### ISSUE TITLE
Should handle ActiveRecord::NotFound exception and display a nice UI for developer not found page

### ISSUE THREAD

**Issue by themudassarhassan** [joemasilotti/railsdevs.com#107]
**Describe the bug**
We are using find method which will throw `ActiveRecord::NotFound` exception if record with the specified id not found

**To Reproduce**
1. Navigate to any developer profile that doesn't exist for example https://www.railsdevs.io/developers/1000

**Expected behavior**
 Should handle that exception and show a nice UI of developer not found with specified id or something like that.

**Screenshots**

<img width="1098" alt="Screenshot 2021-11-18 at 2 05 29 pm" src="https://user-images.githubusercontent.com/31462903/142384748-01c928a5-bba9-426d-a8bb-b123b4fb411e.png">

**Additional context**

**Comment by joemasilotti** [comment]
I'm down for having a better designed 404 page (and even 500 page). There's good examples in TailwindUI we could use almost verbatim. 

But I don't think we need something special for a developer profile not being found.

I also know it will be tricky to bundle Tailwind CSS into the static pages - all styles must be on the page for that to work since they are rendered without the Rails engine (AFAIR).

**Comment by lsparlin** [comment]
@joemasilotti For using the tailwind styles on error pages would you approve of an errors controller similar to this example? https://web.archive.org/web/20141231234828/http://wearestac.com/blog/dynamic-error-pages-in-rails

**Comment by joemasilotti** [comment]
Oooh, probably not. We don't want to render the error pages via Rails. We should keep it static and served via `public/`. If the entire app is down, for example from a configuration error, the Rails-rendered pages might not get displayed at all. 

I'll accept a PR that bundles Tailwind CSS in some way into the static files. Maybe a CDN? Or maybe a build script that copies the latest CSS on deploy. I'm open to ideas. Design-wise, whatever Tailwind UI is doing is fine for now.

**Comment by lsparlin** [comment]
I'll get a PR sent today 😁

**Comment by joemasilotti** [comment]
Closed with #116.
