### ISSUE TITLE
Mobile menu z-index is off

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#109]
**Describe the bug**

The mobile menu is covered by elements on the `Developers#show` page.

**To Reproduce**

1. Visit any developer page (e.g. https://www.railsdevs.io/developers/1) on mobile
2. Open the menu
2. See the avatar and hero covering the mobile menu

**Expected behavior**

The mobile menu should be on top of everything.

**Screenshots**

<img width="493" alt="image" src="https://user-images.githubusercontent.com/2092156/142442667-18ad8574-8b72-4889-9ba3-8e5a47ba2c3d.png">

**Comment by Blaise-Shyaka** [comment]
Hi @joemasilotti, I'd like to work on this.

**Comment by joemasilotti** [comment]
Awesome! Go for it @Blaise-Shyaka.

**Comment by joemasilotti** [comment]
Closed via #112.
