### ISSUE TITLE
Move all copy to translation (locales/en.yml) file

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#110]
**Describe the bug**

Not really a bug, but more a chore. We should move all of the copy to the i18n file `config/locales/en.yml`. This will make our lives much easier if/when we translate to a new language. It also keeps everything in one spot vs. littered across the app.

**Comment by fetijashari** [comment]
Hey @joemasilotti - are you thinking to move all "static text" that currently exist on controllers, views,  components etc - to I18n file (en.yml) ?

**Comment by joemasilotti** [comment]
Yep, exactly!

**Comment by fetijashari** [comment]
Ok - I'll take it :)
