### ISSUE TITLE
Long hero causes page to scroll horizontally

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#113]
**Describe the bug**
If a developer enters a very long Hero then the page shows the entire content and causes horizontal scrolling. 

**To Reproduce**
1. Visit the homepage on mobile
2. Scroll down to the developer in the screenshot

**Expected behavior**
The page doesn't scroll horizontally. 

**Screenshots**
![image](https://user-images.githubusercontent.com/2092156/142737607-7b01d35e-94e8-4386-b177-75c0de6efd26.png)

**Additional context**
This can be done in CSS but I'm not 100% sure which property to use.

**Comment by imrushikesh** [comment]
try -- > 
    overflow-x: hidden;
    width: 100%;

or  give  width to  div having --> 
        Rails Developer/Consultant/Freelancer/Coach


it will fix the problem
