### ISSUE TITLE
areas of developer interests

### ISSUE THREAD

**Issue by briu** [joemasilotti/railsdevs.com#117]
Regarding our recent conversation here https://github.com/joemasilotti/railsdevs.com/issues/45 I suggested to implement something like limited badges, that developers can choose

Additionally, I think it might be useful to add some preferences between the two options, it can help to better understand developer preferences.

For example: 
`ruby` - `other backend languages`
`rails way` - `dry-rb`

I don't know maybe developer can set some percentage proportion 30/70 or 50/50 or something like this 

It can helps employees to choose developers that better match their project conditions. For example, it's good for big projects that currently rewriting their existing monoliths to microservices with golang backend language, that your future ruby developer has some interest in golang. And vice versa for startups it's not valuable if the developer starts to push founders to try any other technology only because he has an interest in it.

**Comment by joemasilotti** [comment]
Oh, interesting idea! I've never seen a sliding scale like that for preferences.

In theory, this could be a lot of fun. But in practice, I worry that a developer might be limiting themselves too much by sliding that scale too far. For example, I _strongly_ prefer minitest over RSpec, so I would set it to 100%. But if a potential client was using RSpec I wouldn't say no, you know?

Instead, I'd rather we add a set list of tags/interests/expertise. Then, each developer can show 3 (maybe 5?) of these on their profile. That limits a developer to choosing the ones that make the most sense for them. Some examples can include React, Hotwire, TDD, minitest, Heroku, AWS, Tailwind CSS, etc.

**Comment by briu** [comment]
I think it makes sense to add a hint with the explanation that this is not an overall developer opinion, but the willingness to work with technology where 0 - I will never work with that technology for any money, 100 - I'll very like(want to try technology) and ready to start work asap. For me, personally, it will be interesting to see this combats stats, I think results can be an argument in many of holly wars 😄 

Interests in technologies is cool too, but this idea is not so fresh, as I know linkedin has something like this, and I think it will be interesting only in limited size and maybe it should be not technologies, but more common things as directions for career growth like `ui/ux/frontend`, `infrastructure/devops`, `oss`, `management`, `high load`

**Comment by joemasilotti** [comment]
Hey @briu, if you're still interested in this can you please open an [Ideas discussion](https://github.com/joemasilotti/railsdevs.com/discussions/new)?

I'm trying to keep Issues for bug reports and work-in-progress tracking. Thanks!
