### ISSUE TITLE
A business can message a developer

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#120]
The ~first~ second (of many) [Messaging](https://github.com/joemasilotti/railsdevs.com/projects/3) issues!

A PR addressing this issue should...

* Add a Message button to a developer's profile
    * When clicked, if signed in as a business then open a new conversation screen
    * When clicked, if not signed in as a business then prompt to create a business profile
* `developers/:id/messages/new` with an input field
    * Create a `Conversation` that belongs to the developer and business
    * Create a `Message` that belongs to the conversation
    * Can only be access by a business (via `pundit`)
* `conversations` index of all conversations the developer or business is a part of (read only)
    * Link to conversations from header / menu
* `/developers/:id/conversation` show a specific conversation (read only)
    * `pundit` for authorization scopes
* Hide the Message button in production based on the feature flag
* Double check mobile views

**Comment by Tonksthebear** [comment]
Do you have any thoughts on how "fancy" to make this feature? Would a simple text field suffice, or would you want to leverage ActionText to accommodate @mentions or other inline features down the line?

**Comment by joemasilotti** [comment]
I'm planning on building this as simple as possible to start. Once the entirety of the Messaging project is done we can come back and add polish, like rich text, images, hyperlinks, etc.

**Comment by Tonksthebear** [comment]
Ok! Are you actively working on this? I'd be happy to whip this up depending on how soon you want it

**Comment by joemasilotti** [comment]
I'm going to take this one. But the next few issues in this project will be open for contributions.
