### ISSUE TITLE
SignalException in at_exit

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#127]
Reported from Honeybadger - https://app.honeybadger.io/fault/93997/ff09c81937af176f383d94deaa5b375e

**Comment by JuanVqz** [comment]
Hi! @joemasilotti is this a solution?

[SignalException or SystemExit is reported when a process or rake task exits
](https://docs.honeybadger.io/lib/ruby/support/troubleshooting/#code-signalexception-code-or-code-systemexit-code-is-reported-when-a-process-or-rake-task-exits)

**Comment by joemasilotti** [comment]
Huh, that's super interesting! I'm curious how it got through then, since there aren't any rake tasks yet. I wonder if a remote console session would be considered one, though?

**Comment by joemasilotti** [comment]
this seems to be a fluke so I'm going to close this for now.
