### ISSUE TITLE
Pagination on developers/index busted

### ISSUE THREAD

**Issue by caseyjenks** [joemasilotti/railsdevs.com#128]
I noticed it's only rendering the most recent 20 developers, and it doesn't ever load in more developers. Something with Pagy and Turbo maybe?

**Comment by joemasilotti** [comment]
Thanks for reporting @caseyjenks! Feel free to submit a PR if you know what's going on.

@Tonksthebear, I believe [you originally implemented this](https://github.com/joemasilotti/railsdevs.com/pull/76). Any chance you can take a look?

**Comment by Tonksthebear** [comment]
I'm just taking a peek real quick and I can't put together a PR, but looks like the regression took place when the original `<ul id="developers">` was replaced with `<%= render DeveloperCardComponent.with_collection(@developers) %>`.

If you swap
```
<div class="space-y-8">
  <%= render DeveloperCardComponent.with_collection(@developers) %>
</div>
```
with 
```
<div class="space-y-8" id="developers">
  <%= render DeveloperCardComponent.with_collection(@developers) %>
</div>
```
It should all work as expected. Leaving that id off looks like the culprit!

**Comment by joemasilotti** [comment]
Love it. Fixed and pushed - thanks everyone!
