### ISSUE TITLE
ActionView::SyntaxErrorInTemplate

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#135]
https://app.honeybadger.io/fault/93997/0ca3455881e766d2cd91727e54d129ff

**Comment by joemasilotti** [comment]
@fetijashari can you take a look at this? I believe it's caused by the translation changes we made.

**Comment by fetijashari** [comment]
Hey @joemasilotti,

Yes  and solved ! :)

**Comment by joemasilotti** [comment]
Awesome, thank you!
