### ISSUE TITLE
Currency changing

### ISSUE THREAD

**Issue by pacMakaveli** [joemasilotti/railsdevs.com#142]
**Is your feature request related to a problem? Please describe.**
I would like to be able to change my currency. It currently defaults to $, but not everyone is in the US.

**Describe the solution you'd like**
I think this should be split into multiple pull requests, each with the following:

1. Add the ability to select the currency in the `Preferred compensation` panel.
2. As a recruiter, add the ability to select my preferred currency I'd be willing to pay with.
3. Behind the scenes, when viewing a developer profile, the currency should adjust accordingly.

For example, if Company A has currency in $ and wants to hire Developer A which has currency in £, the platform should adjust the preferred compensation accordingly.

If you're happy with the current feature request, I'd be happy to take a stab at this early next year.

**Comment by joemasilotti** [comment]
Thanks for the feature request! I'd love to dive into this, but right now I'm trying to focus efforts on [Messaging](https://github.com/joemasilotti/railsdevs.com/projects/3) and [Payments](https://github.com/joemasilotti/railsdevs.com/projects/4). Once those are done I will be able to take a step back and look at what's next feature-wise.
