### ISSUE TITLE
Show the developer's real name to business subscribers

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#189]
Showing the developer's real name both in their profile and on the new conversation screen will go a long way in making first contact more seamless.

**Comment by jacobdaddario** [comment]
I can pick this up tomorrow @joemasilotti

**Comment by joemasilotti** [comment]
Sounds great, thank you! I'll comment on that issue with some thoughts.

**Comment by joemasilotti** [comment]
Heads up that I still want to show the hero as the primary text. The real name can appear near the hero copy and less prominent. Perhaps something like this could work.

<img width="643" alt="image" src="https://user-images.githubusercontent.com/2092156/147573482-c55c987a-7762-4623-b648-f9629b5aedff.png">
