### ISSUE TITLE
Bug: Flakey test suite

### ISSUE THREAD

**Issue by jacobdaddario** [joemasilotti/railsdevs.com#194]
**Describe the bug**
Occasionally when running the test suite, random tests will error due to attempting to access the same database as another test. I wonder if this has to do with test parallelization? I'm seeing the test run with 4 simultaneous processes. The error being thrown by the test suite is as follows.

```
DRb::DRbRemoteError: PG::ObjectInUse: ERROR:  database "railsdevs_test-3" is being accessed by other users
DETAIL:  There is 1 other session using the database.
```

**To Reproduce**
1. Pull the repo from main.
2. Run the test suite and get a few errors 1 every 2 or 3 suite runs.

**Expected behavior**
The test suite should pass consistently.

**Additional context**
Initially I thought this might be a bug in the code regarding transactions, but it even is hitting model tests. I didn't realize that Rails would shard test databases sometimes, so I can only assume this is from parallelization. @joemasilotti can you think of anything that you added recently that could cause this?

**Comment by joemasilotti** [comment]
Whoa, that's really weird. I just ran the test suite, freshly cloned from `main`, 20 times in a row and they all passed. Very odd that it is only happening every few runs, and not all the time. CI has also never run into this issue.

What machine/OS/etc are you on?

**Comment by jacobdaddario** [comment]
> 20 times in a row and they all passed. 
That's extremely strange.

I'm running a MacBook Air 2019 on MacOS Monterery v 12.1.

**Comment by jacobdaddario** [comment]
Update:

The 'ol diesel engine in my brain finally got booted up, and I thought to reboot the Postgresql brew service running on my Mac. Issue just completely disappeared. Closing this issue under the assumption that this most have been some rogue error with Rails test parallelization, the Ruby PG gem, or Postgres itself.
