### ISSUE TITLE
Paginate notifications

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#200]
`/notifications` and `read_notifications` can get long, especially for admins, so should be paged.

`/developers` has an infinite scroll example powered by pagy and Turbo which could be replicated for these two views.

Now that #133 is merged in this can be addressed with the new component!

**Comment by imella** [comment]
Hey @joemasilotti! If you don't mind, I can pick this one!

**Comment by joemasilotti** [comment]
Sure, go for it! I'll add it to the [In progress column](https://github.com/joemasilotti/railsdevs.com/projects/6).
