### ISSUE TITLE
Email paying businesses when new developer profiles are added

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#208]
Paying customers shouldn't have to manually check railsdevs to see if there are any new developer profiles. Instead, they should receive daily or weekly emails linking to all of the new profiles added that day or week, respectively.

A PR addressing this should handle the following:

- [ ] Add a new column to the `Business` model,`new_developer_notifications`, as an enum with values `none`, `daily`, and `weekly`; defaulted to `none`
- [ ] Add an option for this field on `/businesses/:id/edit`
- [ ] Add a job that gathers developer profiles added in the last 24 hours and last 7 days and sends a respective email to paying customers based on their preference
- [ ] Run this job every day at 9am EST
- [ ] Add an unsubscribe link to the bottom of the email that links to editing their business profile
- [ ] Highlight the feature on the `/pricing` page

**Comment by jacobdaddario** [comment]
I'd be happy to take this on. It might take a week or so since I need to close my existing PR and work a bit on a personal project this week.

**Comment by joemasilotti** [comment]
Sounds great! I assigned it to you. Thanks Jacob.

**Comment by jacobdaddario** [comment]
I had Railsdevs open tonight, so I began working on this. Realistically, I probably won't finish up until some time next week.
