### ISSUE TITLE
Add tests for avatar and cover photo uploads

### ISSUE THREAD

**Issue by jacobdaddario** [joemasilotti/railsdevs.com#21]
We need to determine how we're going to go about testing the avatar uploads in #20. This breaks down into basically two items.

1. Are we okay with using shoulda matchers? This is the recommended way to test file attachments according to the `active_storage_validations` gem. I've never personally used them.
2. How do we handle file fixtures? I need to do some investigation to figure this out, but I wanted to put it out there in case anyone else knew.

**Comment by jacobdaddario** [comment]
Going to go ahead and handle this now that #60 is ready to be merged.

**Comment by joemasilotti** [comment]
Hey @jacobdaddario, this has been open for a month now. I'm going to close it to clear out old issues.

Feel free to open it up again or open a PR if you get around to working on it.

**Comment by jacobdaddario** [comment]
😱 In the craziness of the holidays and fresh-installing my Mac I completely forgot about this. I'm re-cloning my fork and pulling down all of the changes now. Sorry about that! I had been kind of proud of staying on top of stuff for this project, and I'm embarrassed I forgot about this.

**Comment by joemasilotti** [comment]
No worries at all! Enjoy the holidays and get to this whenever. No rush - it all seems to be working fine in production now.
