### ISSUE TITLE
More robust database seeds

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#213]
Currently, the seeds file `db/seeds.rb` only contains the bare minimum to interact with the site in development. I'd love for this to contain more "real" information so we can test things like pagination and all the different `Developer` fields without having to manually create data.

For example,

* 20+ `Developer` records (to trigger pagination)
* 20+ `Notification` records (to trigger pagination) - 20 developers should handle this for the admin account
* `Developer` records with some fields filled in, some not, and all sorts of combinations
* `Developer` records with avatars and cover images
* More "real" `Business` records, like one without a paying subscription

Please follow the guidelines of the current 3 developers - the are "real" profiles but pulled from Wikipedia and/or made up. They aren't an actual person that is alive today. I also would strongly prefer to _not_ use a gem like `faker` to generate name and emails and such.

**Comment by marlomorales** [comment]
@joemasilotti 
is it ok to work on this one? 🤔
i'll start doing this, after i successfully setup my dev environment. 🙂

**Comment by xmarlox** [comment]
@joemasilotti 

is it ok to work on this one? 🤔
i'll start doing this, after i successfully setup my dev environment. 🙂

**Comment by joemasilotti** [comment]
Sounds great! Reply when you're good and I'll assign it to you. 

Also, check out this post on moving seeds to a job. If you have the appetite that would be awesome, too. I really like the idea of printing out a email/password after setup to let the developer who know to sign in. 

https://stevepolito.design/blog/rails-setup-script-improvements/

**Comment by joemasilotti** [comment]
Heads up that there is a PR that is being worked on to fix some issues in the seeds: #242.

**Comment by xmarlox** [comment]
@joemasilotti 
got it! i'll keep you posted. thanks!

**Comment by xmarlox** [comment]
@joemasilotti 
all good now
ready to submit PR 😄

**Comment by joemasilotti** [comment]
Assigned - all yours!

**Comment by joemasilotti** [comment]
#242 is merged in!

**Comment by xmarlox** [comment]
@joemasilotti 
here's the [PR](https://github.com/joemasilotti/railsdevs.com/pull/244/files) for this issue
