### ISSUE TITLE
Add system tests for pagination

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#214]
A PR addressing this issue should configure system-level tests, with JavaScript enabled, via minitest. It should also test the pagination feature for `/developers` and/or `/notifications` (whichever is easier).

**Comment by salochara** [comment]
I can work on this 🖐️

**Comment by joemasilotti** [comment]
All yours!

**Comment by joemasilotti** [comment]
Closed via #221.
