### ISSUE TITLE
Encrypt `Message.body`

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#217]
To farther secure application data, the content of private messages should be encrypted. Rails 7 introduced [Active Record Encryption](https://edgeguides.rubyonrails.org/active_record_encryption.html) which should handle most if not all of the work for us.

A PR addressing this issue should:

- [ ] Encrypt `Message.body`
- [ ] Create a script to run in production to migrate existing messages
- [ ] Gracefully display the text "Encrypted content" if a production database dump is accessed in development for debugging

**Comment by xmarlox** [comment]
@joemasilotti 
this one is much challenging. i'll work on this one unless you want me to work on something else. 😅

**Comment by joemasilotti** [comment]
Let's hold off on this one for now.
