### ISSUE TITLE
Message email should link to sign in

### ISSUE THREAD

**Issue by coder2000** [joemasilotti/railsdevs.com#218]
**Describe the bug**
Currently the message email links to the sign up page. If someone is receiving a message it is safe to assume they are already signed up and a step can be skipped by linking to sign in.

**To Reproduce**
Click link in email saying you received a message.

**Expected behavior**
Link directly to the message if session is still active, otherwise redirect to sign in.

**Comment by joemasilotti** [comment]
This [wiki from Devise](https://github.com/heartcombo/devise/wiki/Redirect-to-new-registration-(sign-up)-path-if-unauthenticated) is how I originally customized the redirection. I'm not sure how we can have a conditional redirection, though. Ideally, `authenticate_user!` in `NotificationsController` has a way to customize the route.

**Comment by coder2000** [comment]
```
  def authenticate_user_with_sign_up!
    unless user_signed_in?
      store_location_for(:user, request.fullpath)
      redirect_to find_store_register_path, alert: "You must have an active account to access this page."
    end
  end
```
This is how I redirect for all my controllers, could adapt something like this as a before action.

**Comment by joemasilotti** [comment]
Hmm, I feel like that kind of completely diverts away from Devise's internal plumbing. I'd rather continue to use Devise's method which takes care of this already (and some more).

**Comment by dhairyagabha** [comment]
I would like to take a look at this as my first issue contribution, if that is okay?

**Comment by joemasilotti** [comment]
Sure thing, all yours @dhairyagabha!

**Comment by dhairyagabha** [comment]
Hey @joemasilotti 

I haven't been able to get to this. Please feel free to open it up. If I find a fix, I will request and open a PR.

**Comment by kaushikhande** [comment]
@joemasilotti I have attached a PR for this issue. Please review.
