### ISSUE TITLE
Translations?

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#219]
Most of the site's copy has been moved to [`locales/en.yml`](https://github.com/joemasilotti/railsdevs.com/blob/main/config/locales/en.yml) thanks to @fetijashari. I'd love if we could start taking advantage of this and being translating to other languages besides English!

If you are interested in helping out, let me know by replying below. I'm not fluent in anything other than English.

---

Ideally, non-English locales should fail safely. Meaning, if we are missing a Spanish translation it should fallback to the English copy for now. This ensures we can continue to update the site without being held back by translating into other languages after the initial bulk of the work is done.

Also, if we can add a rake task that shows which translations are missing for which language that would be awesome. I'm pretty sure the `i18n-tasks` gem, which is already configured, can help us there.

**Comment by salochara** [comment]
Hey! 👋 

I'll happily help with this. 
Spanish is my native tounge, so I can definitely work on this!

I'll work on this during the weekend 😄

**Comment by joemasilotti** [comment]
Amazing – thank you so much! I'm sure there will be some places where translations are missing. Feel free to extract those or ping me and I can take care of it.

**Comment by hungmi** [comment]
HI!
It's so cool that railsdevs.com is going to be an international service.
I can and I want to do translations to Chinese Traditional/Simplified.
And I think this can be extended to Japanese in the future.
I am not a professional designer, but [some design changes](https://medium.com/dropbox-design/design-for-internationalization-24c12ea6b38f) may be needed in the future.
What is your thought about this? 😊

**Comment by salochara** [comment]
Hey! 👋 

Just a quick update from my side.. I didn't have much time during the weekend to work on this. 
I'll be working on this hopefully during the week (or most probably during the weekend). 
I've been quite busy at work 😅

**Comment by joemasilotti** [comment]
@hungmi,

> It's so cool that railsdevs.com is going to be an international service.

I'm excited too! This will be my first app I've worked on with translations, so I'm going to be learning a lot here.

> I can and I want to do translations to Chinese Traditional/Simplified. And I think this can be extended to Japanese in the future.

❤️ Thank you!

> I am not a professional designer, but some design changes may be needed in the future. What is your thought about this? 😊

If we have to make changes that's fine by me. I vote we apply the translations first then see what looks weird before doing anything upfront.

**Comment by joemasilotti** [comment]
@salochara, no worries! Whenever you get to it is fine :)

**Comment by freebian** [comment]
Hi @joemasilotti, 

thank you so much for making this open source!
I plan on contributing also on functions/features but I need to dive into your code a lot deeper to understand it all 😅
(I am a freelance UX person, self-thought ruby/rails to build my own online businesses)

In the meantime I could provide the German translation.
I am German and it is my mother tongue. Primarily I am working in UX so I am confident my translations won't be too crappy. 

Let me know what you think.

**Comment by joemasilotti** [comment]
That sounds great, thank you for the offer! Once we have a solid workflow for switching between languages and some tooling (see my comment above), adding new languages should only require the locale file.
