### ISSUE TITLE
View notifications as a lazy-loaded dropdown

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#220]
I'd love for the notification bell to link to a lazy-loaded dropdown powered by Turbo. This aligns more closely with modern web apps (instead of linking to a new page).

A PR addressing this issue should:

- [ ] Add a desktop and mobile dropdown when clicking the bell icon
- [ ] Render the content via a lazy-loaded Turbo frame (meaning, only load it after someone clicks it) with a spinner
- [ ] Display the 5 most recent unread notifications
- [ ] Link to "All notifications" at the bottom
- [ ] Have an empty state if there are no unread notifications and link to "Read notifications"

**Comment by jacobdaddario** [comment]
Saw this when I sat down for lunch. #202 is wrapping up already, so I'd be happy to take this. I'm pretty confident with Turbo.

**Comment by joemasilotti** [comment]
Awesome! Once we wrap up #212 and it's merged in I'll assign this to you.
