### ISSUE TITLE
In /developers add my profile button shows when user is logged in

### ISSUE THREAD

**Issue by imella** [joemasilotti/railsdevs.com#229]
**Describe the bug**
I don't know to actually classify this as a bug, because maybe it's intended. 

I find it weird that something that invites you to create a profile shows up when you already have one.

Maybe add a button to your existing profile or it could be used in the future to tell the developer/business that they need to update it in the case new required fields are added.

**To Reproduce**
1. Sign in as a business or developer
2. Go to `/developers`
3. See `add my profile` button

**Screenshots**
<img width="1268" alt="Screen Shot 2022-01-09 at 20 43 24" src="https://user-images.githubusercontent.com/741631/148706694-510b3153-d7cc-40cf-a32b-e1cc36a2d026.png">

**Comment by joemasilotti** [comment]
Ah, good point! Do you have appetite to fix this? I'd love to have this turn into a secondary button (white background) that says "Edit my profile" if you already have one. If not, then hiding it if you already have one would be good enough for a first pass.

**Comment by imella** [comment]
Great! Yeah, I can go for it!

**Comment by salochara** [comment]
Hey 👋 
I can take this one, if that's okay!

**Comment by joemasilotti** [comment]
Sure thing! As long as @imella isn't planning to work on it.

**Comment by joemasilotti** [comment]
@salochara and @imella, are either (both?) of you working on this? Let me know and I'll assign it over to you. I don't want to duplicate effort :)

**Comment by salochara** [comment]
Nope. I haven't worked on this yet. I was waiting for @imella response :)

**Comment by dhairyagabha** [comment]
@joemasilotti Added #301 to fix this. Take a look when you get a chance.
