### ISSUE TITLE
Move public revenue and expenses in-house

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#234]
Currently, the public revenue and expenses [live on Notion](https://same-legend-a38.notion.site/railsdevs-revenue-and-expenses-c28706a1b3a846d4a058e4fef135aa67). I'd love to move these three tables and rendering into the codebase.

<img width="949" alt="image" src="https://user-images.githubusercontent.com/2092156/148998966-334dd7f1-a407-4397-8153-6bc628be142d.png">

Ideally, we don't have to calculate anything manually. So the few SUM columns should be done in Ruby (or the database). Quickly sketching this out, we could have a few YAML files that get read in and spit out into nice looking HTML styled with Tailwind UI. The [Simple striped](https://tailwindui.com/components/application-ui/lists/tables#component-d60e8c748260b622747ec1568ba9c509) table looks perfect for this use case.

<img width="1387" alt="image" src="https://user-images.githubusercontent.com/2092156/148998836-788eadd6-63cb-40c4-9179-89a125ee8d12.png">

If you want to want to work on this but don't have access to Tailwind UI then feel free to open a PR with an un-styled table and I can finish it up.

---

This is a great first issue for someone to pick up because you don't need to know a lot about the existing codebase to get started.

**Comment by vluna** [comment]
@joemasilotti I would like to give it a try if possible 🙂

**Comment by joemasilotti** [comment]
Sure thing! It's all yours :)

**Comment by joemasilotti** [comment]
Closed via #270.
