### ISSUE TITLE
Add "role type" filter

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#235]
A PR addressing this issue should add a new filter to `/developers` so folks can filter profiles by what type of role they are interested in. Most of the code can be modeled after the time zone filter with the exception of this being a join model on `RoleType`.

**Comment by themudassarhassan** [comment]
Hey @joemasilotti 
I would like to work on this one if not already taken.

**Comment by joemasilotti** [comment]
That would be great, thank you! All yours.

**Comment by joemasilotti** [comment]
Closed via #251.
