### ISSUE TITLE
Add "looking for" filter

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#236]
Similar to #235 but for the "looking for" field on the developer profile.

**Comment by themudassarhassan** [comment]
@joemasilotti after merging of #251 I would like to take on this one.

**Comment by joemasilotti** [comment]
Thank you! Let's get that one merged in first before we move on to this. I just posted a review with some change requests.

**Comment by joemasilotti** [comment]
@themudassarhassan all yours! Thanks again for the other PR.

I think we can use "Search status" as the title of the dropdown to match the developer form.

**Comment by themudassarhassan** [comment]
@joemasilotti sure will work on this in the coming weekend. It is really great working with you!

**Comment by joemasilotti** [comment]
Closed via #268.
