### ISSUE TITLE
Missing Stripe production instructions in Wiki

### ISSUE THREAD

**Issue by bencgreenberg** [joemasilotti/railsdevs.com#238]
**Describe the bug**

The README does a great job of walking a user through setting up their Stripe dev/test environment, but the same is not done on the production settings in the Wiki. Specifically, a link should be added to the production settings with a brief instruction on setting up the production webhook for Stripe. 

If the webhook is not set up, subscriptions won't be created successfully in the app, and for new users of Stripe and new developers using this codebase, it may produce a ambiguous experience of trying to locate what went wrong in the code, when what was missing was the webhook creation within Stripe.

**Comment by joemasilotti** [comment]
I added more documentation at the bottom of the [production settings](https://github.com/joemasilotti/railsdevs.com/wiki/Production-settings) wiki page.
