### ISSUE TITLE
db:seed => Validation failed: Avatar is not attached, Time zone can't be blank

### ISSUE THREAD

**Issue by bugdimes** [joemasilotti/railsdevs.com#243]
**Describe the bug**
While running `bin/setup` I am getting the error, need to populate it as well while running `bin/rails db:prepare`

**To Reproduce**
run `bin/setup`

**Comment by joemasilotti** [comment]
Thanks for documenting! This is being fixed in PR #242, which should be merged in soon.

**Comment by joemasilotti** [comment]
Closed via #242.
