### ISSUE TITLE
Profile images do not keep attached on form error

### ISSUE THREAD

**Issue by gmmcal** [joemasilotti/railsdevs.com#249]
**Describe the bug**
When creating (and probably updating) profile, if some text field is invalid and user uploads an image, preview of image is shown on error page, but when user tried to save again, a new error pops saying image was not uploaded.

**To Reproduce**
1. Go to 'https://railsdevs.com/developers/:id/edit' on newly created profile
2. Remove data from one of mandatory fields
3. Upload a new image
4. Click on `Save`
5. Error of mandatory field should show on page, as well as image preview
6. Add content to missing field
7. Try to save again
8. Error of image not uploaded should show up

**Expected behavior**
Profile should be saved correctly after mandatory field is filled

**Comment by joemasilotti** [comment]
Thanks for bringing this up! I think this bug has existed since launch 😆

Do you have appetite to fix it? IIRC, I was stumped as to what was going on.

**Comment by gmmcal** [comment]
@joemasilotti I can do it, but I can't commit to timeline atm. If it is fine for you, assign to me

**Comment by joemasilotti** [comment]
No worries on timeline. Let me know when you want to dive in and submit a PR or I'll assign it to you.

**Comment by gmmcal** [comment]
@joemasilotti FYI, PR for this is created
