### ISSUE TITLE
www subdomain is in google but not accessible

### ISSUE THREAD

**Issue by robbyrussell** [joemasilotti/railsdevs.com#254]
**Describe the bug**

I searched google.com for `site:railsdevs.io` and results include `www.railsdevs.io` URLs, which are not currently accessible.

**To Reproduce**
1. Go to [these results](https://www.google.com/search?q=site%3Arailsdevs.io)
2. Click on any of the links

**Expected behavior**

Application should probably either a) redirect to non-www and/or b) load the page but have a canonical tag that points to the non-www URL.

**Screenshots**

![site:railsdevs io - Google Search 2022-01-21 16-06-49](https://user-images.githubusercontent.com/257/150615421-d6faef36-4af3-4a38-b1b9-3d34f4fcb248.png)

**Comment by joemasilotti** [comment]
The site is .com now, not .io. I'm not sure how to remove those results from google.

**Comment by jacobdaddario** [comment]
If you still own the old URL, could we set up some kind of proxy/redirect?

**Comment by tarellel** [comment]
I'm not sure if you your using nginx, traefik, etc.
But you could probably set it up to catch both URL's instead of railsdev.com specifically.
Or just do redirect with the webserver

**Comment by joemasilotti** [comment]
I have a redirect set up with my registrar but it doesn't work for www. I've debated moving it over to namecheap but don't want to pay for .io for another year if the site is already in .com. 

I think the solution here is to not search on Google for an unsupported domain and use the .com.

**Comment by joemasilotti** [comment]
I'm going to close this. I don't have appetite to try and fix these redirect issues with the old domain.
