### ISSUE TITLE
Bring back Turbo to the business form

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#259]
I recently [removed Turbo from the business form](https://github.com/joemasilotti/railsdevs.com/commit/888ca8819318370aa75ab53df92c09136981c6c2) so it can redirect to Stripe without issue. @kobaltz [tweeted about a Stimulus controller](https://twitter.com/kobaltz/status/1485459044831739908?s=20) that should get around this issue.

I haven't tested it yet, but maybe that will work!

**Comment by dhairyagabha** [comment]
Hey @joemasilotti 

I will try to take a shot at this. Might need some guidance on some testing steps.

**Comment by joemasilotti** [comment]
Thanks! All yours.

**Comment by dhairyagabha** [comment]
Hey @joemasilotti 

I was playing around with it and seems that it required importing a entire Stripe Javascript to create a checkout instance and redirect to checkout based on Dave's comment. 
Two thoughts:

1. If you want to use Turbo with Business From, send the redirect URL in a turbo_stream and let a stimulus controller redirect the user directly from client side by changing `window.location` - _Keeps it in check with RailsWay by using Turbo._
2. Redirect the url from the `BusinessesController#show` to the `stripe_checkout_path`. - _Workaround to avoid another library._

Thoughts?

**Comment by joemasilotti** [comment]
Ah, good catch. I'd definitely like to avoid that if we can.

Does setting `window.location` break any sort of back behavior or Turbo workflow? I'm guessing doing something like `Turbo.visit(url)` doesn't work, right?

**Comment by dhairyagabha** [comment]
I will review that. I thought of raw javascript only. Will review Turbo options further more.

**Comment by dhairyagabha** [comment]
After review, it seems that Turbo will not be able to help us with this. There is excellent debate on this subject in the [Trubo Repository Issues](https://github.com/hotwired/turbo/issues/401#issuecomment-1032492888).

Ultimately, their solution was also to use a Stimulus Controller to simply update the window location. Since Turbo also updates the history, it should not break any behavior.

@joemasilotti  thoughts?

**Comment by joemasilotti** [comment]
If it's the recommended approach and doesn't require the Stripe JS library then that sounds good to me!

**Comment by dhairyagabha** [comment]
@joemasilotti PR added. Please closely review the tests. I have adjusted things as I saw fit but want to make sure all areas are covered.

**Comment by dhairyagabha** [comment]
@joemasilotti This is still soon my list. I will get back to this as soon as possible.

**Comment by joemasilotti** [comment]
Awesome, thanks for the update! A heads up that some flows around billing/Stripe have changed and there are now a few more non-Turbo forms.

**Comment by dhairyagabha** [comment]
Hey @joemasilotti please take a look at the comment on the PR when you get a chance

**Comment by joemasilotti** [comment]
Closed in favor of #483.
