### ISSUE TITLE
Replace :id segment from url to slug

### ISSUE THREAD

**Issue by XaoGao** [joemasilotti/railsdevs.com#261]
Hi, show id in url for developers is security danger and i think some ugly. May be we could change id segment to slug, add new column to Developer and Business, edit routes and fix link_to. Already exist popular gem for this https://github.com/norman/friendly_id/

**Comment by joemasilotti** [comment]
Why is showing the ID a security danger? Can you link to Rails documentation recommending against this or a report on how it can open up an attack vector?

**Comment by XaoGao** [comment]
In terms of accessing data is safe. This is not a direct vulnerability. First: All people can see ham many developers have account, i think it some "business sensitive" data. Second: showing the key is an "invitation" for database parser. But if you think this is not require, it is not a big problem

**Comment by joemasilotti** [comment]
Being an open startup I'm not too worried about folks knowing how many developers there are on the site. I actually plan to make that even more public in the future.

I'm not sure I follow how a database parser would work, to be honest. Can you explain?

**Comment by joemasilotti** [comment]
I'm going to close this issue but we can continue to have a discussion here!
