### ISSUE TITLE
An email notification is sent even if no new developer profiles were added

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#266]
**Describe the bug**
I received an email notification saying "0 new developer profiles were added" this morning.

**To Reproduce**
1. Ensure no developers were added "yesterday"
1. Trigger the daily email notification script

**Expected behavior**
No one should receive an email.

**Actual behavior**
Everyone receives an email stating "0 new developer profiles added to railsdevs".

**Screenshots**
<img width="1119" alt="image" src="https://user-images.githubusercontent.com/2092156/151705092-df2b5680-1d78-41e6-a4a9-98f6642ab9d7.png">

**Comment by salochara** [comment]
Hey 👋 
I'll be happy to work on this one!

**Comment by joemasilotti** [comment]
All yours, thanks!

**Comment by jacobdaddario** [comment]
Oops! Sorry for this bug 😅
