### ISSUE TITLE
Filters are not applied to pagination

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#269]
**Describe the bug**
The second (and so on) page of filtered developers ignores the selected filters.

**To Reproduce**
1. Go to `/developers`
2. Apply a filter (sorting by availability works)
3. See that all developers are in the filter (all "Available now")
4. Scroll so pagination triggers the second page

**Expected behavior**
Second page of developers are also filtered (all "Available now").

**Actual behavior**
Second page of developers are not filtered (some are not available).

**Screenshots**
<img width="1066" alt="image" src="https://user-images.githubusercontent.com/2092156/151994975-a2049a0c-1945-42f7-a3b2-c593cc299313.png">

**Comment by kaushikhande** [comment]
@joemasilotti hi
Can I work on this bug?

**Comment by joemasilotti** [comment]
Yes, please! All yours @kaushikhande.

**Comment by kaushikhande** [comment]
@joemasilotti Please review

**Comment by joemasilotti** [comment]
Fixed via #272.
