### ISSUE TITLE
Email confirmation redirects to wrong page. 

### ISSUE THREAD

**Issue by phil-6** [joemasilotti/railsdevs.com#279]
**Describe the bug**
When clicking the "Confirm Email" button in the confirmation email. The user is redirected to this page:
![image](https://user-images.githubusercontent.com/29845460/153453963-03469bb9-debd-4907-930d-8d7b04a3f334.png)

**To Reproduce**
Sign up as a new user. Go to confirmation email and click "confirm email"

**Expected behaviour**
Redirect you to home page or login page after email has been confirmed.

**Comment by phil-6** [comment]
Hey @joemasilotti,

Interesting! I love to hate these hard to replicate bugs. 

It might have been a double click on the button in the email. Occam's Razor suggests that would be the cause, especially considering your devise setup is fairly out-of-the-box.

Thank you for investigating!

**Comment by joemasilotti** [comment]
Gotcha. Thanks! I'm going to close this now until we can reliably reproduce it. Feel free to reopen it if it happens again.
