### ISSUE TITLE
Menu flashing on full page load

### ISSUE THREAD

**Issue by kstratis** [joemasilotti/railsdevs.com#284]
**When doing a full page refresh on `/developers`, the sort and filter menus momentarily flash**

**Reproduce**
1. Go to `/developers`
2. Hit refresh
3. Notice that -for a brief second- all filtering menus are fully open 

**Expected behavior**
The menus should be hidden and only open up if the user clicks on them

**Video/Proof**
Turned it down to "Slow 3G" for demonstration. Just wait for it.

https://user-images.githubusercontent.com/1859806/154079769-dfa7fcf8-4484-40a3-a30b-67e973747100.mp4

**Additional context**
The problem seems to be located somewhere [along these lines]( https://github.com/joemasilotti/railsdevs.com/blob/61105c0363596d885ccd6b2ffa18d10b359c88ec/app/components/developer_query_component.html.erb#L15). What's effectively happening here is that we load the page without the `hidden` class present and only after stimulus connects, `#toggle` is called and `hidden` is added. That's why we see the flash: It's actually the interval before JS kicks in. It should be the other way around though: `hidden` should be set in the DOM on page load and only by clicking on the menu stimulus should remove the class. 

I think this also explains the fact that during page navigation you don't see any issues (stimulus is already loaded in memory and `#toggle` is instant). 

If you're interested @joemasilotti, I could prepare a PR for it (at least for the `/developers` page).

**Comment by joemasilotti** [comment]
Thanks for documenting this! Yes, please submit a PR adding the `hidden` classes to the DOM. If you see any other spots where this is happening please let me know, too.
