### ISSUE TITLE
bin/setup failed

### ISSUE THREAD

**Issue by hungmi** [joemasilotti/railsdevs.com#287]
**Describe the bug**
I got two situations when I want to setup a new database for development.

### The first one
Rails is complaining about a wrong migration file name:
```bash
-- create_table(:pay_webhooks)
   -> 0.0011s
== 20211218203645 CreatePayTables: migrated (0.0117s) =========================

rails aborted!
NameError: uninitialized constant AddUTCOffsetToDevelopers

      Object.const_get(camel_cased_word)
            ^^^^^^^^^^
Did you mean?  AddUtcOffsetToDevelopers


Caused by:
NameError: uninitialized constant AddUTCOffsetToDevelopers
```
**To Reproduce**
`RAILS_ENV=development rails db:drop db:create db:migrate`

**Additional context**
According to https://stackoverflow.com/a/43814860/5005466, this has something to do with `config/initializers/inflections.rb`: https://github.com/joemasilotti/railsdevs.com/blob/a31ac059e689b1aa9d8b3abc8c2d1ce714ca45d3/config/initializers/inflections.rb#L16
I have no experience with this configuration.
Maybe we can avoid using `utc` in constants? Or change them to be like `AddUTCOffsetToDevelopers`.

---
### The second one
`rails db:seed` fails because the `Developer` is creating a `location` with null value in `time_zone` column.
```bash
ActiveRecord::NotNullViolation: PG::NotNullViolation: ERROR:  null value in column "time_zone" of relation "locations" violates not-null constraint
DETAIL:  Failing row contains (1, 1, null, null, null, null, null, null, null, null, null, 2022-02-20 08:58:52.697421, 2022-02-20 08:58:52.697421).
/Users/hungmingtsai/Workspace/railsdevs.com/db/seeds.rb:12:in `create_developer!'
/Users/hungmingtsai/Workspace/railsdevs.com/db/seeds.rb:24:in `<top (required)>'
```
```ruby
def create_developer!(attributes)
  avatar_name = attributes.delete(:avatar_name)
  Developer.create!(attributes) do |developer|
    developer.avatar.attach(io: File.open(Rails.root.join("test/fixtures/files/#{avatar_name}")), filename: avatar_name)
  end
end
```

**To Reproduce**
`RAILS_ENV=development rails db:drop db:create db:migrate && rails db:seed`

**Additional context**
I am not sure how `Location` works, so I am not able to figure out a good way to fix this.

**Comment by joemasilotti** [comment]
The inflection is so we can name things like `UTCOffset` instead of `UtcOffset` which I personally things reads nicer. But I forgot to update the old migration name to reflect the change.

Location requires a city, state, and/or country to kick off the geocoding and belongs to a developer.

---

I fixed both issues in the latest two commits on `main`. Can you give this a check and if it's working for you please close the issue?

**Comment by hungmi** [comment]
It's working now👍👍👍
