### ISSUE TITLE
Looking for role level

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#292]
The goal of this issue is for developers to add what level of role they are looking for in their next gig. Think junior developer, mid-level, senior, etc.

A PR addressing this issue should:

* Add a new field to the developer form, "Role level"
    * Add this under the "Work preferences" section
    * Subtitle it with "Select all the experience levels you would consider taking."
    * Add the following options as checkboxes:
        * Junior
        * Mid
        * Senior
        * Principal/staff
        * C-level
* Display the selected options on the public developer profile after "Interested in roles" matching that design
* Modeling-wise, this could be a new table/model like `RoleType`

The PR should not address:

* Filtering on /developers for this new field

**Comment by kaushikhande** [comment]
@joemasilotti Can I take this issue?

**Comment by joemasilotti** [comment]
All yours!

**Comment by kaushikhande** [comment]
@joemasilotti Added PR https://github.com/joemasilotti/railsdevs.com/pull/300. Please review.

**Comment by joemasilotti** [comment]
Closed via #300.
