### ISSUE TITLE
Filter /developers on mobile

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#293]
Currently, the filters on `/developers` are only visible on desktop and tablets. A PR addressing this issue should add the same filters to the mobile version of the site.

I don't think we need a new Stimulus controller - a couple of nested `ToggleController.js` controllers should do the trick.

---

The existing filtering design was based off of the [With centered text and dropdown product filters](https://tailwindui.com/components/ecommerce/components/category-filters#component-cb75aacd7c636865835476c98f606a38) from Tailwind UI. Here are the comparisons of desktop to mobile.

<img width="1371" alt="image" src="https://user-images.githubusercontent.com/2092156/155604930-62e90af5-ef7a-462a-936c-5013df88968c.png">

<img width="532" alt="image" src="https://user-images.githubusercontent.com/2092156/155604955-5507d3cd-56a2-45dd-9e12-0d7df0348967.png">

<img width="559" alt="image" src="https://user-images.githubusercontent.com/2092156/155604987-a89831b5-4e66-4ad3-af93-fc7493b84e91.png">

Please only work on this issue if you have access to Tailwind UI. I want to keep the markup and classes the same so changes in the future are easier.

If you _really_ want to work on this but don't have access to Tailwind UI then [email me](mailto:joe@masilotti.com) and we can work something out!

**Comment by dhairyagabha** [comment]
@joemasilotti I would like to take this if possible

**Comment by joemasilotti** [comment]
All yours – thanks for the offer!

**Comment by dhairyagabha** [comment]
@joemasilotti Created a PR. Look forward to your thoughts.
