### ISSUE TITLE
Filter by role level

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#294]
The goal of this issue is to enable businesses to filter developers by their desired role levels.

A PR addressing this issue should:

* Add a new dropdown filter to `/developers`, "Role level"
* Add a checkbox for each possible role level
* When selected, filter out developers based on the selection

Most of this code can be modeled after other examples in `DeveloperQuery` and `DeveloperQueryComponent`.

Note that #292 must be merged in before this can be worked on.

**Comment by themudassarhassan** [comment]
@joemasilotti I think I can work on this once the parent PR gets merged which someone already mentioned to work on.

**Comment by joemasilotti** [comment]
All yours!

**Comment by joemasilotti** [comment]
Hey @themudassarhassan, this is ready to be worked on! Let me know if you're still interested in taking this.

**Comment by themudassarhassan** [comment]
Yeah the PR is on the way very soon🚀
