### ISSUE TITLE
Filter by location

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#297]
The UX of this filter is super tricky!

railsdevs currently collects (required for new users) location from developers. You are free to be as specific or general as you'd like - city, state/region, country are all possible and valid values.

Businesses have requested to filter by the following criteria:

1. ~Specific time zones~ - this is done already
2. Specific countries - some businesses has HR requirements for where they can hire
3. Specific states - some businesses health insurance is only in certain US states
4. Local - essentially a distance to a specific city

To start, we could add filtering by country. It could work the same way the timezone filter works now - show a list of unique countries, sorted alphabetically. This will probably work for a while, but when there are even 30 countries this will need a revamp.

Currently, when a business has requested filtering by state they only care about the US. This makes me thing we could get by with listing (at most) all 50 states. Not idea, but it wouldn't be _too_ terrible.

Side note, but a autocomplete/filterable list could go a long way in both of these.

Finally, locality is actually the most straightforward to solve for. Once we have geocoding autocomplete integrated, we can ask for a location and distance. The `Geocoder` gem, already integrated, will be able to filter developers based on that distance.

---

The _actual_ UX problem to solve is how to have all three of these filters live at the same time without overwhelming someone and/or creating a mess of JavaScript code?

**Comment by dhairyagabha** [comment]
@joemasilotti I think a consolidated search like this one might be a good idea. Checkboxes to facilitate the multi city search. But it could very well be a simple select dropdown.

**My two cents:**
Zipcode may not add much value as one might have to search for a big radius any way to find a developer. Might be a good idea to start with details until city and observe the response.

![railsdevs-location-filter](https://user-images.githubusercontent.com/17806296/158084763-c88ce1c2-9abf-47ff-8117-d6611498665d.png)

**Comment by joemasilotti** [comment]
After thinking about this a lot more, and getting requests from businesses, I think a simple v1 of this won't be too difficult. However, it is blocked by #356.

A PR addressing this issue should:

- [ ] Add a new filter to `/developers` on desktop and mobile labeled "Location"
- [ ] Show checkboxes for every _country_ in `Location`
- [ ] Filter developers by selected countries when applied

The logic/filters/scopes can be modeled after existing filters in `DeveloperQuery`, `DeveloeprQueryComponent` and `Developer`.

**Comment by wasabigeek** [comment]
Would love to tackle this once unblocked! I could maybe start on the backend stuff (e.g. the Query)

**Comment by joemasilotti** [comment]
Sure thing, all yours @wasabigeek! Keep in mind that if you touch the view layer you might have a nasty merge. But starting on the backed as you mentioned sounds like a great place to start.

**Comment by joemasilotti** [comment]
Closed via #468.
