### ISSUE TITLE
Clean up from PR #286

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#302]
PR #286 has two incomplete to-dos that need to be cleaned up. A PR addressing this issue should address the following:

- [ ] Remove `developers.time_zone` and `developers.utc_offset`
- [ ] Remove conditional validation for `locations.latitude` and `locations.longitude`

**Comment by kaushikhande** [comment]
@joemasilotti Can I work on this issue?

**Comment by joemasilotti** [comment]
Yes please! If you see any other unused columns feel free to open a PR to get rid of those, too. Thank you.

**Comment by kaushikhande** [comment]
@joemasilotti Added PR https://github.com/joemasilotti/railsdevs.com/pull/315. Please review.

**Comment by kaushikhande** [comment]
> Yes please! If you see any other unused columns feel free to open a PR to get rid of those, too. Thank you.

I will look into it and let you know.

**Comment by joemasilotti** [comment]
Done via #315.
