### ISSUE TITLE
Filtering `/developers` resets sorting option

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#305]
**Describe the bug**

Modifying the filter on `/developers` always resets the sort to "Newest".

**To Reproduce**

1. Go to `/developers`
2. Filter by "Availability"
3. Add a filter

**Expected behavior**

The added filter is applied and the sorting remains by "Availability".

**Action behavior**

The added filter is applied but the sorting is reset to "Newest".

**Comment by kaushikhande** [comment]
@joemasilotti Can I work on this bug.

**Comment by joemasilotti** [comment]
Sure thing! All yours.

**Comment by joemasilotti** [comment]
Let's hold off for a bit - the mobile filtering PR might fix this. I'll follow up here and let you know either way.

**Comment by joemasilotti** [comment]
PR #304 ended up fixing this.
