### ISSUE TITLE
Clean up ignored i18n keys 

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#313]
Currently, the i18n-tasks configuration, `config/i18n-tasks.yml:112`, is ignoring a bunch of keys. These keys are dynamic, so the `health` command can't pick up on them. Instead, we should be marking the dynamic keys as such where they are used.

https://github.com/glebm/i18n-tasks#dynamic-keys

A PR addressing this issue should:

1. Remove all `ignore_unused` keys from the configuration
2. Ensure `bundle exec i18n-tasks health en` still passes

**Comment by padi** [comment]
@joemasilotti looks like a good first issue to familiarize myself with the codebase.

Just tried removing ignored_unused and there's a total of 140 unused/undetected keys.

Are you fine with one big PR on this one?

**Comment by joemasilotti** [comment]
Awesome, thanks for kicking this off! One PR is fine as I _think_ it will only require a bunch of special comments in the codebase.

**Comment by joemasilotti** [comment]
Hey @padi, do you still have appetite to get this over the finish line? If not, let me know and I can pass it on to someone else or take it over myself.

**Comment by padi** [comment]
I was able to remove some of the ignored files but stopped it midway. I even upgraded to the latest version of i18n-tasks, where one of the recent addition if a new scanner might come in handy.

I can put up a PR in a few hours if you want and then continue from there. Just typing on mobile right now.

**Comment by joemasilotti** [comment]
Sure thing, that would be great! Thank you.

**Comment by padi** [comment]
@joemasilotti yes you can assign this to someone else.

**Comment by pkayokay** [comment]
I'd love to pick this up!

**Comment by joemasilotti** [comment]
Excellent - all yours!

**Comment by joemasilotti** [comment]
For now, now. If they are getting in the way of running the health check then you can remove them. I'm working on revamping translations soon.

**Comment by pkayokay** [comment]
Looks like we're not using devise's lockable feature, is it safe to assume that any translations related to that should be removed?

**Comment by pkayokay** [comment]
Other translations that we don't actually use, here's a few. I can have a PR for a more detailed review.
- `devise.registrations.edit.cancel_my_account` -> `Cancel my account`
- `devise.registrations.edit.leave_blank_if_you_don_t_want_to_change_it` -> `leave blank if you don't want to change it`
- `devise.registrations.edit.unhappy` -> `Unhappy`

**Comment by joemasilotti** [comment]
I'm not too concerned about the Devise ones. I think we should actually leave them because when we update Devise it should also update some translations (ideally).

I'm more interested in removing the smart comments sprinkled throughout the app that tell `i18n-tasks` we are using a translation. Here are two examples:

```ruby
# app/models/developers/meta.rb:32

def description
  # i18n-tasks-use t("developers.meta.description")
  i18n("description", count:)
end
```

```ruby
# app/components/developers/query_component.rb:39

def role_types
  # i18n-tasks-use t('activerecord.attributes.role_type.full_time_contract')
  # i18n-tasks-use t('activerecord.attributes.role_type.full_time_employment')
  # i18n-tasks-use t('activerecord.attributes.role_type.part_time_contract')
  RoleType::TYPES.map { |role| [role, RoleType.human_attribute_name(role)] }
end
```

**Comment by pkayokay** [comment]
I see, so the devise translations should remain in their respective `.yml` files, but should they still be added as comments?

I could see how this isn't necessary for some, they either belong in the `_flash.html.erb` partial or their respective views. I unfortunately started with the [devise translations](https://github.com/joemasilotti/railsdevs.com/pull/536/files), will revert if this isn't needed. The only thing left for the devise translations if we need this would be to still add the unused translations as comments..if that makes sense

**Comment by joemasilotti** [comment]
The overall goal of this issue is to remove all of the inline comments marking translations as used. Devise is already listed in the i18n-tasks configuration, so no adjustments to Devise translations should be needed.

**Comment by joemasilotti** [comment]
Closing this for now as the remaining tags aren't that much of an issue.

But it does beg the question if we really want translations as part of the codebase. There are so few actually translated strings that I'm beginning to wonder if `i18n-tasks` is causing more effort than it's worth.
