### ISSUE TITLE
Mark all notifications as read

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#316]
A PR addressing this issue should:

1. Add a button to the top of `/notifications` if there are any unread notifications
2. Clicking the button should mark all unread notifications as read

**Comment by gathuku** [comment]
I would like to contribute to this.  I got a client on this platform whom I have been working with for almost a month now. Thanks for making this platform.

**Comment by joemasilotti** [comment]
All yours. And that's awesome to hear! Thanks for sharing.
