### ISSUE TITLE
Told to subscribe as a developer to continue messaging.

### ISSUE THREAD

**Issue by coder2000** [joemasilotti/railsdevs.com#318]
**Describe the bug**
I am a developer messaging a potential employer and I am being asked to subscribe to continue.

**To Reproduce**
Try to send a message as a developer

**Expected behavior**
Being able to send a message

**Screenshots**
![Screenshot 2022-03-09 at 19-43-57 railsdevs](https://user-images.githubusercontent.com/27944/157570708-5ad69d82-dfbf-4872-bca1-b4306eb35d8a.png)

**Comment by joemasilotti** [comment]
Ah! That's not good. I pushed some changes for the new pricing model and it must have broke this. Thanks for the heads up, I'll get to this ASAP.

**Comment by joemasilotti** [comment]
OK, this should be fixed and live in production! Can you double check to see if it's working?

**Comment by coder2000** [comment]
As we discussed it is all good. Thanks.
