### ISSUE TITLE
Full text search (for hero and bio)

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#324]
I'm helping a lot of businesses manually narrow down their search for developers via email. And a common request is experience with specific technologies or languages. Python, React, GraphQL, web3, etc. have all been requested.

I'm currently doing this by running a text search on `developers.bio` and `developers.hero` via a `LIKE` query. Ideally, this could be built into the filters on `/developers`.

<img width="1060" alt="image" src="https://user-images.githubusercontent.com/2092156/158236151-c8236cc2-fd31-45bf-833f-b385f237f475.png">

<img width="445" alt="image" src="https://user-images.githubusercontent.com/2092156/158238225-dd25d55a-bd61-4cad-a816-7696773fa803.png">

A PR addressing this issue should:

1. Apply the design changes from PR #325 in your PR.
    * Also, swap the locations of Filter and Sort on mobile to match desktop.
3. Pass search query from view to `DeveloperQuery`.
4. Ensure that searching then applying filters doesn't lose the search term (and visa versa).
5. Add a new method to `DeveloperQuery` to query developer profiles. The query should:
    * be case-insensitive
    * search `developers.bio` and `developers.hero`
    * chain off of the existing queries in that model
6. Show the searched for query in both desktop and mobile forms.
7. Hide input fields (via `Feature.rb`) in production.

**Comment by themudassarhassan** [comment]
hey @joemasilotti I would like to work on this

**Comment by themudassarhassan** [comment]
also do you think the Like query will scale? Because I read somewhere it is not good with full text search and also not very performant

**Comment by joemasilotti** [comment]
Honestly, I'm not sure. It works fine for me in development, but I don't know if it will continue to be performant when there are thousands of developers.

If you're up for it, feel free to seed 2000 developers or something and run some tests. I've reached for `pg_search` in the past which could help clean up the queries. Maybe we will probably need an index on the two fields, too.

Database optimization is not my strength so my vote is to make it work first then optimize!

**Comment by themudassarhassan** [comment]
Yeah agree let's make this work then we can optimize queries. There is some information regarding full text search on the [docs](https://www.postgresql.org/docs/14/textsearch.html) of `PostgresSQL` that might be helpful in this regard.

**Comment by joemasilotti** [comment]
Oh, nice find!

If possible, I'd love to avoid any SQL strings. So using Arel if possible or trying out `pg_search`. Not a requirement, though.

**Comment by themudassarhassan** [comment]
Would it be cool if we first make things work and then I can do that optimization work in a separate PR?

**Comment by joemasilotti** [comment]
100%! Sorry, just getting excited :)

**Comment by themudassarhassan** [comment]
Hey @joemasilotti 
A little clarification regarding design if we swap the positions of sort and filters on mobile then the filter panel should open from left side instead of right side. Right?

**Comment by joemasilotti** [comment]
Ah, good point. Let's _not_ swap the sort/filter buttons on mobile and leave them where they are, for now.

**Comment by themudassarhassan** [comment]
sure sure.

**Comment by joemasilotti** [comment]
Closed via #341.
