### ISSUE TITLE
Button to copy hero/URL of developer profile

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#326]
When manually sending businesses a list of developers I have to copy and paste the hero and URL to my email client. Instead, I'd rather a button built into the UI that builds this for me.

A PR addressing this issue should:

1. Add a button to developer profile pages next to the Edit button. The button should:
    * Read "Copy"
    * Use the `duplicate` outline icon from [heroicons](https://heroicons.com)
2. Only show the button if the user is an admin.
3. When clicked, the button should add the following to the clipboard:
    * `<a href="<%= developer_url(@developer) %>"><%= @developer.hero %></a>`
4. When pasted into, for example, an email client, [my profile](https://railsdevs.com/developers/1) looks like this:
    * [The Turbo Native guy](https://railsdevs.com/developers/1)

**Comment by gathuku** [comment]
I will pick this.

**Comment by joemasilotti** [comment]
All yours!
