### ISSUE TITLE
Submit message form with CMD-Enter

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#328]
When messaging it would be nice to submit the form with a keyboard shortcut.

A PR addressing this issue should:

1. Add a Stimulus controller to submit a form via a keyboard shortcut
2. Set the shortcut to <kbd>CMD</kbd> + <kbd>Enter</kbd> on macOS and the equivalent on Windows and Unix
3. Ensure that pressing Enter alone does _not_ submit the form
4. Ensure the form still works as expected on mobile

**Comment by jasonplatts** [comment]
I would be happy to work on this one.

**Comment by joemasilotti** [comment]
All yours, thanks!

**Comment by joemasilotti** [comment]
Closed via #335.
