### ISSUE TITLE
Location in detail page shows html text along with offset.

### ISSUE THREAD

**Issue by kaushikhande** [joemasilotti/railsdevs.com#331]
**Describe the bug**
On the developer details page, the location is showing extra HTML content in the offset field

**To Reproduce**
1. Go to developer details page
2. see location

**Screenshots**
![Screenshot from 2022-03-17 11-07-37](https://user-images.githubusercontent.com/28509627/158744207-28f0fedf-98e6-45fd-addf-e37894fe1432.png)

**Additional context**

**Comment by joemasilotti** [comment]
Thanks for reporting, @kaushikhande! This was occurring in dev because of the newly enabled `annotate_rendered_view_with_filenames` configuration. I pushed a fix to render the nested View Component in the HTML and not the .erb file and all seems to be working again.
