### ISSUE TITLE
Mobile view of `/notifications` CSS tweaks

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#332]
**Describe the bug**

The mobile view of `/notifications` is weird looking.

**To Reproduce**

1. Seed your database (or create a notification)
2. Visit `/notifications` on mobile

**Expected behavior**

* "New notifications" and the button should have horizontal padding on mobile, but not add to the desktop padding.
* Each notification should not have rounded borders on mobile (desktop design should not change).
* Stretch: There should be no space between notifications on mobile (desktop design should not change). 

**Screenshots**

<img width="505" alt="image" src="https://user-images.githubusercontent.com/2092156/158840047-ba7b4e1a-4728-4ea8-82d9-20f5f6a01ebf.png">

**Comment by dhairyagabha** [comment]
@joemasilotti I would like to take this one

**Comment by joemasilotti** [comment]
Awesome – all yours!
