### ISSUE TITLE
Add affordance for new keyboard shortcut

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#344]
I want to make it more obvious you can submit the Message form with a keyboard shortcut. Ideally, something like this could work (but with matching color, font weight, etc.).

![image](https://user-images.githubusercontent.com/2092156/159542770-37564637-9e6b-4cf6-b298-1c0b59b0f144.png)

The one tricky part is making sure it uses the Windows equivalent on Windows machines. And same for Linux! I'm open to ideas.

**Comment by aiethics95** [comment]
Hi, I think it would look a bit better if the "Send" button is changed to look like a keyboard key. Style wise this will make sense and look pretty (: Let me know if this is something you are okay with?

**Comment by aiethics95** [comment]
Also, an easy way to replicate the same CSS for this new button is to inspect the "Send" button and copy its properties and add them to the new button and they will look the same.

**Comment by joemasilotti** [comment]
Agreed! This was just a mockup I did in Preview.app to show where I think the affordance should go.

It won't be a new button, so shouldn't be styled like one. But gray, semibold or medium weight text.
