### ISSUE TITLE
100% remote option

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#346]
Developers have requested a way to share that they are only looking for fully remote roles. A toggle/checkbox in the developer form could be a good way to collect this.

Then, adding a toggle in the filters.

Finally, letting the business know before reaching out that the developer is only interested in remote roles. (Perhaps in `ColdMessagesController#new`.)

**Comment by kaushikhande** [comment]
Can I take this one?

**Comment by joemasilotti** [comment]
Thank for the offer, @kaushikhande! At this point I'm not 100% sure how this will work or where the buttons/filters will go. If you're up for it, feel free to submit a PR. But I might go back and forth on the UX a few times before it is accepted.

**Comment by dqnamo** [comment]
Taking a look at this 🙌🏽

**Comment by joemasilotti** [comment]
Closing this for now as I'm not sure it's worth the complexity of a new form field.
