### ISSUE TITLE
Index `developers.hero` and `developers.bio` for search performance

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#347]
Context: https://github.com/joemasilotti/railsdevs.com/pull/341#discussion_r833542319

**Comment by themudassarhassan** [comment]
I'll take it and will add more details regarding the approach of the implementation.

**Comment by joemasilotti** [comment]
All yours! Thanks.

**Comment by joemasilotti** [comment]
Hey @themudassarhassan, I'd love to get this working before we go live with the search box for everyone. Do you have any updates on this?

**Comment by themudassarhassan** [comment]
Hey @joemasilotti, unfortunately, I don't have an update right now as I have been occupied with other things lately 😞 But I'm planning to start working on this very soon, probably this week.

**Comment by joemasilotti** [comment]
Sounds great - thank you! If something changes and you no longer have the appetite let me know and I can pass it off to someone else.

**Comment by themudassarhassan** [comment]
Hey @joemasilotti I have created the [PR](https://github.com/joemasilotti/railsdevs.com/pull/379). Please review whenever possible. Thanks.

**Comment by joemasilotti** [comment]
Closed via #379.
