### ISSUE TITLE
Replace id in url with a slug of some kind

### ISSUE THREAD

**Issue by arni1981** [joemasilotti/railsdevs.com#350]
Currently the id is shown in the url for developers, notifications and conversations (maybe more, I haven't checked all).
I think it would improve things to see a slug of some sort instead of the id, both because the id doesn't have any meaning really, but more importantly I don't think it is a good strategy to show how many conversations and developers there are in the system already.

I would be willing to work on this feature if needed.

**Comment by joemasilotti** [comment]
> I don't think it is a good strategy to show how many conversations and developers there are in the system already.

Honest question: why not? I already mention on `/developers` how many developers are on the site.

**Comment by joemasilotti** [comment]
@arni1981, I'm going to close this since it's been almost 3 weeks since I've heard back. Feel free to reopen it if you'd like to continue the discussion!
