### ISSUE TITLE
Read indicator for messages

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#351]
Folks have been reaching out to know if their messages were read by the recipient. A PR addressing this issue should:

1. Add an indicator to the most recent sent message in the conversation screen based on if the associated notification was read.

I'm open to design ideas on this one, but to start it could be something as simple as a checkmark that when hovered says "Read at #{timestamp}".

**Comment by themudassarhassan** [comment]
@joemasilotti  Can I work on this?

**Comment by joemasilotti** [comment]
Sure thing - all yours!

One more request - wrap the UI in a feature flag, please.

**Comment by joemasilotti** [comment]
Hey @themudassarhassan, do you have any updates on this? Let me know if you still have appetite! No worries if not, I can pass it off to someone else.

**Comment by themudassarhassan** [comment]
Hey @joemasilotti. I do want to work on this but it may get delayed by one more week. I'll try to grab some time to work on this during this week, but if this is important you can surely assign it to someone else. Thanks!

**Comment by joemasilotti** [comment]
All good - this isn't a super high priority task so another week is fine. Thanks for the update!

That said, I will want to pass this off to someone else if you don't get to it by then. Just to keep it fair to other contributors.

**Comment by themudassarhassan** [comment]
Hey, @joemasilotti You can assign this task to someone else, I have been very busy lately. Sorry for the blockage :(

**Comment by joemasilotti** [comment]
All good! Thanks for the heads up.

**Comment by troyizzle** [comment]
I'd like to work on this @joemasilotti !

**Comment by joemasilotti** [comment]
Awesome - all yours!

**Comment by joemasilotti** [comment]
Closed via #485.
