### ISSUE TITLE
Welcome emails

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#354]
I'm finally at the point where I'd like to automate a welcome email to new developers and businesses to the site. To start, I'd love to keep these as unstyled HTML and very short.

A PR addressing this issue will:

- [ ] Add an `after_create_commit` callback to both `Developer` and `Business` that sends an email
    * Subject: Welcome to railsdevs!
    * Body: (see below)
    * From: Joe Masilotti joe@masilotti.com (formatted correctly)
- [ ] Ensure the HTML and plain text versions work when previewing
- [ ] Add a test for each that ensures the email is enqueued correctly
- [ ] **BONUS**: Implement [`name_of_person`](https://github.com/basecamp/name_of_person) to use the developer/business's first name

---

### Developer welcome email

Hey #{developer.name},

I'm Joe, the founder of [railsdevs](https://railsdevs.com). I saw that you added your developer profile and wanted to reach out.

What does your ideal next role look like?

### Business welcome email

Hey #{business.name},

I'm Joe, the founder of [railsdevs](https://railsdevs.com). I saw that you added your business profile and wanted to reach out. If there's anything I can do to make your search easier let me know.

What are you looking for in a Rails developer?

**Comment by salochara** [comment]
Hey there! 👋  
I'd be happy to work on this one!

**Comment by joemasilotti** [comment]
All yours @salochara! Thanks for taking this on 💪

**Comment by joemasilotti** [comment]
Hey @salochara, do you have any updates on this? It's been over a week so I wanted to check in. Let me know if you still have appetite to get this over the finish line!

**Comment by tim-carey-code** [comment]
I would like to help out with this one!

**Comment by salochara** [comment]
Hey 👋 
I haven't had a lot of progress on this one.. I've had some setbacks and haven't had much time. 
@tim-carey-code go ahead with this one!

I'll grab another issue once I get a bit more of time.

**Comment by joemasilotti** [comment]
Thanks @salochara. @tim-carey-code, all yours!
