### ISSUE TITLE
Show warning when part-time plan reaches out to full-time only developer

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#358]
Businesses that have signed up for the $99/month part-time plan are not allowed to hire full-time developers.

When reaching out to a developer, if the business is on the part-time plan and the developer is not looking for part-time contract roles...

- [ ] Show a warning/info message and disable the form on the cold message page and conversation page 
- [ ] Enforce logic in `MessagingPolicy`

**Comment by joemasilotti** [comment]
All yours!

**Comment by GALTdea** [comment]
got the logic working from the cold_messages_controller but I can't get it to work on the MessagingPolicy. going over the pundit docs to see how to access the developer record since the record variable it's an empty message object. not experienced on pundit.

**Comment by joemasilotti** [comment]
Exciting! Take a look at the other policy classes - there should be an example that shows what you need to get close.

**Comment by joemasilotti** [comment]
Closed via #380.
