### ISSUE TITLE
Add link to "full-time form part-time plan" warning to upgrade account

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#359]
Businesses that have signed up for the $99/month part-time plan are not allowed to hire full-time developers.

When reaching out to a developer, if the business is on the part-time plan and the developer is _not_ looking for part-time contract roles...

- [ ] Add link to Stripe Billing to upgrade account in warning/info message

**Comment by GALTdea** [comment]
I'll try and give this one a shot over the weekend if I have a couple of hours. If not I'll work on it on monday.

**Comment by joemasilotti** [comment]
Awesome! I forgot to mention, but this is dependent on #358.

**Comment by GALTdea** [comment]
I see.  Stop them from completing the transaction(outside of their limited account)  and redirect them to the upgrade page instead. seems like a single issue to me!

**Comment by GALTdea** [comment]
Yes, I'll take a pass at 358. thank you

**Comment by joemasilotti** [comment]
Closed via #380.
