### ISSUE TITLE
Add checkbox acknowledging 10% fee to cold message form

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#360]
Businesses that have signed up for the $299/month full-time plan are required to pay a 10% salary fee when they hire someone they contacted via railsdevs.

- [ ] On the cold message screen add a checkbox to the form stating "I understand that if I hire #{developer's name} then I will pay railsdevs 10% of their first year salary."
- [ ] Invalidate the form if the checkbox is not checked
- [ ] **BONUS**: Disable the form if JavaScript is enabled and the checkbox is not checked

**Comment by kaushikhande** [comment]
@joemasilotti Can I work on this issue?

**Comment by joemasilotti** [comment]
Sure thing! All yours.

**Comment by kaushikhande** [comment]
Started working on this.

**Comment by joemasilotti** [comment]
Closed via #371.
