### ISSUE TITLE
Add 10% fee payment button to conversation

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#361]
Businesses that have signed up for the $299/month full-time plan are required to pay a 10% salary fee when they hire someone they contacted via railsdevs.

- [ ] Add a button on the conversation page below the form titled "Pay 10% hiring fee" with a label of "I hired #{developer's name}." that links to `mailto:joe@masilotti.com?subject=railsdevs hiring fee&body=I hired #{developer's name} and am ready to pay the 10% fee. Their first year salary is: `

**Comment by sriddbs** [comment]
@joemasilotti I would like to take this up, please assign it to me

**Comment by joemasilotti** [comment]
All yours! Thank you.

**Comment by joemasilotti** [comment]
Hey @sriddbs, I was wondering if you've made progress on this issue as it's been over a week. If you still have the appetite to complete it let me know. Otherwise I can take it over - no worries either way!

**Comment by joemasilotti** [comment]
Closed via #380.
