### ISSUE TITLE
Add "Invisiblize" button on developer profiles (for admins)

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#367]
I've had a few folks add their developer profile but fill in bogus data. "abc" as their entire bio or even "Loading...". My process is to email them and tell them I've hidden their profile then manually fire up the Rails console and set their search status to "invisible". I'd like to automate this process.

A PR addressing this issue should:
- [ ] Add a button next to the "Hire me" one (similar to #337) that says "Invisiblize"
    - [ ] Only show this button to admins
    - [ ] Use the `eye-off` icon from [Heroicons](https://heroicons.com)
- [ ] When clicked, update the `search_status` field to `:invisible` for the developer being viewed
- [ ] Send that developer an email with the below content and subject "Your profile on railsdevs was flagged"
    - [ ] Link "railsdevs" to `https://railsdevs.com`
    - [ ] Link "Your developer profile" to their profile page

Hey #{developer.name},

I'm Joe, the founder of railsdevs. Your developer profile was flagged because it doesn't contain enough information and kind of looks like spam.

I've set your profile to invisible. No one but yourself will be able to see it. You can toggle this back when you flesh out your profile a bit more.

Thanks,
Joe

**Comment by DRBragg** [comment]
Hey Joe, I'm down to take this on.

**Comment by joemasilotti** [comment]
Awesome! All yours.
