### ISSUE TITLE
Show what job type developers are looking for during messaging

### ISSUE THREAD

**Issue by barefootford** [joemasilotti/railsdevs.com#382]
I'm currently looking for part-time roles, but every message I've been sent is for full-times. We probably can't totally fix this, but I think companies should see a banner or something during messaging. Not sure if this is already there.

I spent hours on this design and it should look exactly this way. kidding:

<img width="752" alt="Screen Shot 2022-04-19 at 12 36 02 PM" src="https://user-images.githubusercontent.com/3782822/164082271-cc6b45a6-65e1-48d9-9e05-6c2c49827c6c.png">

**Comment by joemasilotti** [comment]
> but every message I've been sent is for full-times

First off, that stinks. I'm sorry about that!

I love your idea of adding some sort of affordance to the top of the conversation. I'm thinking of adding this to the initial outreach screen for businesses. What do you think of this?

<img width="741" alt="image" src="https://user-images.githubusercontent.com/2092156/164500699-6146a6ed-b2d2-410f-a403-5350d2b0c81e.png">

**Comment by barefootford** [comment]
Looks great to me :shipit: 

Separately but related to that page - it would be nice to have just 'part time employment' as an option too. ie https://4dayweek.io That's more what I'm looking four, rather than part-time contracting.

**Comment by joemasilotti** [comment]
Awesome, thanks!

> it would be nice to have just 'part time employment' as an option too

Hmm, in my opinion that would be full-time employment but the hours aren't a traditional 40 hour work week. I'm worried about adding a new option there, to be honest. I was actually thinking of merging part-time contract and full-time contract! I'll keep you posted.

**Comment by joemasilotti** [comment]
Closed via #383.
