### ISSUE TITLE
Misaligned form field (tiny fix)

### ISSUE THREAD

**Issue by MichaelArriaga** [joemasilotti/railsdevs.com#389]
**Describe the bug**
Not significant enough to warrant a pr. There is a misaligned form field in `app/views/developers/_form.html.erb` 

**To Reproduce**
1. sign_in as example user: `developer@example.com`
1. click `edit` button
1. view form fields for `city` `state` `country`
1. notice the fields are misaligned

**Expected behavior**
Fields should be aligned

**Screenshots**
![rails-devs-alignment](https://user-images.githubusercontent.com/6802326/165860622-58709a57-92c7-4988-8048-7c598ac5ed8b.png)

**Additional context**
please refer to https://github.com/MichaelArriaga/railsdevs.com/commit/14fcff3828aadaaef7f39d554b6c5787f3b9afcb for the change.

**Comment by joemasilotti** [comment]
Thanks for the report! Would you mind creating the PR? It should be a click or two for you. Then I don't have to manually edit the file – plus you get contributor perks (when they launch)!

**Comment by MichaelArriaga** [comment]
Absolutely, will do.
