### ISSUE TITLE
Revamp business profiles

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#391]
Business profiles, [like mine for example](https://railsdevs.com/businesses/1), are pretty bare bones. They list the company name, the person associated, a sentence or two, and a photo.

Even though these profiles aren't publicly linked to, they can be accessed when a developer receives a message. So I'd like to add a bit more info to make it easier for the business to share details about their company and contact.

As a first pass, I'd love to see the following fields added:

* Bio - along with hero, a bit more info about the company
* URL - where can I find more information about the company?
* Contact role - what does the person do at the company?

There's a big design decision to make before adding these fields. I don't want the business profile to look just like the developer one. But I also don't want to design an entirely new screen.

I'm open to ideas!

**Comment by joemasilotti** [comment]
After thinking on this a bit more I think we can get a v1 of this out without much more design requirements.

A PR addressing this issue should:

- [ ] Add a website field to the business form and public view
- [ ] Add a role field to the business form and public view

We will not be addressing bio at this time. If you are unsure of where/how to put the fields then toss them at the bottom and submit a PR. I can take over for the design!

**Comment by scottharvey** [comment]
First pass PR here: https://github.com/joemasilotti/railsdevs.com/pull/397

**Comment by joemasilotti** [comment]
Awesome - all yours! I'll comment on the PR.

**Comment by joemasilotti** [comment]
Closed, for now, via #397.
