### ISSUE TITLE
Add confirmation dialog to Invisibilize admin button

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#392]
When clicking the Invisibize admin button the developer is marked as invisible and an email is sent right away. I'd like one step of security in case I fat finger a click.

A PR addressing this issue should:

- [ ] Add a confirmation alert to the Invisibilize admin button

The alert should prompt `Mark this developer as invisible and notify them via email?` and be done via Turbo and not require additional JavaScript.

**Comment by scottharvey** [comment]
@joemasilotti Are you happy to just use the standard Turbo confirmation or do you want a nicer confirmation message in a custom modal?

![confirmation](https://user-images.githubusercontent.com/78157/166128478-24f5fec4-8a7c-42bf-a42b-eb230d27ef79.gif)

**Comment by joemasilotti** [comment]
Standard Turbo confirmation is just fine for this issue!

**Comment by joemasilotti** [comment]
Closed via #396.
