### ISSUE TITLE
Notify admin if developer changes status to indicate being hired

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#393]
This is the first check in trying to track when a developer gets hired via the platform.

A PR addressing this issue should:

- [ ] Send a new admin email/notification when a developer's status changes to indicate they may have been hired

Any of the following changes should trigger the notification:

* A developer's search status changes from actively looking or open to not interested or invisible
* An admin marking a developer as invisible (via the Invisibilize button) should _not_ trigger the notification
* A developer removing full-time employment from their selected role types

**Comment by benngarcia** [comment]
happy to jump in on this

**Comment by joemasilotti** [comment]
Sure thing, all yours @benngarcia!

**Comment by joemasilotti** [comment]
Closed via #401.
