### ISSUE TITLE
Migrate Pundit to Action Policy to pass message and redirect URL on authorization failure

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#395]
Pundit, the authorization gem, doesn't support passing "context" when raising an error. [Action Policy](https://actionpolicy.evilmartians.io/#/) does. I want to pass context to display a custom error message and redirect based on what kind of authorization failed.

## A PR addressing this issue should:

- [ ] Follow the [migration guide](https://actionpolicy.evilmartians.io/#/./pundit_migration)
- [ ] Abstract adding error message and redirect path to `ApplicationPolicy`
- [ ] Implement `ColdMessagePolicy` to handle the different failure paths (see the `before_action`s in `ColdMessageController`)

I'm open to lots of discussion on this one as I'n not 100% sure Action Policy is the right move. So feel free to submit a draft PR to kick off a conversation!

**Comment by djdarkbeat** [comment]
We're thinking about migrating to action policy at work from petergate (https://github.com/elorest/petergate) Petergate is being used in two repos, but we have i18n issues to support and there's the whole passing context thing to consider also. I have to admit being curious about this but I also know I can't commit to look at it until after RailsConf.

**Comment by joemasilotti** [comment]
I doubt I'll get around to it before then, either. But glad to know other folks are thinking along the same lines as me!

**Comment by joemasilotti** [comment]
Closed via #447. I'll probably come back to this, but shoving error messages and redirection URLs in the policy layer feels weird right now.
