### ISSUE TITLE
Index site on Google via a sitemap generator

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#40]
I've used [this fork of sitemap_generator](https://github.com/kjvarga/sitemap_generator) in the past, but am open to newer/better tools!

I'll then set up Google Search Console.

**Comment by vamsipavanmahesh** [comment]
A couple of questions:

- Do you want individual developer profiles to be part of the sitemap?
If that's the case, we might want to run a cron job to regenerate this sitemap every day via a cron job

- Do you envision at some time in the future that we will move to multiple servers, if that's the case we cannot have a sitemap file in a single server or multiple servers, need to be in s3 or equivalent and a route will point to that file

But the second point need not be done right now! we can do it when the time comes

**Comment by davegudge** [comment]
Using a [dynamically generated sitemap](https://webdevchallenges.com/how-to-add-a-dynamically-generated-sitemap-with-rails) would remove the need for regenerating and it should work regardless of how the site is hosted.

**Comment by vamsipavanmahesh** [comment]
For a small site it should be fine, but when you have thousands of records, might not be a good solution?

A lot of this will obviously depend on what is the time crawler is willing to time just to get the sitemap?

After getting the sitemap, it has to actually crawl

When I have worked on an SEO project at my company, SEO consultants used to talk about a thing called "crawl budget", basically our question was why only 40 k things were indexed, whereas 100 k URLs. So they used to be talk about how google only gives a budget for each site etc

But overall I would vote for not doing it dynamically assuming that thousands of people are going to come in

**Comment by davegudge** [comment]
You've raised some very good points. 

SEO is such a large topic these days!

**Comment by joemasilotti** [comment]
I've used the fork I linked to at the top for a variety of projects. You set up a single Ruby file that looks a lot like a Rails routing file. You can dynamically index pages pages on path, or resource. It also sets up a single rake task that will publish the sitemap on an S3 bucket and ping Google (and other search engines).

That still feels like the easiest approach for setting up a sitemap on a Rails project. But I'm still open to other ideas or implementations. I want to stay away from manually generating and splitting XML files and am fine bringing in a gem for this.

### What to index?

* the homepage
* `/developers`
* `/about`
* every developer profile
* sign in, sign up, reset password, and resend confirmation instruction pages

**Comment by vamsipavanmahesh** [comment]
Yes, I was talking about using the mentioned gem

> every developer profile

this is where the complexity lies in, example there are 100 developers right now and our URLs are like this

/developers/1
/developers/2 etc

all these URLs will go to sitemap, now tomorrow 100 more devs sign up, and you need to put those URLs also on the sitemap

sitemaps do not allow dynamic routes as far as I know like rails routes

so in order to put those new URLs, you need to regenerate the sitemap and for that a cron job is needed

I can point to some files if needed, please let me know :)

**Comment by joemasilotti** [comment]
Yep, exactly! A job that regenerated the site map once a day should work great. I can set that up on Heroku once the rake task exists.

**Comment by vamsipavanmahesh** [comment]
I can pick this up if this is not urgent, can get done by this week

**Comment by joemasilotti** [comment]
Awesome, thank you!

**Comment by joemasilotti** [comment]
A heads up that I will happily review a PR but won't merge anything until #94 is merged in.

**Comment by joemasilotti** [comment]
#94 is merged and live, so this is ready to be worked on again!

**Comment by caseyjenks** [comment]
@vamsipavanmahesh How is your availability looking? I can pick up if need be

**Comment by vamsipavanmahesh** [comment]
Hi Casey,

My machine is broken right now. Unfortunately I cannot pick this, you can
go ahead with this :)

**Comment by joemasilotti** [comment]
Closed via #183.
