### ISSUE TITLE
Refactor non-reusable View Components under model named module

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#417]
A PR addressing this issue should:

- [ ] Move non-reusable (model-specific) View Components under their own module/namespace

PR #418 shows an example of refactoring `AvailabilityComponent` into `Developers::AvailabilityComponent` because we can't use that component without a developer.

Components that need to be refactored:

- [x] `BusinessAdminComponent` -> `Businesses::SubscriptionsComponent`
- [x] `BusinessOpenGraphComponent` -> `Businesses:OpenGraphComponent`
- [x] `ColdMessageRoleTypeComponent` -> `RoleType::ColdMessageComponent`
- [x] `DeveloperAdminComponent` -> `Developers::AdminComponent`
- [x] `DeveloperCardComponent` -> `Developers::CardComponent`
- [x] `DeveloperOpenGraphComponent` -> `Developers::OpenGraphComponent`
- [x] `DeveloperPrimaryActionComponent` -> `Developers::PrimaryActionComponent`
- [x] `DeveloperQueryComponent` -> `Developers::QueryComponent`
- [ ] `ExpiredSubscriptionComponent` -> `Businesses::ExpiredSubscriptionComponent`
- [ ] `HiringFeeComponent` -> `Conversations::HiringFeeComponent`
- [x] `LegacyBusinessSubscriptionComponent` -> `Businesses::LegacySubscriptionComponent`
- [ ] `LocationComponent` -> `Locations::Component`
- [x] `NewDeveloperFieldComponent` -> `Developers::NewFieldComponent`
- [x] `NewDeveloperFieldsComponent` -> `Developers::NewFieldsComponent`
- [ ] `PaywalledComponent` -> `User::PaywalledComponent`
- [x] `RoleLevelComponent` -> `RoleLevel::Component`
- [x] `RoleTypeComponent` -> `RoleTypes::Component`
- [x] `SearchStatusComponent` -> `Developers::SearchStatusComponent`
- [ ] `TimeZoneComponent` -> `Locations::TimeZoneComponent`
- [x] `UpgradeAccountComponent` -> `Businesses::UpgradeAccountComponent`
- [ ] `UTCOffsetComponent` -> `UTCOffsets::Component`

Feel free to submit a PR for some of these if you don't want to knock out all of them at once!

**Comment by metamoni** [comment]
I can work on these

**Comment by joemasilotti** [comment]
You're making great progress, @metamoni! Just a few more to go.

**Comment by metamoni** [comment]
@joemasilotti I see a few more in the main folder that haven't been mentioned here. Should I refactor these too?

`BusinessPrimaryActionComponent` > `Businesses::PrimaryActionComponent`
`DeveloperProfileActionComponent> `Developers::ProfileActionComponent`
`DeveloperQuerySortButtonComponent` > `Developers::QuerySortButtonComponent`

**Comment by joemasilotti** [comment]
That would be great, yes please!

**Comment by metamoni** [comment]
Happy to do these too, @joemasilotti

**Comment by joemasilotti** [comment]
Amazing – thank you again!
