### ISSUE TITLE
Add admin search

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#419]
I often find myself trying to find a developer or business in an admin context.

## A PR addressing this issue should: 

- [ ] Create a new page, `/admin/developers`
    - [ ] List all developers, paginated, in reverse `created_at` order
    - [ ] Display their name, only, in a table like `/admin/conversations`
    - [ ] Add a search field to filter developers by name and email address
- [ ] Create a new page, `/admin/businesses`
    - [ ] List all businesses, paginated, in reverse `created_at` order
    - [ ] Display their company and contact name, only, in a table like `/admin/conversations`
    - [ ] Add a search field to filter businesses by contact name, company, and email address

Search should be partial matching like we are already doing for `Developer` with `pg_search_scope`.

## Stretch goals (not need for this PR and could be in a follow up one):

- [ ] Add stats to `/admin/developers`
    - [ ] Number of developers
    - [ ] Number of actively looking + open developers
- [ ] Add stats to `/admin/businesses`
    - [ ] Number of businesses
    - [ ] Number of actively subscribed businesses

**Comment by esmale** [comment]
Question regarding the data displayed vs the search criteria:
Developers
 * Search: name & email
 * Display: name

Businesses
 * Search: Contact Name, Company, Email address
 * Display: Company & Contact Name

Primary Question: It feels strange to have the search and display criteria not in sync with each other.  If you execute a search that matches a developer's email address, but that email address isn't displayed, you can't immediately see on the search results page what matched against your query.  So I want to verify that you don't want to see the developer email address in the table?

Secondary Question: I'm not seeing an email address field on the Business model itself.  Is the email address mentioned supposed to be the address of the User to which the Business record belongs?  (And if so, the same question as above also applies: if we're searching against it, should it also be displayed on the /admin/businesses page?)

**Comment by joemasilotti** [comment]
> Primary Question: It feels strange to have the search and display criteria not in sync with each other. If you execute a search that matches a developer's email address, but that email address isn't displayed, you can't immediately see on the search results page what matched against your query. So I want to verify that you don't want to see the developer email address in the table?

Great point. Let's add email address to the table as well.

> Secondary Question: I'm not seeing an email address field on the Business model itself. Is the email address mentioned supposed to be the address of the User to which the Business record belongs? (And if so, the same question as above also applies: if we're searching against it, should it also be displayed on the /admin/businesses page?)

Ah, both should be using `users.email`. `developers.email` is no longer being used and should actually [be removed](https://github.com/joemasilotti/railsdevs.com/issues/428).

**Comment by joemasilotti** [comment]
Closed in favor of #601 (for now).
