### ISSUE TITLE
`bin/setup` failed on fresh install

### ISSUE THREAD

**Issue by malachaifrazier** [joemasilotti/railsdevs.com#426]
**Describe the bug**
`bin/setup` failed on a fresh repo install.

**To Reproduce**
1. Git clone `git@github.com:joemasilotti/railsdevs.com.git`.
2. Run `brew bundle install --no-upgrade` and wait for it to finish.
3. Run `bin/setup`
4. See error. [Full Console output Gist here](https://gist.github.com/malachaifrazier/3de2b9e94f9faa4a8526ef247e256d26)

**Expected behavior**
The installation script should automatically get the application setup.

**Screenshots**

**Additional context**
On MacOS Monterey MacBook Pro (13-inch, 2020) 12.3.1

**Comment by joemasilotti** [comment]
What version of PostgreSQL are you using?

```bash
$ psql --version
```

**Comment by malachaifrazier** [comment]
I'm at `psql (PostgreSQL) 14.3`

**Comment by joemasilotti** [comment]
@themudassarhassan, any ideas what could be going on here? The error is coming from the the search index on developers.

[`db/migrate/20220416144523_add_index_for_searchable_fields_in_developers.rb`](https://github.com/joemasilotti/railsdevs.com/blob/main/db/migrate/20220416144523_add_index_for_searchable_fields_in_developers.rb)

**Comment by themudassarhassan** [comment]
@joemasilotti let me have a look.

**Comment by themudassarhassan** [comment]
Okay. So I was able to do a fresh setup and the database was created successfully and migrations ran successfully. I'm not sure what is the exact root cause of this issue. But @malachaifrazier can you try to create db with `bin/rails db:create` and then run migrations afterward to see if this helps.

**Comment by malachaifrazier** [comment]
Will do!

**Comment by malachaifrazier** [comment]
Here's a screenshare of what i'm seeing now;


![`bin/setup` failed on fresh install · Issue #426 · joemasilotti/railsdevs.com - 19 May 2022 - Watch Video](https://cdn.loom.com/sessions/thumbnails/f918e4eec01a4feabf695df58ef8c009-with-play.gif)

**Comment by malachaifrazier** [comment]
Running `bin/setup` twice gives me this error:

```
== Installing dependencies ==
The Gemfile's dependencies are satisfied

== Install JavaScript dependencies ==
yarn install v1.22.17
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.14s.

== Preparing database ==
== 20211022220447 CreateDevelopers: migrating =================================
-- create_table(:developers)
   -> 0.0060s
== 20211022220447 CreateDevelopers: migrated (0.0061s) ========================

== 20211028230858 CreateActiveStorageTables: migrating ========================
-- create_table(:active_storage_blobs, {:id=>:primary_key})
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::DuplicateTable: ERROR:  relation "active_storage_blobs" already exists
/Users/malachai/Desktop/Projects/railsdevs.com/db/migrate/20211028230858_create_active_storage_tables.active_storage.rb:7:in `change'

Caused by:
ActiveRecord::StatementInvalid: PG::DuplicateTable: ERROR:  relation "active_storage_blobs" already exists
/Users/malachai/Desktop/Projects/railsdevs.com/db/migrate/20211028230858_create_active_storage_tables.active_storage.rb:7:in `change'

Caused by:
PG::DuplicateTable: ERROR:  relation "active_storage_blobs" already exists
/Users/malachai/Desktop/Projects/railsdevs.com/db/migrate/20211028230858_create_active_storage_tables.active_storage.rb:7:in `change'
Tasks: TOP => db:prepare
(See full trace by running task with --trace)

== Command ["bin/rails db:prepare"] failed ==
```

**Comment by malachaifrazier** [comment]
I ended up manually going through a bunch of the migration files and adding `if_not_exists: true` [see in this gist of git diff](https://gist.github.com/malachaifrazier/f5f03f6e8faf34e4485080e7805db2ec).


I then ran `bin/setup` again and reached this error once more:

```
➜  railsdevs.com git:(main) ✗ bin/setup                 
== Installing dependencies ==
The Gemfile's dependencies are satisfied

== Install JavaScript dependencies ==
yarn install v1.22.17
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.17s.

== Preparing database ==
== 20220416144523 AddIndexForSearchableFieldsInDevelopers: migrating ==========
-- execute("      ALTER TABLE developers\n        ADD COLUMN textsearchable_index_col tsvector\n          GENERATED ALWAYS AS (to_tsvector('simple', coalesce(hero, '') || ' ' || coalesce(bio, ''))) STORED;\n")
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::SyntaxError: ERROR:  syntax error at or near "("
LINE 3:           GENERATED ALWAYS AS (to_tsvector('simple', coalesc...
                                      ^
/Users/malachai/Desktop/Projects/railsdevs.com/db/migrate/20220416144523_add_index_for_searchable_fields_in_developers.rb:3:in `up'

Caused by:
ActiveRecord::StatementInvalid: PG::SyntaxError: ERROR:  syntax error at or near "("
LINE 3:           GENERATED ALWAYS AS (to_tsvector('simple', coalesc...
                                      ^
/Users/malachai/Desktop/Projects/railsdevs.com/db/migrate/20220416144523_add_index_for_searchable_fields_in_developers.rb:3:in `up'

Caused by:
PG::SyntaxError: ERROR:  syntax error at or near "("
LINE 3:           GENERATED ALWAYS AS (to_tsvector('simple', coalesc...
                                      ^
/Users/malachai/Desktop/Projects/railsdevs.com/db/migrate/20220416144523_add_index_for_searchable_fields_in_developers.rb:3:in `up'
Tasks: TOP => db:prepare
(See full trace by running task with --trace)

== Command ["bin/rails db:prepare"] failed ==
```

**Comment by joemasilotti** [comment]
That _looks_ like your version of Postgres doesn't support that syntax, but you're running a version higher than me. (I'm on 14.2.) So I'm really not sure what's going on here!

Maybe a red herring, but I just reran the migrations and the following diff was made to my schema. I wonder if this is related?

```diff
diff --git a/db/schema.rb b/db/schema.rb
index c42ca61..72ba1a0 100644
--- a/db/schema.rb
+++ b/db/schema.rb
@@ -12,6 +12,7 @@

 ActiveRecord::Schema[7.0].define(version: 2022_05_01_021745) do
   # These are extensions that must be enabled in order to support this database
+  enable_extension "pg_stat_statements"
   enable_extension "plpgsql"

   create_table "active_storage_attachments", force: :cascade do |t|
@@ -227,7 +228,7 @@ ActiveRecord::Schema[7.0].define(version: 2022_05_01_021745) do
     t.string "processor_id"
     t.boolean "default"
     t.jsonb "data"
-    t.datetime "deleted_at"
+    t.datetime "deleted_at", precision: nil
     t.datetime "created_at", null: false
     t.datetime "updated_at", null: false
     t.index ["owner_type", "owner_id", "deleted_at", "default"], name: "pay_customer_owner_index"
@@ -264,8 +265,8 @@ ActiveRecord::Schema[7.0].define(version: 2022_05_01_021745) do
     t.string "processor_plan", null: false
     t.integer "quantity", default: 1, null: false
     t.string "status", null: false
-    t.datetime "trial_ends_at"
-    t.datetime "ends_at"
+    t.datetime "trial_ends_at", precision: nil
+    t.datetime "ends_at", precision: nil
     t.decimal "application_fee_percent", precision: 8, scale: 2
     t.jsonb "metadata"
     t.jsonb "data"
```

**Comment by malachaifrazier** [comment]
Ha! Found it 😄 

Found it! 
The root cause was because that syntax isn't supported by my old PostgreSQL version (installed via `Homebrew`). 

Upgrading like so fixed all the things:

Installed PostgreSQL via `Homebrew`?

Check your PostgreSQL version like so:
```
psql [username with correct permissions]
```

Then, check your version like so:
```
select version();
```

Your version should be at least 13.7. Here's mine:

```
 PostgreSQL 13.7 on x86_64-apple-darwin21.3.0, compiled by Apple clang version 13.1.6 (clang-1316.0.21.2), 64-bit
``` 

If your version is lower than 13.7, upgrade like so:
```
brew install postgresql@13
```

**Comment by joemasilotti** [comment]
Ah, that's great to know! Thanks for digging in and following up.

Unfortunately we [can't set a minimum version in the Brewfile](https://github.com/Homebrew/homebrew-bundle/issues/547#issuecomment-525443604), so `Brewfile.lock.json:272` will have to do for now!

**Comment by malachaifrazier** [comment]
Sweet. Think it's worth specifying `postgresql@13` in the README?

**Comment by axhgl** [comment]
In case anyone is trying to `bin/setup` in Debian 11 and you have multiple versions (e.g. `9.6, 12.x, 14.2`) of "postgresql" installed, make sure that the server of the right version (`13+`) is listening on port `5432`. 
One could check/modify that in the `postgresql.conf` file, e.g. in case of version 13:  `/etc/postgresql/13/main/postgresql.conf`.   

In my case, I had "postgresql v.9.x" running on port `5432` hence the syntax errors were popping up when running migrations.

**Comment by joemasilotti** [comment]
Thanks for this @axhgl! Would you mind adding a note to the README for future contributors?

**Comment by axhgl** [comment]
You're welcome, @joemasilotti! Sure. I'll soon give it a try.
