### ISSUE TITLE
Refactor business logic to a service layer

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#433]
I attended a talk at RailsConf that really got me thinking. [Your Service Layer Needn't be Fancy, It Just Needs to Exist](https://railsconf.org/schedule#session-1281) from David Copeland, author of [Sustainable Web Development with Ruby on Rails](https://sustainable-rails.com).

The gist was that all of your business logic is scattered across your app. If you need to know _what_ your app does you have to open models, controllers, jobs, and maybe even some views. Instead, he proposed moving all business-specific code to a service _layer_.

Note "layer" and not object. He doesn't care _how_ you do it (POROs were recommended) just that it has to exist. And it doesn't need to be complicated.

---

Based on that I'm inspired to try and consolidate some business logic of railsdevs into `services/`. I kind of already started this with #387 but it could be extended further. Here are some high-level guidelines for what I'm planning.

* Move non-database-related logic out of Active Record models
  * Exception: keep validations in the model
  * "Creating a user via the website is not the same adding a row to the database"
* Move business-related logic into a PORO under `services/`
  * `CreateDeveloper#create_developer(developer_params)` is better than `DeveloperService.create(params)` - explicit about exactly what each class and method does
* Service layer _could_ be moved to a Ruby command line app
  * Return a state and the model, let the controller switch on that and generate the path
  * Return an error message, let the controller shove it in the flash
* Roll our own authorization
  * Consolidate _logic_ into specific services, but Pundit has proved too limiting

**Comment by joemasilotti** [comment]
> Have you seen [u-case](https://github.com/serradura/u-case)?

I haven't, no! I'm trying to stay as "boring" as possible right now but I will take a look for inspiration.

Do you use it in your projects?

**Comment by aquilarafa** [comment]
> > Have you seen [u-case](https://github.com/serradura/u-case)?
> 
> I haven't, no! I'm trying to stay as "boring" as possible right now but I will take a look for inspiration.
> 
> Do you use it in your projects?

Yes. I started "boring" as well. Once a controller starts to be more complex than simple operations I eventually extract to a domain layer with usecases.

**Comment by aquilarafa** [comment]
<img width="400" alt="Uploaded using RayThis Extension-11" src="https://user-images.githubusercontent.com/33739544/169650849-d1e83781-adee-4860-8135-7df2b5f69d07.png">


A usecase flow is made of "micro"cases or steps. It's very readable. I also like the functional style to unfold results (Success or Failure objects).
<img width="400" alt="Uploaded using RayThis Extension-9" src="https://user-images.githubusercontent.com/33739544/169650788-1a4468b9-2531-4791-808b-d912515e9b21.png">

**Comment by jacobdaddario** [comment]
That's pretty slick, and I could see it working really well in super-large applications. That said, I wonder if it becomes a bit of an over-abstractions when you're just dealing with 5-10 people contributing at any given time.

**Comment by aquilarafa** [comment]
This project 

> That's pretty slick, and I could see it working really well in super-large applications. That said, I wonder if it becomes a bit of an over-abstractions when you're just dealing with 5-10 people contributing at any given time.

I'm new to rails. Didn't build a lot of projects but I think it brings convention and good design to bigger teams.

**Comment by aquilarafa** [comment]
For the 'create developer' task I know that a CreateDeveloper usecase exists somewhere.

**Comment by davidteren** [comment]
You could consider [interactor](https://github.com/collectiveidea/interactor)

It's nice to use very lightweight **interactors** that call helper modules or classes which in turn are super easy to test in isolation. 
Several **interactors** can be called by an **organizer**  with each passing a `context` that will return the result and any relevant message.

**Comment by joemasilotti** [comment]
> What's very interesting to me is that I've enjoyed your approach of keeping the app as vanilla Rails as possible. There's a lot you can you within that `app/models` folder and I think that creating a separate `app/services` folder feels like a (small) step outside of the Rails way of doing things. 

Thanks @andreimaxim, I needed to hear this.

The more service layer/objects I write the worse I feel about them. All I want to do is extract a DSL or parent object when I really want freedom to return whatever makes the most sense.

I also feel like I'm adding more and more code, and more and more indirection, to not accomplish much. Testing controllers via integration tests isn't hard these days. Yes, they are much slower than a unit level test. But I feel like with a sub 10 second test suite that's a trade off I'm willing to make.

---

I'm going to close this issue and accompanying PR #434 for now. Thanks to everyone who provided feedback!
