### ISSUE TITLE
Truncated unrendered HTML on the 'developers available now' list

### ISSUE THREAD

**Issue by harry-wood** [joemasilotti/railsdevs.com#444]
**Describe the bug**
I saw the profile text for this chap https://railsdevs.com/developers/531 showing up on the homepage 'developers available now' list, but it looked like this:

**Screenshots**

<img width="530" alt="Screenshot 2022-05-24 at 21 22 05" src="https://user-images.githubusercontent.com/227525/170126412-2f5b1927-a365-4c2c-8fef-c7f1495478ad.png">

**Expected behavior**
I'm not sure. Perhaps on the homepage it needs to drop all HTML (condense to only plain text) prior to truncating the string.

But is the profile allowing user-crafted HTML? Maybe that's a mistake. [Security issue?](https://security.stackexchange.com/questions/135513/what-could-an-img-src-xss-do)

**Comment by joemasilotti** [comment]
Thanks for calling this out! I'm not sure if it is a security issue, but I don't want to deal with the edge cases of images in the bio right now. Sanitizing the input might be a good first pass. I'll dig in.

In the meantime, @malachaifrazier, can you please remove the image from your bio?

**Comment by malachaifrazier** [comment]
@joemasilotti Yessir!

**Comment by malachaifrazier** [comment]
Done & done
