### ISSUE TITLE
Cannot change location at the user#edit

### ISSUE THREAD

**Issue by ogirginc** [joemasilotti/railsdevs.com#457]
## Describe the bug

When the user tries to edit their location, saving changes the values to an Italian address.

## To reproduce

1. Go to `user#edit`
2. Change `City`, `State` and `Country`.
3. Click save.
4. Go to `user#show`.
5. You should see the address as the same Italy address.

## Expected behavior

Save the provided address.

## Actual behavior

Displays an unrelated Italian address.

## Screenshots

<img width="671" alt="Screenshot 2022-05-31 at 13 02 48" src="https://user-images.githubusercontent.com/7466873/171148722-b8ed50c6-bd6b-452c-9ed6-d63c160f0d34.png">

## Additional context

https://user-images.githubusercontent.com/7466873/171148804-a37ad584-a24d-46b0-99eb-7c66d3a05018.mp4

**Comment by ogirginc** [comment]
It does work with others. The issue might be due to countries like Turkey not having states. For example, when I put Istanbul as a state, it did work. 

TBH, it's a minor annoyance (at least to me) and I don't think it is worth an update. 🤷

**Comment by joemasilotti** [comment]
Sounds good, thanks for following up!

**Comment by ogirginc** [comment]
FYI, this seems to be still an issue as I just got a DM from an Italian company 😅

**Comment by ogirginc** [comment]
Here is a Jam of the issue: https://jam.dev/c/5ff27d17-adae-45da-a603-07baf03d7829
