### ISSUE TITLE
Add filter developers by Availability

### ISSUE THREAD

**Issue by maful** [joemasilotti/railsdevs.com#46]
This will be easier to find the developer by their availability

Here's the time range I propose:
- All -> this is the default one
- Available Now
- In a week
- In two weeks
- In a month
- More than a month

**Comment by lsparlin** [comment]
Is anyone working in this? I cannot not

**Comment by joemasilotti** [comment]
I'm wondering if we need a filter here. Like, would sorting by availability work even better? I imagine employers would be looking for devs ASAP, but I could be wrong. 

Maybe we could add a sorting option (default to recently added) for next available date. Then, group everyone by how far out they are. For example, Available Now, available in less than 1 month, less than 3 months, etc. 

What do folks think about that?

**Comment by A7madXatab** [comment]
Shouldn't we allow turning availability off?. Like it's not required?. Currently, we don't allow to create an account unless the availability is set. How about we allow nil values and when nil, we count them as unavailable ?

**Comment by joemasilotti** [comment]
I wanted availability to be mandatory, but it seems like folks are kind of abusing the date by selecting something unreleasticly in the future. So I've changed my mind and would be happy to make `available_on` not required.

**Comment by maful** [comment]
@joemasilotti I will create a PR to make `available_on` optional

**Comment by joemasilotti** [comment]
Sounds great, thanks, @maful!

**Comment by joemasilotti** [comment]
The site has changed a bit since this issue was opened. I'm going to close this for now as I focus on Messaging and Payments.
