### ISSUE TITLE
"Showing X of Y developers" on `/developers`

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#473]
When searching for developers it's not always obvious how many are in the list. Or if you've filtered everyone out.

A PR addressing this issue should:

- [ ]  Add "Showing X of Y developers" to search results on `/developers`

I'm not 100% sure _where_ this should go or how it should look. So I'm open to ideas!

**Comment by troyizzle** [comment]
@joemasilotti I'd like to work on this!

**Comment by joemasilotti** [comment]
Sure thing! Once we close out your other open PRs and issues I'll assign it to you.

Two things we have to figure out:

1. Where does the text go?
2. How do we calculate Y? Is it total developers on the site, ones looking for a job, not invisible, etc.?

**Comment by joemasilotti** [comment]
Hey @troyizzle, now that your other issue is wrapped up, do you want to take this one on?

**Comment by troyizzle** [comment]
@joemasilotti yes sir!

**Comment by joemasilotti** [comment]
All yours!

**Comment by joemasilotti** [comment]
@troyizzle, I just pushed a small PR with some design ideas for the banner. Feel free to build on that or roll your own!

https://github.com/joemasilotti/railsdevs.com/pull/502

**Comment by troyizzle** [comment]
@joemasilotti I looked into this some and I'm not sure how the best way of doing this without some major changes to the `PagyPaginatorComponent`. I thought I could just add something like

In `developers/index.html.erb`
```        
<%= turbo_frame_tag "developers_pagy" do %>
   <%= render "banner", pagy: @query.pagy %>
<% end %>
```

In `components/pagy_paginator_component/pagy_paginator_component.html.erb`
```
<%= tag.turbo_stream target: "developers_pagy", action: "replace" do %>
  <%= tag.template do %>
    <%= render "developers/banner", pagy: pagy %>
  <% end %>
<% end %>
```

But to no luck... I assume its because you can't _break_ out of turbo frame?

Looking forward to your feedback!

**Comment by joemasilotti** [comment]
Hmm, I'm not sure I follow. Why does this have to be inside the Turbo Frame? Can we add a new partial or View Component and render it on `app/views/developers/index.html.erb:47`? We can pass in the `pagy` object to get the total count I believe.

**Comment by troyizzle** [comment]
That is what I tried unfortunately to no luck, I believe since it can only update things in scope of the turbo frame its being called from?

**Comment by joemasilotti** [comment]
Weird... am I missing something in #502? If not, I'll merge that PR for now.

**Comment by troyizzle** [comment]
Looks good Joe! I was thinking it would be something like on the first results
"1 of 20"
and when loading more results that would get updated to
"1 of 23"

Sorry for the misunderstanding Joe but glad to see your finished solution for it!

**Comment by joemasilotti** [comment]
Ahhh, that makes sense. Well, that's on me then for not explaining the issue clearly enough. Thanks for the help!
