### ISSUE TITLE
Markdown support for messages

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#474]
Developers and (some) businesses have been using markdown-like syntax in their messages. I'd like to support and encourage this as it makes it easier to communicate.

A PR addressing this issue should:

- [ ] When converting _new_ messages to HTML run them through a markdown parser
- [ ] Only allow the following markdown:
    * New paragraphs (blank line between blocks of text)
    * Bold
    * Italics
    * Inline code
    * Code blocks
    * Block quotes
    * Links

All other tags should ignored (like images, headings, tables, etc.).

Note that we are already using [auto_html](https://github.com/dejan/auto_html) and `simple_format` to currently covert and render the message content. Ideally we can configure this gem to do what we want. If not, please propose what gem you would like to use before submitting a PR.

**Comment by faqndo97** [comment]
@joemasilotti I'm researching a little bit about this. 

About paragraphs, they should be already formatted with the `simple_format`, shouldn't they?

Related to the other pieces, we have two options. The first one is to use the markdown formatter of auto_html, but it will allow more markdown tags. Behind the hood, auto_html uses redcarpet, which is written in c, so we don't have much space to play with.

Another option is to use [kramdown](https://kramdown.gettalong.org/), but we'll have the same problem, but it is written in c, so maybe we can monkey patch the main class not to parse the things that we don't want.

In case that doesn't work, we can check the parsers for the different tags that kramdown is using ([here](https://github.com/gettalong/kramdown/tree/master/lib/kramdown/parser/kramdown)) and write our modules and put them in the auto_html pipeline. 

What do you think?

**Comment by joemasilotti** [comment]
Thanks for diving in!

I'm using Redcarpet already so I'd like to stick with that, if possible.

It looks like you can disable some attributes (like images) by [configuring the renderers](https://github.com/vmg/redcarpet#darling-i-packed-you-a-couple-renderers-for-lunch). I wonder if that will get us most of what we want.

**Comment by joemasilotti** [comment]
Closing this to prioritize other work. I'd rather add in Trix to the message form than support markdown at this point.
