### ISSUE TITLE
Localize copy in `Conversations::HiringFeeComponent`

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#477]
A PR addressing this issue should:

- [ ] Move the hard-coded strings in `Conversations::HiringFeeComponent` to the locale file

Only translate to English - don't worry about other languages for now.

**Comment by atiqueakhtar** [comment]
Hii @joemasilotti I would like to work on this issue. I will raise a PR for the same. Please do have a look.

**Comment by joemasilotti** [comment]
All yours!

**Comment by atiqueakhtar** [comment]
Hi @joemasilotti I am getting following error on pushing my commit via `git push -u origin main`

> ERROR: Permission to joemasilotti/railsdevs.com.git denied to atiqueakhtar.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by joemasilotti** [comment]
You will need to fork the repository and push to your fork. Then you can open a PR against this repo from your fork.

https://docs.github.com/en/get-started/quickstart/fork-a-repo

**Comment by atiqueakhtar** [comment]
Hi @joemasilotti . Thanks a lot!
I have raised a PR addressing this particular issue: [Move the hard-coded strings in HiringFeeComponent to the locale file](https://github.com/joemasilotti/railsdevs.com/pull/491#)
Please let me know if it looks good.

**Comment by joemasilotti** [comment]
Closed via #491.
