### ISSUE TITLE
Profile appears on home page although work preference is "open"

### ISSUE THREAD

**Issue by ahmgeek** [joemasilotti/railsdevs.com#488]
## Describe the bug

Profile appears on home page although work preference is "open"
<img width="1017" alt="Screenshot 2022-06-12 at 13 45 59" src="https://user-images.githubusercontent.com/4132009/173231591-faee289d-20ee-4b5d-983d-456499f0eea4.png">
<img width="1269" alt="Screenshot 2022-06-12 at 13 46 16" src="https://user-images.githubusercontent.com/4132009/173231597-06b4a504-5275-41cf-bee1-e725a431c475.png">

## Expected behavior
Profile Shouldn't be listed on home page

## Actual behavior
Profile present on home page

**Comment by joemasilotti** [comment]
Thanks for the report! Bug fix incoming.
