### ISSUE TITLE
Admins can view invisible developer profiles

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#503]
When I get notified of new developer profiles some have been set to invisible. I'd still like to review their profile to make sure they aren't obvious spam.

## A PR addressing this issue should:

- [ ] Allow admins to view invisible developer profiles

This change can be made in `app/policies/developer_policy.rb`.

**Comment by kaushikhande** [comment]
Hi @joemasilotti 
Can I work on this issue?

**Comment by joemasilotti** [comment]
Sure thing! All yours.

**Comment by kaushikhande** [comment]
@joemasilotti Added PR https://github.com/joemasilotti/railsdevs.com/pull/505.
Please review

**Comment by joemasilotti** [comment]
Closed via #505.
