### ISSUE TITLE
Site-wide banner indicating your profile is invisible

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#504]
Developers have been marking their profile as invisible to not show up on the site. Some of these are because they found a job and are longer looking! Odds are they won't come back to the site for a while.

But for the others, I'd like to let them know a bit more aggressively that their profile isn't appearing for anyone else.

## A PR addressing this issue should:

- [ ] Add a banner to every page indicating such linking to edit your profile (if your developer profile is invisible).

Design can be copied form `NewFieldsComponent` and rendered from `app/views/shared/_main.html.erb`.

**Comment by joshio1** [comment]
Hi there! 👋
I'd be happy to work on this one!

**Comment by joemasilotti** [comment]
Sure thing – all yours!

**Comment by joshio1** [comment]
Thanks, I have a few questions:

1. When the user clicks on the CTA and is on the `Edit Developers` page, do we still show the banner? Or is there any change we need to do on that screen?
2. Do you have anything specific in mind as far as the verbiage for the banner is concerned? (for both the title and CTA)
3. I saw that the NewFieldsComponent does not have an equivalent version in other languages. Do we require localization for this component?

**Comment by joemasilotti** [comment]
Closed via #509.
