### ISSUE TITLE
Resize avatars to displayed sizes

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#513]
Running a [PageSpeed Insight audit](https://web.dev/measure/?url=https%3A%2F%2Frailsdevs.com) on railsdevs highlights a few areas of improvement. This issue hopes to remedy the following:

> Avoid enormous network payloads Total size was 6,175 KiB

## A PR addressing this issue should:

- [ ] Use [Active Storage variants](https://api.rubyonrails.org/v6.1.0/classes/ActiveStorage/Variant.html) to resize avatars to appropriate sizes
- [ ] Ensure that 1x and 2x sizes work correctly for relevant devices

**Comment by bradpurchase** [comment]
I'd be happy to take a swing at this one!
