### ISSUE TITLE
Load images lazily

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#514]
Running a [PageSpeed Insight audit](https://web.dev/measure/?url=https%3A%2F%2Frailsdevs.com) on railsdevs highlights a few areas of improvement. This issue hopes to remedy the following:

> Serve images in next-gen formats

## A PR addressing this issue should:

- [ ] Set [image loading to `lazy` via Rails configuration](https://blog.saeloun.com/2021/03/01/rails-6.1-adds-config-for-lazy-image-loading.html)
- [ ] Ensure that images load without issue in Chrome, Safari, and Firefox

**Comment by joshio1** [comment]
Hi,

Can I pick this one?

**Comment by joemasilotti** [comment]
Sure thing - all yours!

**Comment by joshio1** [comment]
Hey @joemasilotti,

I was looking at this one and [I added the config](https://github.com/joemasilotti/railsdevs.com/compare/main...joshio1:feature/load_images_lazily?expand=1) to lazily load the images application wide. 

I just wanna flag that it still loads 8/10 images on the first page load. I tested this with adding 10 more developers to the seeded data such that they show up on the front page. Without this config, 10/10 avatars are loaded and with this config  8/10 avatars are loaded. So I'm not sure how much it would help optimize the results in the [audit](https://web.dev/measure/?url=https%3A%2F%2Frailsdevs.com). But, I just wanted to flag this before I raise this PR.

<img width="1426" alt="image" src="https://user-images.githubusercontent.com/21145429/175211596-23eaf540-0211-46ef-b78f-5204d19473d4.png">

**Comment by joemasilotti** [comment]
Thanks for diving in! I think that's expected behavior. If I understand correctly, Chrome looks ahead 2000px or something to load all images.

Have you tested to make sure the images load OK in Safari and Firefox?

**Comment by joshio1** [comment]
> Thanks for diving in! I think that's expected behavior. If I understand correctly, Chrome looks ahead 2000px or something to load all images.
> 
> Have you tested to make sure the images load OK in Safari and Firefox?

Yes, Chrome [looks ahead 1250px to 2500px](https://web.dev/browser-level-image-lazy-loading/#distance-from-viewport-thresholds) depending on the connection speed.

Yep, the images load OK in Safari and Firefox. I'll raise a PR for this.
