### ISSUE TITLE
Add invisible captcha to sign up form

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#517]
I've had recent spam complaints of confirmation emails. Just to be safe, let's add a honeypot to trap some bots.

## A PR addressing this issue should:

- [ ] Add [invisible_catpcha](https://github.com/markets/invisible_captcha) to the registration form

**Comment by kaushikhande** [comment]
@joemasilotti Can I work on this issue?

**Comment by joemasilotti** [comment]
Hey @kaushikhande, do you still have appetite to work on this? I'm starting to see a bit more spam complaints and would like to have this out sooner rather than later. No worries either way!

**Comment by kaushikhande** [comment]
@joemasilotti Sorry. I do not have the bandwidth right now. Please proceed as you wish with this issue.

**Comment by joemasilotti** [comment]
All good – I can take it.
