### ISSUE TITLE
Serve avatars at 1x and 2x

### ISSUE THREAD

**Issue by bradpurchase** [joemasilotti/railsdevs.com#519]
As of #518, we generate variants for avatars @2x the displayed size instead of scaling down the full image. For instance, avatar thumbnails are displayed at 32x32, while the thumbnail itself is 64x64.

As per [this comment](https://github.com/joemasilotti/railsdevs.com/pull/518#issuecomment-1164461961), we want to push this further this by also serving avatars at 1x and 2x via HTML.

## A PR addressing this issue should:

- [ ] Create HTML markup that ensures 1x and 2x images are rendered for the correct screen resolution

I _think_ this might involve using the `srcset` attribute on `<img>` but can't say for sure.

**Comment by prikeshsavla** [comment]
Something like this probably 
https://www.dofactory.com/html/img/srcset

```html
<img srcset="/img/html/vangogh-sm.jpg 120w,
             /img/html/vangogh.jpg 193w,
             /img/html/vangogh-lg.jpg 278w"
     sizes="(max-width: 710px) 120px,
            (max-width: 991px) 193px,
            278px">
```

**Comment by joemasilotti** [comment]
Ooh nice! That will be a fun helper to build. 

From my understanding a good portion of desktop monitors are still 1x. And desktop makes up almost 50% of traffic.

Regardless, PageSpeed checks this. :)
