### ISSUE TITLE
Filtering by location includes other countries

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#522]
## Describe the bug

Filtering by United States shows some developers in other countries, France for example. 

## To reproduce

1. Go to `/developers`
2. Check United States under Location
2. Apply the filter

## Expected behavior

Only United States-based developers should appear. 

## Actual behavior

Developers from other countries appear, like [this one](https://railsdevs.com/developers/583). 

## Additional context

My first guess is that we aren't passing the filters to pagination correctly.

**Comment by imella** [comment]
Hey @joemasilotti ! I can take a look at this. I also confirmed that filters are not being passed to the pagination call

**Comment by joemasilotti** [comment]
Yes please! Thanks so much.
