### ISSUE TITLE
Self-host Inter font

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#525]
The biggest opportunity according to PageSpeed Insights is to eliminate render-blocking resources.

## A PR addressing this issue should:

- [ ] Self-host the [Inter font](https://rsms.me/inter/)

<img width="1128" alt="image" src="https://user-images.githubusercontent.com/2092156/175924622-c6354fea-961c-4a67-ae37-65966a693e9b.png">

**Comment by adrienpoly** [comment]
Looking at the css that is downloaded https://rsms.me/inter/inter.css it looks like all font weight are defined (from 100 to 900). What are the font weight that you really need within your design system? 
I think the major optimisation would first come by downloading only the fonts that you really need.

**Comment by joemasilotti** [comment]
For this issue I'd rather self-host the entire font family. In a future issue we can review if removing some weights would help enough. My concern is that if/when we do decide to add a new weight it would be confusing as to why it wasn't working right away.

---

But to answer your question, railsdevs is currently using 5 of the 9 available weights:

* ~`font-thin`~
* ~`font-extralight`~
* ~`font-light`~
* `font-normal`
* `font-medium`
* `font-semibold`
* `font-bold`
* `font-extrabold`
* ~`font-black`~

**Comment by adrienpoly** [comment]
Ok will give it a try
