### ISSUE TITLE
Creating an invisible developer profile raises an error

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#533]
## Describe the bug

If you set your search status to invisible when creating your developer profile the app 500s.

## To reproduce

1. Create a new account
2. Visit `/developers/new`
3. Fill in the required fields (name, hero, bio, city, and avatar)
4. Set "Search status" to Invisible
5. Click "Save"

## Expected behavior

The developer profile is created without issue.

## Actual behavior

The app returns a 500, raising the following exception:

```
ActionController::UrlGenerationError: No route matches {:action=>"edit", :controller=>"developers", :id=>#<Developer id: nil, ...}, possible unmatched constraints: [:id]
```

## Additional context

I _think_ #509 introduced this regression.

**Comment by joemasilotti** [comment]
@joshio1, would you like to take a pass at this? If not, no worries at all I can handle it tomorrow.

**Comment by joemasilotti** [comment]
Thank you!

**Comment by joshio1** [comment]
So, I had a look at this one. But the steps to reproduce were a little different from what I saw. I could reproduce the failure but only when we don't enter the required fields, have the search status as `invisible` and then click Save.

I was able to reproduce the failure with a test-case in this branch: https://github.com/joemasilotti/railsdevs.com/pull/534

If there is anything else, please let me know.

Also, I found that the priority of the banners was mixed up. Do you have a way to write tests such that we could've caught this?

**Comment by joemasilotti** [comment]
Ohh, good catch. Hmm... we could add a test that would trigger multiple banners and ensure that the right one is rendered.
