### ISSUE TITLE
Add rate and/or salary to developer profiles

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#55]
I'd love a way for developers to show their expected rate or salary, optional of course. One way would be to do ranges; a min and max for each. The other approach is to set an expected target as a single number.

I'd love feedback on this from folks! What would you rather fill out on your developer profile?

**Comment by maful** [comment]
Ya, that's a good idea

The hourly rate is a common one I think for freelancers, are we going to show the expected rate or salary publicly or only for authenticated users?

**Comment by joemasilotti** [comment]
Everything except email and personal links is planned to be shown publicly.

**Comment by JuanVqz** [comment]
I think one field is good enough for now

**Comment by peterberkenbosch** [comment]
not sure if the max is needed? min would be a good indication where to start. I usually do retainer contracts where the base hourly goes down a bit based on the minimum hours reserved per month (or 4 weeks to make it more complex ;).

Btw. love this!

**Comment by joemasilotti** [comment]
Yeah, I'm leaning more towards one field (for each) as well.

`developers.expected_salary` and `developers.expected_hourly_rate` should work, where both are optional.

**Comment by peterberkenbosch** [comment]
Started working on this in #108

**Comment by joemasilotti** [comment]
Closed via #108.
