### ISSUE TITLE
Filter accordion not open when filters present

### ISSUE THREAD

**Issue by dqnamo** [joemasilotti/railsdevs.com#558]
## Describe the bug
A super small user experience issue but when a filter is selected, ideally the heading accordion should remain open but it isn't.

## To reproduce

1. Go to developers index page
2. Click on location
3. Select country or countries
4. apply filters
5. Notice accordion not open

## Expected behavior

If a filter is selected in a particular heading, the heading accordion should remain open.

## Actual behavior

If a filter is selected in a particular heading, the heading accordion is closed.

## Screenshots

<img width="367" alt="CleanShot 2022-07-11 at 20 56 29@2x" src="https://user-images.githubusercontent.com/25507937/178347494-028f0a5d-b6ed-4fcb-b3bc-7986548d9868.png">

<img width="420" alt="CleanShot 2022-07-11 at 20 54 44@2x" src="https://user-images.githubusercontent.com/25507937/178347361-ef53e50f-754d-4c4a-8fa8-0d4064f124b8.png">

**Comment by joemasilotti** [comment]
I agree, thanks for documenting this!

**Comment by ypcethan** [comment]
@joemasilotti, I'm happy to help with this.

**Comment by ypcethan** [comment]
The same bug seems to happen to the `TimeZone` accordion as well.

**Comment by joemasilotti** [comment]
Thanks!

**Comment by joemasilotti** [comment]
Closed via #586.
