### ISSUE TITLE
Make it clear that links shouldn't get added to the developer bio

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#560]
I've had to manually reach out to a few developers to remove links from their bio. Ideally, that section of the website is anonymous. This helps protect their identity and puts more emphasis on the single "website" link for paying businesses.

## A PR addressing this issue should:

- [ ] Update the help text on the bio when editing your developer profile

It should read, in full:

> Write a few sentences about yourself. Links and personally identifiable information will be removed.

**Comment by kaushikhande** [comment]
@joemasilotti Can I take this issue.

**Comment by joemasilotti** [comment]
Sure thing! All yours.

**Comment by kaushikhande** [comment]
PR: #584

**Comment by joemasilotti** [comment]
Closed via #584.
