### ISSUE TITLE
Remove hardcoded JSON string in fixture

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#567]
During the Rails 7.0.3.1 upgrade I had to hardcode a JSON string into a test fixture. Ideally, this can be changed to a better representation (like a hash or more YAML) but I couldn't figure it out.

## A PR addressing this issue should:

- [] Replace the hardcoded JSON string in the `OpenStartup::Metric` fixture

`test/fixtures/open_startup/metrics.yml:3`

**Comment by gathuku** [comment]
@joemasilotti allow me to have a look at this.

**Comment by joemasilotti** [comment]
Sure thing - all yours!
