### ISSUE TITLE
Saved login suggestion not working in iOS app

### ISSUE THREAD

**Issue by jespr** [joemasilotti/railsdevs.com#568]
## Describe the bug

After having downloaded the Railsdevs iPhone app, when you go to log in you're not presented with your saved login from 1Password ~/iCloud keychain~. You have to go search for it. I have confirmed it works as expected in Safari when not using the app.

## To reproduce

1. Download iOS app from the App Store
2. Go to the sign in page
3. Tap on the email field
4. No suggested login pops up, you have to search

## Expected behavior

I expected iOS would've suggested my saved login information to be used

## Actual behavior

iOS didn't suggest my saved login to be used

## Additional context

I have verified that my saved login information is suggested on railsdevs.com using Safari on iPhone. I'm not seeing the same behavior when using the iOS Railsdevs app.

**Comment by jespr** [comment]
This is what I have in 1Password 

![image](https://user-images.githubusercontent.com/311936/178744399-1a3c6f2b-0446-4254-b7a2-7520c6d15a1d.jpeg)

**Comment by jespr** [comment]
Adding www in front of railsdevs.com in 1Password doesn't make a difference either - just tried to see if that was it

**Comment by joemasilotti** [comment]
Interestingly, iCloud passwords find it OK.

![image](https://user-images.githubusercontent.com/2092156/178766359-947a583b-92fd-43c8-958b-22a9cff0345f.jpeg)

**Comment by jespr** [comment]
Yep. Works fine for me with iCloud passwords as well - I missed that earlier, my bad. It was early :D

**Comment by joemasilotti** [comment]
Closing this because iCloud passwords is good enough for me, for now.
