### ISSUE TITLE
Business profile links are easily broken

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#573]
## Describe the bug

Adding a website link to a business profile often creates an invalid URL.

## To reproduce

1. Sign up for a new account
2. Visit `/businesses/new`
3. Fill out the form
4. Set `https://example.com` as the Website field
5. Visit your profile
6. Click your company name

## Expected behavior

You navigate to `https://example.com`.

## Actual behavior

You are navigated to `https://https://example.com`

## Additional context

We handle this type of normalizing in the developer profile. Logic from there can be extracted or copied over to handle this issue.

**Comment by ypcethan** [comment]
Hi @joemasilotti, I would love to help with this. 🙂

**Comment by joemasilotti** [comment]
Thanks! All yours.

**Comment by joemasilotti** [comment]
Closed via #577.
