### ISSUE TITLE
Avatar Picture Upload State on Developer Profile Create fails to update

### ISSUE THREAD

**Issue by horaciovelvetine** [joemasilotti/railsdevs.com#592]
## Describe the bug

When creating a new developer account, if you attempt to save the profile without an avatar picture the form raises an error as expected. Subsequently when an avatar is uploaded, the 'avatar required' error sticks around on the page persisting through a successful upload, and the avatar circle (place where I would've expected an avatar preview) does not populate with a preview. 

## To reproduce

1. Go to 'https://www.railsdevs.com'
2. Click on 'Register', follow confirmation steps (click email confirmation link)
3. 'What brings you to railsdevs' click: 'Im looking for work'
4. Fill in all required profile information, omit an avatar/profile picture
5. Click 'save'
6. Raises prohibited this developer from saved: 'Avatar is not attached'
7. Upload a photo

## Expected behavior

Error from top of page should change to a confirmation 'Avatar uploaded', and button too 'Upload is attached'. Possibly with 'success' green coloring

## Actual behavior

Raised error remains at top of page, and avatar button remains 'Upload is not attached' while saving profile is not possible as avatar has been uploaded

## Screenshots

![Screen Shot 2022-08-01 at 1 34 50 PM](https://user-images.githubusercontent.com/78946408/182230993-942e9a17-54a7-45b3-8bde-64f761b3b016.png)

**Comment by joemasilotti** [comment]
I can also reproduce when trying to upload an image before submitting an invalid form.
