### ISSUE TITLE
Better discoverability for developers

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#597]
With 500+ (!) developers on the site it's become harder for individual folks to stand out. A developer can be featured for a week, but that doesn't solve the core issue.

I'm planning to talk with businesses over the next few week. Ideally I will learn is difficult for them in searching and be able to pull out some product improvements. I'm also going to talk to developers and hear what kind of info they would like to share on their profile.

Until then, I won't be writing any code or outlining specific features.

### Running list of ideas

* Endorsements from other developers (@GALTdea)
* More sorting options: recently updated, random
* Badges - RailsDevs source contributors, high/100% message response rate, recently updated
* Expertise/interest tags – set by developer

P.S. If you would like to share your thoughts on this (as a business or developer) then please [let me know](mailto:joe@railsdevs.com)!

**Comment by GALTdea** [comment]
Would be great to be able to display some kind of endorsement.

**Comment by joemasilotti** [comment]
@GALTdea, what kind of endorsement were you thinking? From another person, technology/skill-based, something else?

**Comment by GALTdea** [comment]
Probably from other developers that you've paired with or opensource you've contributed to.  In terms of what kind of endorsement, I'd say technical.  Perhaps something related to the  interaction?

**Comment by joemasilotti** [comment]
Closing this out in favor of #639.
