### ISSUE TITLE
Remove Twitter from developer Open Graph tags

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#603]
A PR addressing this issue should remove the `#twitter` method from `app/components/developers/open_graph_tags_component.rb:28`.

**Comment by sarthakw7** [comment]
Hey, Can i work on this issue?

**Comment by joemasilotti** [comment]
Sure thing! All yours.

**Comment by de-marauder** [comment]
Hi, is this issue still available? I'd like to work on it.

**Comment by joemasilotti** [comment]
No, @sarthakw7 is working on it in #607.

But #606 hasn't been claimed yet if you'd like to give that one a go!

**Comment by de-marauder** [comment]
Alright. I'll give it a look. Thank you

**Comment by joemasilotti** [comment]
Closed via #607.
