### ISSUE TITLE
Link to "impersonate" from `/admin/users` and remove `/admin/impersonate`

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#606]
A PR addressing this issue should:

1. Link to "Impersonate" from each user in `/admin/users`
2. Remove the views and links for `/admin/impersonate`

**Comment by vsmay98** [comment]
Hi @joemasilotti 
Can I work on this issue?

**Comment by joemasilotti** [comment]
Sure thing, all yours @vsmay98!

**Comment by KarlHeitmann** [comment]
Hello there! Is there any progress in this issue @vsmay98  ? I already have something working on my local fork to submit.

**Comment by vsmay98** [comment]
Hi @KarlHeitmann 
Please go ahead and raise a PR. I will unassign myself from this issue.

**Comment by KarlHeitmann** [comment]
Ok, thanks. Here is the work in progress: https://github.com/joemasilotti/railsdevs.com/pull/627

I need to do the other two items from the checklist: `My code contains tests covering the code I modified`  and `I added significant changes and product updates to the changelog`, you can review it and send any other feedback.

**Comment by joemasilotti** [comment]
Closed via #627.
