### ISSUE TITLE
Send admins a notification when a `Hired::Form` is created

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#614]
A PR addressing this issue should:

* Create a new notification, `Admin::NewHiredFormNotification` when a `Hired::Form` is created
* `#title` - A developer was hired via RailsDevs!
* `#url` - `admin_hired_form_path`
* A new mailer on `AdminMailer` (and preview) should also be added

Feel free to use placeholder copy and I can tweak it when a PR is submitted.

**Comment by sarvaiyanidhi** [comment]
Hi @joemasilotti Would like to take up this feature.. can you please assign it to me?

**Comment by joemasilotti** [comment]
Sure thing – all yours @sarvaiyanidhi!

**Comment by joemasilotti** [comment]
Closed via #625.
