### ISSUE TITLE
Add "Found a job?" link to mobile menu

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#618]
The desktop view links to "Found a job?" in the main navigation but the dropdown mobile menu does not.

A PR addressing this issue should:

1. Add a link to "Found a job?" in the mobile dropdown menu.

**Comment by Kritikajain6104** [comment]
I want to work on this issue . Please assign this issue to me

**Comment by joemasilotti** [comment]
Thank you – all yours!

**Comment by Kritikajain6104** [comment]
#618 <https://github.com/joemasilotti/railsdevs.com/issues/618>
joemasilotti <https://github.com/joemasilotti>/railsdevs.com
<https://github.com/joemasilotti/railsdevs.com>
I am sorry. I don't know about brew technology. I have just started
contributing. This was my first issue. I thought it was an issue of Html,
Css and Javascript. Can you please tell whether I can work on this project
in HTML, CSS, Js.

**Comment by joemasilotti** [comment]
The code change will be in HTML, but in an interpreted Ruby file. So you will need to have the app running on your machine to make sure it all works.

What issue are you running into with brew? I can try to help get it straightened out.

**Comment by Kritikajain6104** [comment]
Ok I am trying.Thank you for your response.

**Comment by joemasilotti** [comment]
Hey again @Kritikajain6104. It's been 2 weeks so I wanted to check in and see if you still have appetite for this issue. If not, no worries! Let me know and I can assign it to someone else.

**Comment by xmarlox** [comment]
@joemasilotti 
happy to work on this one 😄

**Comment by joemasilotti** [comment]
@Kritikajain6104, since I haven't heard from you in 10 days I'm going to assign this over to @xmarlox. Feel free to pick up another issue.

**Comment by xmarlox** [comment]
@joemasilotti ✋🏽 
i believe this issue is already addressed

**Comment by joemasilotti** [comment]
You are correct, thanks @xmarlox!
