### ISSUE TITLE
Add context/tips when filling out developer profile

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#632]
### Goals

1: Help developers position themselves better to get hired.
2: Make it clear that profiles should remain anonymous (no real names in bio).

A PR addressing this issue should:

- [ ] Move the bio section of the developer form to its "card" before `Work preferences`
- [ ] Make the input text area 20 lines

The new card should be titled `Bio` with the following description:

Share what makes you unique as a developer. This is your chance to market yourself to potential employers – sell yourself a little! Examples:
* A recent milestone or accomplishment
* Something new you learned
* What your passionate about
* How you can help where others can't
* Your unique skills that make you awesome

The text under the text area should be:

> Please don't mention personally identifiable information, like your real name or links.

**Comment by rayhanw** [comment]
Hi @joemasilotti  Do you mind if I give it a shot? 😃

**Comment by joemasilotti** [comment]
Sure thing – all yours @rayhanw! Thanks for the help.
