### ISSUE TITLE
Rich text for developer bio

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#633]
The designer I'm working with noticed that multiple profiles are writing quasi-formatted lists and sections in their bio. I'd love to offer this as a real feature so folks can clean up their profiles a bit.

A PR addressing this issue should:

- [ ] Enable markdown in the developer bio field

When rendering, _only_ the following tags/elements should be displayed. Everything else should be stripped, removed, or sanitized.

* italics
* bold
* strikethrough
* ordered lists
* unordered lists
* headings
* code blocks
* inline code blocks

RailsDevs already has [Redcarpet](https://github.com/vmg/redcarpet), so ideally we can use that gem. Digging into the README it looks like there are options for disabling everything we don't want (images, styles, links, etc.).

**Comment by rayhanw** [comment]
I'd like to give this a shot 👋

**Comment by joemasilotti** [comment]
Sure thing! All yours, @rayhanw. Let me know if you run into any issues filtering out the right markup with Redcarpet.
