### ISSUE TITLE
Recently active badge

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#640]
This kicks off the first batch of work for [developer discoverability](https://github.com/joemasilotti/railsdevs.com/discussions/639)!

The goal of this feature is to highlight developers who have been recently active on the platform. "Active" is not limited to only updating a profile, but also responding to messages.

A PR addressing this issue should:

- [ ] Add a "Recently active" badge to developer cards if they sent a message or updated their profile in the last 7 days

The badge can mirror the design of the existing "Featured developer" badge with the following colors: `bg-green-100 text-green-800`. It might make sense to extract a new View Component for badges (if it doesn't already exist).

Implementation-wise, we don't want to query for a developer's last sent message as this could lead to N+1 situation. Instead, let's make sure that sending a message touches `developers.updated_at`. This might be as straightforward as adding `touch: true` to `app/models/message.rb:11` but I need to experiment.

Alternatively, we could create a new column and manage that directly. But it will require more work to maintain and I'm not inclined to add additional complexity if it isn't needed.

**Comment by sarvaiyanidhi** [comment]
I would like to work on this feature.. Can you please assign it to me?

**Comment by joemasilotti** [comment]
Sure thing @sarvaiyanidhi! All yours. Let me know if you have any questions when diving in.

**Comment by sarvaiyanidhi** [comment]
Sure. Will reach out in case of any query. Thanks

**Comment by joemasilotti** [comment]
Closed via #649.
