### ISSUE TITLE
Contributor profile badges

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#643]
The goal of this issue is to highlight developers who have contributed to the RailsDevs source code. To start, this will _not_ integrate with GitHub in any way. A single admin interface to manually toggle someone's status is good enough (for now). And the best part is, once a contributor always a contributor!

A PR addressing this issue should:

- [ ] Add a new boolean (non-null) column, `developers.source_contributor` defaulted to `false`
- [ ] If true, render a badge in the developer's card in search results
- [ ] If true, render a badge on the developer's profile page
- [ ] Add a new column to the table on `/admin/users` to toggle the status of that boolean

Note that the badge can follow the existing design patterns for "Featured developer" and "Recently active" but with the following colors classes: `bg-gray-100  text-gray-800`.

Also, the last item in this checklist will probably require a new route and controller for updating the status on the developer. `Admin::DevelopersController` with only the `source_contributor` param permitted could work!

**Comment by benmercerdev** [comment]
I'd like to take this on

**Comment by joemasilotti** [comment]
Sure thing, all yours @benmercerdev! Thanks for contributing.

**Comment by benmercerdev** [comment]
Hi @joemasilotti can you add me as a collaborator or give me permission to push my branch with this work for comments and review, thanks!

**Comment by benmercerdev** [comment]
I put up a draft PR https://github.com/joemasilotti/railsdevs.com/pull/677

Would love some advice on the UI to toggle the source_contributor attribute and also on the route and controller for that action

**Comment by joemasilotti** [comment]
Closed via #677.
