### ISSUE TITLE
Access developer profiles via slug, only

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#645]
The goal of this PR is to obfuscate the developer's ID to a hard-to-guess string of characters.

A PR addressing this issue should:

- [ ] Migrate the `developers` table primary key to UUID
- [ ] Ensure linking to developers works via `developer_path(developer)`
- [ ] Ensure “old” developer routes (e.g. `/developers/1`) return a 404

Notes and links:

* [Datatypes UUID - Rails Guides](https://guides.rubyonrails.org/v5.0/active_record_postgresql.html#uuid)
* [UUID Primary Keys - Rails Guides](https://guides.rubyonrails.org/v5.0/active_record_postgresql.html#uuid-primary-keys)
* [Migrate table from integer to UUID primary key](https://pawelurbanek.com/uuid-order-rails#how-to-migrate-a-table-from-integer-to-uuid-primary-key)

**Comment by adrienpoly** [comment]
Rather than uuid have you considered https://github.com/excid3/prefixed_ids ?

I like this Stripe like obfuscated ids

**Comment by joemasilotti** [comment]
I love Stripe's obfuscated IDs but I don't see the value in a project that doesn't have a real developer API. Said another way, what's the benefit of a developer having an ID of `dev_abc123` vs. `abc_123` if the only place you ever see it is in the URL of a developer's profile page?

**Comment by joemasilotti** [comment]
Thanks for bringing this up @adrienpoly. I ended up [opening a PR](#656) with what prefixed_ids uses under the hood, [hashid](https://github.com/jcypret/hashid-rails). I was worried about [not being able to salt prefixed_ids](https://github.com/excid3/prefixed_ids/issues/6) which would make it easy to guess URLs. Which kind of defeats the purpose of this task!
