### ISSUE TITLE
Publicly shareable URLs polish

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#647]
The goal of this issue is to clean up the UX around #646.

A PR addressing this issue should:

- [ ] When the “Share” button is clicked show a modal explaining how the public page works
- [ ] A Cancel buttons closes the modal
- [ ] A “Copy link” button copies the link to the clipboard

~This issue is blocked by #646.~ This issue is no longer blocked.

Reminder to include a disclaimer that the developer's email address will be shared if they share their profile via this method.

**Comment by sarvaiyanidhi** [comment]
Hi @joemasilotti I would like to work further on this issue.. can you please assign it to me?

**Comment by joemasilotti** [comment]
Sure thing! All yours @sarvaiyanidhi. Thanks again for all the help. :)

**Comment by joemasilotti** [comment]
Closed via #718.
