### ISSUE TITLE
Paywall location and timezone search, too

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#652]
The goal of this issue is to ensure someone doesn't "find" a candidate by filtering so tightly that they show up on the first page of search results.

A PR addressing this issue should:

- [ ] Require an active subscription to filter by location and/or timezone
- [ ] This includes the UI (like text search) and updating the Pundit policy

For reference, check out how the search query works. We might be able to borrow paywall logic from that.

**Comment by mansakondo** [comment]
I'd like to work on this one but I also volunteered for #653. So, I suppose that I should choose between the two, right?

**Comment by joemasilotti** [comment]
Both are needed to launch the new feature – which do you have a preference of starting, first? If it helps, this one should be more cut-and-dry since there are no remaining design decisions (I don't think).

**Comment by mansakondo** [comment]
I'd like to start with this one since there are fewer unknowns, but I'll still let you know if I have ideas for the CTA design.

**Comment by mansakondo** [comment]
I'm experimenting with a design where I added a variant for the `PaywallComponent` to only display the lock icon.:
![Capture d’écran de 2022-09-22 15-37-36](https://user-images.githubusercontent.com/47113995/191762198-12fa3887-9717-43ed-a295-429068ada024.png)

What do you think?

**Comment by mansakondo** [comment]
> Ohh, I like that design! How are you rendering the hover?

I'm glad that you like it! I'll open a draft PR right now to allow see the code. 

> Does it require any additional JavaScript or can we do it with CSS?

No additional JavaScript is required.

**Comment by mansakondo** [comment]
The draft PR is open. There's some dirty code waiting to be refactored.

**Comment by joemasilotti** [comment]
Got it – thanks for that!

Do you need an early set of eyes on the PR? Or would you like me to wait to review until it is marked as ready?

**Comment by mansakondo** [comment]
> Got it – thanks for that!
> 
> Do you need an early set of eyes on the PR? Or would you like me to wait to review until it is marked as ready?

Though the code still needs to be refactored, I'm open to suggestions.

**Comment by joemasilotti** [comment]
Closed via #674.
