### ISSUE TITLE
Revamp CTA design

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#653]
The goal of this issue is to improve the design (and increase conversion) of the search results CTA.

A PR addressing this issue should:

- [ ] Replace CTA design with a static list of developers blurred out
- [ ] Overlay the copy and button on top of this list

Note that this will probably require a few design iterations. If you're up for it, feel free to give it a shot!

This is blocked on #651.

**Comment by mansakondo** [comment]
I'm up for it.

**Comment by mansakondo** [comment]
How many blurred-out profiles should be on the list?

**Comment by joemasilotti** [comment]
For now, let's do 10 profiles with the CTA hovering over the 2nd and 3rd ones. I think that will fit, size-wise.

I'm still deciding between rendering a static, anonymous profile or using real data but blurred out. If we go the latter then we will need to make sure to remove the URLs in the DOM, too.

If you're up for it, feel free to scaffold some designs that I can play with and make tweaks to!

**Comment by mansakondo** [comment]
if we go with the blurred-out approach we'll also need to handle the avatar, hero, and bio in the DOM.

**Comment by joemasilotti** [comment]
I'm less worried about those, to be honest. Especially if we are only blurring a handful of profiles. But it is definitely worth considering if it makes sense over a generic "loading style" profile card that doesn't have real data at all.

**Comment by izaguirrejoe** [comment]
Hey Joe, did you still want help overlaying the CTA over a list of developers blurred out?

**Comment by joemasilotti** [comment]
Yeah, that would be great! It doesn't even need to be the "real" list of developers, a static image or markup is fine for now.

**Comment by izaguirrejoe** [comment]
Sounds good! I'll take a crack at it.
