### ISSUE TITLE
Redirect `/developers/:id` to `/developers/:hashid`

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#662]
While folks are transitioning to the new developer profile URLs I want to make sure no one's links break.

A PR addressing this issue should:

**When the `:obfuscate_developer_urls` feature is enabled:**

- [ ] 302 redirect `/developers/:id` to `/developers/:hashid` with a flash message
- [ ] Update the sitemap (`config/sitemap.rb:24`) to use the developer's `hashid`

The flash message should read:

> Links to developer profiles have changed. Please update your bookmark to {new developer profile URL}.

**Comment by rayhanw** [comment]
I'd like to give this one a shot 😄

**Comment by joemasilotti** [comment]
Awesome – all yours! Thanks @rayhanw.
