### ISSUE TITLE
Clipboard JavaScript doesn't work in Chrome

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#664]
Copying to the clipboard raises an error in Chrome but works fine in Safari. This issue was discovered when implementing [publicly sharable developer profiles](https://github.com/joemasilotti/railsdevs.com/issues/646#issuecomment-1252773983).

## To reproduce

1. Sign in as an admin (`admin@example.com` + `password`)
1. Visit a developers page
1. Clip the Copy button in the Admin section

## Expected behavior

A rich-text version (HTML) of the developer's name and URL is copied to your clipboard.

## Actual behavior

A JavaScript alert is presented describing an error.

## Screenshots

<img width="484" alt="image" src="https://user-images.githubusercontent.com/2092156/191347948-ee54de92-09e1-4632-ad87-e063f3e4261e.png">

## Additional context

Reproducing the flow in Safari works without issue.

**Comment by ferryphang** [comment]
Please check #666

**Comment by joemasilotti** [comment]
Closed via #666.
