### ISSUE TITLE
Upgrade to Rails 7.0.4

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#682]
RailsDevs is currently running 7.0.3.1 and Rails 7.0.4 was released about a month ago.

A PR addressing this issue should:

- [ ] Upgrade the codebase to Rails 7.0.4
- [ ] Review the [changelog](https://github.com/rails/rails/releases/tag/v7.0.4) and ensure nothing breaks

**Comment by kaushikhande** [comment]
Hi
Can I work on this.

**Comment by joemasilotti** [comment]
Awesome, thanks @kaushikhande!

**Comment by joemasilotti** [comment]
Closed via #684.
