### ISSUE TITLE
Upgrade to Turbo 7.2

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#683]
Turbo 7.2.0 was released two weeks ago and I'd love to get RailsDevs on the latest version.

A PR addressing this issue should:

- [ ] Upgrade to Turbo 7.2.0 (this might require a Gemfile and/or Package.json change(s))
- [ ] Ensure nothing in the [changelog](https://github.com/hotwired/turbo/releases/tag/v7.2.0) breaks anything on RailsDevs
- [ ] Manually go through the Hotwire integrations to ensure no regressions, including:
    - [ ] Sign in/out + registration
    - [ ] Stripe + checkout
    - [ ] Sending messages + keyboard shortcut
    - [ ] Anything else Turbo-related

**Comment by sarvaiyanidhi** [comment]
Hi @joemasilotti .. Can you please assign me this task?

**Comment by joemasilotti** [comment]
Sure thing, all yours!

**Comment by joemasilotti** [comment]
Closed via #696.
