### ISSUE TITLE
Apply homepage redesign

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#693]
This is the first big issue of the Redesign milestone and I imagine will require a lot of work. The good things is that it is all wrapped behind a feature flag so there shouldn't be a lot of merge conflicts.

The new sections include:

- [ ] Hero
- [ ] Testimonials
- [ ] How it works
- [ ] About
- [ ] Collage

I don't think we need a new View Component for each of these, a partial will work fine. But there definitely are elements that could be abstracted. For those, let's prefix them with `Marketing::` to distinguish them from the base UI.

For example, `Marketing::Testimonial` for the green-bordered testimonials and `Marketing::Title` for the title + description used twice. I'm sure more can be abstracted but I'll leave that up to the implementor!

**Comment by jacobdaddario** [comment]
Sliding into the GitHub issues

**Comment by joemasilotti** [comment]
Awesome, thanks Jacob. All yours!
