### ISSUE TITLE
Apply pricing page redesign

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#694]
As in #693, this will live behind the same feature flag so risk of merge conflicts are low. The same approach with regard to View Components applies here.

Sections include:

- [ ] Hero
- [ ] Plan
- [ ] Features
- [ ] Collage
- [ ] Testimonials (we can reuse the View Component here)
- [ ] FAQ
- [ ] CTA

**Comment by jacobdaddario** [comment]
Hopping in the issue thread to claim this.
