### ISSUE TITLE
Add new colors to Lookbook preview

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#707]
The colors added in #701 don't follow standard Tailwind CSS naming conventions. They use "-lighter" and "-dark" suffixes vs. "-100" or "-900". I want to add these colors as a reference to a Lookbook page to make it easy for folks to know which colors are which. (Without having to read the Tailwind configuration.)

<img width="860" alt="image" src="https://user-images.githubusercontent.com/2092156/197077198-e208fe42-28c5-41e1-a9c9-8c8775374ff6.png">

This is currently blocked by #624.

**Comment by faqndo97** [comment]
@joemasilotti Do you want me to tackle this one too?

**Comment by joemasilotti** [comment]
That would be great, thank you!

This will be a new namespace, UI or Design, outside of Admin.
