### ISSUE TITLE
Remove `:redesign` feature flag

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#715]
Once all the code has been merged in and the redesign is enabled the branching logic needs to be removed.

A PR addressing this issue should:

- [ ] Remove all code paths related to `Feature.enabled?(:redesign)`
- [ ] Remove non-`:redesign` request variants

**Comment by creaturenex** [comment]
Hello Joe,

I would like to give this a shot. Just let me know when the redesign and merge are complete. Ill subscribed to be notified but not sure which issue to track

**Comment by joemasilotti** [comment]
Awesome! Thanks for the offer, @creaturenex. It might be a while but you have first dibs. Keep watching this issue and I'll @ you when it's ready.
