### ISSUE TITLE
Cells without `href`s are still linked on `/admin/transactions`

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#722]
1. Sign in as an admin (`admin@example.com` + `password`)
2. Visit `/admin/transactions`
3. Add a transaction _without a URL_

Note that the description is still linked even though there is no destination URL.

A fix should check if a URL is present before rendering a link, on `app/views/admin/transactions/index.html.erb:25`.

**Comment by kaushikhande** [comment]
Hi Joe
I would like to work on this issue.

**Comment by joemasilotti** [comment]
Closed via #723.
