### ISSUE TITLE
Save referral code to `User` when registering for an account

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#727]
Kicking off the referral program MVP is knowing which users were referred by which code.

A PR addressing this issue should:

- [x] On every request check for the `ref` URL param
- [x] If present, set a cookie that expires in 30 days
- [x] When registering a new account persist this code to the `Referral` model

**Comment by ferryphang** [comment]
I'm up for it

**Comment by joemasilotti** [comment]
Hey @ferryphang. I'm still ironing out all the details for this milestone. I'll comment again here when it's ready to be picked up!
