### ISSUE TITLE
Remove old feature flags

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#732]
> Note: This issue is reserved for the [OS Hackathon](https://www.meetup.com/portland-ruby-brigade/events/290481353/) on Saturday, February 4 in Portland, OR. You are welcome to join in person or remotely!

Remove the following feature flags and all related code from the codebase, including tests:

- [ ] `:paywalled_search_results`
- [ ] `:redirect_db_id_profiles`

**Comment by inveterateliterate** [comment]
@joemasilotti  I would like to tackle this one today!

**Comment by joemasilotti** [comment]
All yours – thank you! Feel free to comment here or DM me on Slack if you have questions. :)
