### ISSUE TITLE
Rework modeling of referral program

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#736]
RailsDevs has a very basic referral program. Folks refer businesses to the site and 10% of any generated revenue is shared with the referrer. This includes monthly fees _and_ hiring fees.

Currently, I manually create a 6 character referral code for each person. Then they can apply that to URLs to get credit for a referral, e.g. `https://railsdevs.com?ref=ABCDEF`.

As it stands we can't associate a `Referral` record with a user. Which will make #728 a bit more difficult.

Let's rework some of the modeling to better match this diagram.

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/2092156/204567520-f301f721-bd89-45b2-888e-d6d6ce228a13.png">

In text, this means that a `Referral` is still created when someone signs up with a `ref` URL param present. The `code` is still stored on the `Referral` model.

But while creating this record we should also check to see if the code matches any existing `ReferralCode` records. If so, associate them together.

`ReferralCode` records belong to a `User` and have a `code` string as well. This string cannot be changed. For now we can create the code manually in the database (e.g. no UI).

Note that a referral can occur without a `ReferralCode` or associated referrer. This means the relationship from `Referral` to `ReferralCode` is optional.

When creating a new `ReferralCode` we _might_ also want to see if any existing `Referral` objects need to be associated with it. But let's skip this for now – I can handle it manually as the program gets going. And I'd rather not have that code exist after it needs to.

**Comment by PatrickMcSweeny** [comment]
Claiming this issue as it needs to be completed before #729

**Comment by joemasilotti** [comment]
Thanks! All yours.
