### ISSUE TITLE
`NoMethodError` in `developers#index`

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#738]
Honeybadger exception report: https://app.honeybadger.io/fault/93997/9178e06d3ad290d589912c6bce7eb712

URL visited: https://railsdevs.com/developers?countries%5b%5d=United+Kingdom&role_levels%5b%5d=mid%27&role_types%5b%5d=part_time_contract&role_types%5b%5d=full_time_contract

**Comment by kaushikhande** [comment]
@joemasilotti Can I look into this?

**Comment by joemasilotti** [comment]
Yes, please! Thanks @kaushikhande.

**Comment by troyizzle** [comment]
Is it possible to pick this up?
