### ISSUE TITLE
Admins viewing conversations with a deleted developer raise an error

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#747]
## Describe the bug

Folks on RailsDevs are able to delete their account. If you view a conversation with that person the `User` is nil and it raises an error.

## To reproduce

1. Reseed your local database via `bin/rails db:seed`
2. Delete the first developer in the console via `Developer.first.destroy`
3. Sign in as an admin via `admin@example.com` and `password`
4. View a conversation including that developer from the admin dropdown
 
## Expected behavior

The business's conversations and individual conversation appear without issue.

## Actual behavior

[An exception is raised](https://app.honeybadger.io/fault/93997/18b7f61b0e6f84863bc85a2fc3660c02).

## Additional context

Two ways we could potentially fix this issue:

1. Cascading deletions for the user and deleting all of their conversations, like notifications.
2. Making the `User` a "tombstone" and showing "Deleted account" with a generic avatar for the conversations.

I'm open to either depending on your appetite!

**Comment by W3NDO** [comment]
Hi @joemasilotti I'm interested in tackling this issue using the tombstone approach.

**Comment by joemasilotti** [comment]
Excellent! All yours.

**Comment by troyizzle** [comment]
Could I pick this up if available?

**Comment by joemasilotti** [comment]
@W3NDO, do you still have appetite to fix this issue? If not I will pass it along to @troyizzle.

**Comment by W3NDO** [comment]
@joemasilotti I think it would be best to pass it along. I was unable to find time to work on it. I apologize.

**Comment by joemasilotti** [comment]
All yours @troyizzle!
