### ISSUE TITLE
High response rate badge

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#757]
Another way to help developers stand out on the platform is to highlight their response rate. Businesses are more inclined to reach out to someone who responds to every message than someone who doesn't.

I'm defining "response rate" as the number of conversations a developer has responded (at all) divided by the total number of conversations a developer is participating in.

A PR addressing this issue should:

- [ ] Add a badge to developer profiles if their response rate is over 90%
- [ ] Replace that badge with a different one if their response rate is a perfect 100%
- [ ] If needed, ensure the badge status is cached efficiently with no N+1 queries
- [ ] Stretch goal: Give developers 6 hours to respond to a new message before _dropping or removing_ their badge

For the badges, please use the following design/copy for a first pass.

* `90% response rate` in indigo
* `100% response rate` in purple

**Comment by fig** [comment]
This looks interesting. 
I have reservations over the "6 hour" time limit for dropping response rate. (Most doctors recommend 8 hours sleep!)
How about a sub-text or hover bubble with "This developer usually responds within x hours"?
