### ISSUE TITLE
Cache developer badges to a new model

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#758]
Developers can now have up to two badged on their profile and more are coming soon. Before we add anything new I'd like a single place to reference and cache the existing ones.

A PR addressing this issue should:

- [ ] Create a new `Developers::Badge` model and table
- [ ] Cache the "recently active" status to this new model
- [ ] Ensure the status is updated when appropriate
- [ ] Migrate `developers.source_contributor` to the new table
- [ ] Ensure the admin form works with the new modeling

**Comment by troyizzle** [comment]
I'd like to take this on!

**Comment by joemasilotti** [comment]
All yours! Thank you!

**Comment by troyizzle** [comment]
Couple questions,

I'm thinking it would be creating a table like this
 ```
    create_table :developers_badges do |t|
      t.belongs_to :developer
      t.boolean :recently_active, null: false, defualt: false
      t.boolean :source_contributor, null: false, default: false
      t.timestamps
    end
```

Backfill the data, should this been done through a lib task?
```
Developer.all.find_each do |developer|
  developer.badge.create!(
    recently_active: developer.recently_active?
    source_contributor: developer.source_contribuitor?
  )
end
```

For updating the data, I was thinking of a cron job on a set period of time
```
Developer
  .joins(:developer_badge)
  .where(updated_at: >= Developer::RECENTLY_ACTIVE_LENGTH.ago)
  .update_all(recently_active: false)
```
Also would need to update them to be active, so I was thinking of maybe on `ApplicationController` updating it

Some sudo code but would like to get your feedback!

**Comment by joemasilotti** [comment]
The table looks good to me. And I imagine we will need to add/update more fields in the future so the cron job also sounds like a good idea.

The backfill can live in the dedicated backfill task. And the cron job can be a different task perhaps - not sure the best spot for that yet. I think the job can be run once per day and still get us what we want.

I know it is pseudo code, but we also want to make sure we are updating the recently active field to `true` when necessary. This PR should ensure that those calls are in place if they aren't already.

---

We will also probably need to split this into 2 PRs. One to add the migrations and migrate the data. And a second to switch over to the new code path. Otherwise we might deploy without the data being backfilled yet.

**Comment by joemasilotti** [comment]
Doing some Spring cleaning and this issue is pretty stale. I'm going to close it out for now. But feel free to open a PR if you have something ready!
