### ISSUE TITLE
Filter by developer badges

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#759]
Developers can now have up to two badges on their profile: recently active and source contributor. It makes sense to be able to filter by these when searching.

A PR addressing this issue should:

- [ ] Add a new filter option with a checkbox for each badge

The new filter option should be placed in between the search and role level filters and match the UI and UX of the other checkboxes. It should initially be expanded.

Two implementation details to watch out for:

* Make sure the filtering works across desktop and mobile.
* Make sure clicking the label toggles the associated checkbox on desktop and mobile.

Also, I'm not interested in caching the recently active status. This will occur in #758.

**Comment by sarvaiyanidhi** [comment]
Hi @joemasilotti I would like to work on this feature... Can you please assign it to me?

**Comment by joemasilotti** [comment]
Sure thing - thank you!

**Comment by joemasilotti** [comment]
Closed via #763.
