### ISSUE TITLE
Flow for businesses to notify RailsDevs when they make a hire

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#764]
Developers can fill out the [celebration package form](https://railsdevs.com/hired) when they get hired via RailsDevs. This helps me kick off conversations with businesses to collect the hiring fee. I'd like to add a similar form for businesses to inform me when they hire someone.

A PR addressing this issue should:

- [ ] Add a "Made a hire?" link to the nav bar
- [ ] Clicking the link shows a form that looks like `/hired/forms/new`

The link should be styled like the "Found a job?" link for developers and only appear when the active account has a business profile. If the active account has both a developer _and_ business profile then show both, "Found a job?" first.

The form should render at `/hire/forms/new` and follow the same models, tables, and design as `/hired/forms/new` but updated for the new namespace. The backing model/table should `belong_to` a business and the controller should redirect if the active account doesn't have a business profile (just like the developer form).

Successfully submitting the form should trigger an email to admins and appear in `/admin/hire/forms`, mimicking `/admin/hired/forms`.

The form should have the following copy and fields:

### Did you hire someone via RailsDevs?

Congratulations! Fill out these details and Joe will send you info on next steps.

* Billing address - text
* Developer name - string
* Position - string
* Start date - date
* Annual salary - integer
* Employment type - dropdown (freelance or contract, full time employment)
* Feedback (optional) - text

**Comment by RomanTurner** [comment]
Let me at 'em!

**Comment by joemasilotti** [comment]
All yours, thanks Roman!

**Comment by MikeRayUX** [comment]
Hey guys! Happy to push this one forward!

**Comment by joemasilotti** [comment]
Closed via #775 and #818.
