### ISSUE TITLE
Automate business welcome email

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#765]
When a developer signs up an automated email is sent welcoming them to the platform. I'd like to do the same for businesses.

A PR addressing this issue should:

- [ ] Send an email to the user when they create their business profile

The subject and body of the email should be as follows, ensuring HTML + plain text versions:

Subject: Welcome to RailsDevs 👋

Hey [first name],

I'm Joe, the founder of RailsDevs - the *reverse* job board for Ruby on Rails developers. Welcome!

The platform is a bit different than traditional job boards. Instead of posting a job description, you [browse developer profiles](/developers) to find a perfect match.

When you see a good fit click the Hire button. Your message goes right to their email inbox.

**This approach has a ~60% response rate and can dramatically shorten the hiring process.** I’ve seen offers made in as little as 2 weeks.

What are you looking for in your next hire? I’ll send over some folks who could be a good fit.

[signature]

**Comment by accua** [comment]
@joemasilotti I'll take this one!

**Comment by joemasilotti** [comment]
Thanks @accua, all yours!

**Comment by joemasilotti** [comment]
Closed via #756.
