### ISSUE TITLE
Automate subscriber welcome email

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#766]
I'd like to send a welcome email when a business becomes a paying customer.

A PR addressing this issue should:

- [ ] Send an email to the user when they subscribe to a paid plan

The subject and body of the email should be as follows, ensuring HTML + plain text versions:

Subject: Your RailsDevs subscription is live! 🎉 Let’s find your perfect match.

Hey [first name],

It’s Joe again, the founder of RailsDevs. Your subscription is live and you can message all [developer count]+ Rails developers on the platform.

**Get started by adding a filter or two when [browsing developer profiles](/developers).** Start with role level and work preference then try adding a specific term or technology.

When you see a good fit click the **Hire** button. Your message goes right to their email inbox.

Hit reply or [schedule a call](https://savvycal.com/joemasilotti/RailsDevs) if you’d like help narrowing down your search!

And thank you for your support in my bootstrapped, independent business.

[signature]

P.S. Where did you first hear about RailsDevs?

**Comment by duncantmiller** [comment]
I can work on this one

**Comment by joemasilotti** [comment]
Awesome! All yours Duncan.

**Comment by joemasilotti** [comment]
Hey @duncantmiller, do you still have appetite to finish this? Let me know if you need help getting it over the finish line!

**Comment by duncantmiller** [comment]
Hi @joemasilotti yes I'm still interested in trying to get it done. I have been messaging with Andrew trying to find a time to get together and work on both of our PRs together. We are trying again this week but I'll plan to try to work on it again soon either way and let you know if I need a hand.

**Comment by joemasilotti** [comment]
Closed via #766.
