### ISSUE TITLE
Automate subscription renewal email

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#767]
> ~Note: This issue is blocked by #764.~ This issue is no longer blocked!

I'd like to send an email to businesses a few days before their subscription renews. This is a great time to ask if they've hired anyone and could create some goodwill by letting them know before they accidentally renew.

A PR addressing this issue should:

- [ ] Send an email to subscribed users 3 days before their subscription renews

The subject and body of the email should be as follows, ensuring HTML + plain text versions:

Subject: Your RailsDevs subscription renews in 3 days. Have you made a hire?

Hey [first name],

Joe, founder of RailsDevs here. A quick reminder that your subscription will renew on [renewal date].

Already hired someone? Congratulations! [Fill out this form](/hire/forms/new) and I’ll send you info on next steps.

If you’re still looking then hit reply or [schedule a call](https://savvycal.com/joemasilotti/RailsDevs) and I’ll help find a new batch of candidates.

[signature]

**Comment by PatrickMcSweeny** [comment]
@joemasilotti I could work on this one

**Comment by joemasilotti** [comment]
Thanks @PatrickMcSweeny! This is currently blocked by #764 which I believe @RomanTurner is working on. Once that is merged you can pick this one up.

**Comment by jkostolansky** [comment]
Is this open? I could take a look.

**Comment by joemasilotti** [comment]
Sure thing, thanks!

**Comment by jkostolansky** [comment]
The link for "Fill out this form" seems to be wrong, can you post the correct one?

Do you have any preference how should the scheduling thing work? I can use something like [`sidekiq-cron`](https://github.com/sidekiq-cron/sidekiq-cron) gem (or any other cron-like solution) and check every day at a specific time which businesses to contact.

Or should I schedule a job for each subscribed business using `wait_until`? (I personally don't like using sidekiq jobs scheduled in the far future.)

**Comment by joemasilotti** [comment]
The URL for "Fill out this form" is `new_businesses_hiring_invoice_request_url`.

I was hoping we could hook into the Pay web hook workflow but I'm not sure if that is possible with the "3 days" logic. A daily rake task like you proposed sounds great.

That logic also looks correct to me, making sure to account for "3 days" as the entire 24 hour range. Ideally the script could be idempotent per month, but if that adds a lot of complexity then only running the task once per day should be fine for now.

**Comment by joemasilotti** [comment]
Ohh, perfect! I just confirmed that `invoice.upcoming` is indeed being processed. And changed the event to fire 3 days before renewal.

**Comment by jkostolansky** [comment]
Great!

> Pay is only sending emails for annual subscriptions

That's true, but you can enable that for monthly subscriptions in the config, too.

Ok, I will try something.

**Comment by joemasilotti** [comment]
Ah, gotcha! TIL.
