### ISSUE TITLE
Upgrade to Devise v4.9.0

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#786]
Devise recently released [v4.9.0](https://github.com/heartcombo/devise/blob/v4.9.0/CHANGELOG.md) with built-in support for Turbo and Hotwire. I'd like to upgrade to this release and remove the workarounds in place.

A PR addressing this issue should:
- [ ] Update Devise to v4.9.0
- [ ] Remove any Devise-specific workarounds for Turbo
- [ ] Ensure signing in/out still works
- [ ] Ensure the Turbo Native mobile app still works

I will take care of the Turbo Native stuff once a PR is ready for review.

**Comment by sarvaiyanidhi** [comment]
Hi @joemasilotti I would like to work on this issue.. Can you please assign it to me?

**Comment by joemasilotti** [comment]
Sure thing - all yours!

**Comment by joemasilotti** [comment]
Closed via #793.
