### ISSUE TITLE
Add an assertion to the first_message test in the developer mailer spec file

### ISSUE THREAD

**Issue by accua** [joemasilotti/railsdevs.com#788]
## Describe the bug

On line 16 in the `DeveloperMailerTest` file, the test isn't actually making an assertion.

## To reproduce

1. run `rails test test/mailers/developer_mailer_test.rb:16`

## Expected behavior

The spec passes with an assertion

## Actual behavior

Notice that the spec doesn't fail, but also doesn't show an assertion.

## Screenshots
<img width="857" alt="Screen Shot 2023-02-26 at 6 52 15 PM" src="https://user-images.githubusercontent.com/22631623/221462017-e218a55d-0eb8-4170-ac63-8add674c8180.png">

**Comment by joemasilotti** [comment]
Closing this as this file will be deleted. Thanks for documenting!
