### ISSUE TITLE
Option to hide certain notifications from the UI

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#789]
`Developers::WelcomeNotification` and `Businesses::WelcomeNotification` only exist to trigger an email. I'd like to hide these from showing up as notifications in the dropdown and `/notifications`.

A PR addressing this issue should _either_:
- [ ] Add a flag to `notifications` to show in the UI or not; respect flag when viewing notifications
- [ ] Create a system/approach to sending emails

I might be overthinking it, the second one might be ripping out a lot of code. The choice is yours!

**Comment by gathuku** [comment]
@joemasilotti can I help on this?

**Comment by ryy** [comment]
Is there a way to not insert records into the notifications table?

https://github.com/joemasilotti/railsdevs.com/blob/7919b3f3d538c3d139363aa29888ec6d24907b72/app/notifications/developers/welcome_notification.rb#L3

**Comment by gathuku** [comment]
> records into the notification

🤔  looks hard because the mailer would want to use that record.

**Comment by joemasilotti** [comment]
We still need to write the notification to the database. Without it, we [wouldn't be able to send an email](https://github.com/excid3/noticed/blob/master/docs/delivery_methods/database.md).

I tried playing with the `format: :format_for_database` option (same link) but couldn't get it to work. Ideally, we have a module, `InvisibleNotification` or something, that we can include which does all of the "hiding" for us. Then the views only show visible/non-hidden ones with a scope.

Or, I'm overthinking it entirely and we should skip Noticed and go right to a mailer!

**Comment by joemasilotti** [comment]
I posted [a question on the Noticed Discussions board](https://github.com/excid3/noticed/discussions/273) to see what the maintainers think.

**Comment by joemasilotti** [comment]
@excid3, maintainer of Noticed, recommended removing the database delivery.

So, let's do that! It seems to get us exactly what we want.

@gathuku, would you like to take a pass? I think this should be as straightforward as removing the `deliver_via :database` line from the welcome notifications for businesses and developers.

**Comment by gathuku** [comment]
> @excid3, maintainer of Noticed, recommended removing the database delivery.
> 
> So, let's do that! It seems to get us exactly what we want.
> 
> @gathuku, would you like to take a pass? I think this should be as straightforward as removing the `deliver_via :database` line from the welcome notifications for businesses and developers.

@joemasilotti I will have a look at it.
