### ISSUE TITLE
500 Error when clicking on Notifications Icon

### ISSUE THREAD

**Issue by cnorm35** [joemasilotti/railsdevs.com#792]
## Describe the bug

Clicking on the notifications bell as a logged in User returns a 500 error page

## To reproduce

1. Go to railsdevs.com
2. Ensure there are un-read or new notifications
3. Click on the icon for notifications
(See Screenshot)

4. See error "Something went wrong"
(See Screenshot)

## Expected behavior

Should be able to view notifications

## Actual behavior

500 error when navigating to https://railsdevs.com/notifications as a logged in User with new notifications

## Screenshots
![Screen Shot 2023-03-01 at 12 28 01 PM](https://user-images.githubusercontent.com/4549543/222244517-5dd08f08-b9f3-4a53-82f6-a8456b8abadf.png)

![Screen Shot 2023-03-01 at 12 30 36 PM](https://user-images.githubusercontent.com/4549543/222244806-56d6b5cc-ca91-4361-b167-d6358f3faec3.png)

**Comment by joemasilotti** [comment]
Thanks for reporting! I forgot to delete some old notification records.

Can you please try again and see if it is working now?

**Comment by cnorm35** [comment]
Thanks @joemasilotti, that did it!  Got a local version running on my end and didn't see any issues or errors with notifications so everything looks good now.

**Comment by joemasilotti** [comment]
Excellent! Thanks again for reporting.
