### ISSUE TITLE
Automate subscriber cancellation email - $25 bounty

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#795]
> Note: This issue is blocked by #764.

I'd like to send a welcome email when a business cancels their subscription.

A PR addressing this issue should:

- [ ] Send an email to the user when they cancel a paid plan

The code can hopefully be modeled after #794 but with a different enum result from `Pay::SubscriptionChange`. The subject and body of the email should be as follows, ensuring HTML + plain text versions:

Subject: RailsDevs cancellation confirmation

Hey [first name],

Your subscription to RailsDevs is cancelled. Your access to the site will be available until the end of your billing period.

Were you able to hire someone? [Fill out this form](/hire/forms/new) and I’ll send you info on next steps.

A friendly reminder that according to the signed [hiring agreement](/hiring_agreement/terms) you must notify RailsDevs that you have hired someone no later than the developer's first day of employment.

[signature]

**Comment by sarvaiyanidhi** [comment]
Hi.. I can work on this. Can you please assign it to me?

**Comment by joemasilotti** [comment]
I'd love for you to work on this! I'll assign it over to you.

Please keep in mind that it is blocked by #764 which @RomanTurner is still wrapping up.

But we can merge in your changes behind a feature flag until the route is created. Feel free to throw a route `routes.rb` so we can use the helper in the mailer.

**Comment by joemasilotti** [comment]
Also, this issue has a $25 bounty. Once merged let please send me an email so I can send you money!

**Comment by sarvaiyanidhi** [comment]
Thanks.. Will keep an eye on #764 and meanwhile proceed with changes with feature flag.
