### ISSUE TITLE
Add a tooltip to the headers on the admin conversations dashboard - $25 bounty

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#796]
The admin conversations dashboard lets admins keep up with ongoing conversations happening between businesses and developers.

It's not very obvious what two columns, REPLIED? and EMAIL?, mean.

A PR addressing this issue should:

- [ ] Add a `title` HTML attribute to the two headers explaining what they do.

The HTML `title` attribute appears as a tooltip when hovering the element. Use the following titles:

* REPLIED? - The developer has replied to this conversation.
* EMAIL? - The developer mentioned an email address in a reply.

This will most likely require changing the `Admin::Tables::HeaderComponent` View Component to accept a new attribute to be rendered. 

![image](https://user-images.githubusercontent.com/2092156/223533306-88235ad2-d89e-4525-8e5d-a511a13ec436.png)

**Comment by franlocus** [comment]
Hi Joe! It would be awesome if I could work on this :)

**Comment by joemasilotti** [comment]
Sure thing! All yours @franlocus. Don’t hesitate to reach out if you need help or an early review.

**Comment by joemasilotti** [comment]
Closed via #797.
