### ISSUE TITLE
Refactor `DeveloperQuery` to be closed for modification

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#805]
`DeveloperQuery` is becoming increasingly more difficult to work with. There is a _lot_ of logic in that class.

I'd like to refactor it to to receive an array of `QueryItem` objects. This way, each query item can handle its own scoping, sorting, and filtering. This should make it easier to extend in the future when new query options are required, like #803.

**Comment by soumyashree25** [comment]
@joemasilotti can I take this issue one ? Although I have not much context at this moment, happy to spend some time to understand the flow.

**Comment by sarvaiyanidhi** [comment]
I would like to give this a shot if it is still open later.

**Comment by joemasilotti** [comment]
Hey @soumyashree25, want to take a look and see if you would like to commit? The class is pretty gnarly and might be hard to wrap your head around if you are new to the project.

Let me know either way!

**Comment by soumyashree25** [comment]
@joemasilotti I would like to work on this, let's see how it goes.

**Comment by viktorvsk** [comment]
Did you consider using [ransack](https://activerecord-hackery.github.io/ransack/#demo-application) ?

**Comment by joemasilotti** [comment]
How will ransack help us here? I've only heard of the gem but haven't used it.

**Comment by joemasilotti** [comment]
Oh! That looks super interesting, thanks for sharing.

One issue we are tackling in the PR is making sure the individual query items aren't exposed. But we still need a way to render the filters in the form.

Any ideas on how Ransack could help with that?

**Comment by viktorvsk** [comment]
If I understand correctly, by "individual query" you mean this:

```ruby
def role_type_filter_records
  @_records.merge!(Developer.filter_by_role_types(role_types)) if role_types.any?
end
```

that:

```ruby
def role_level_filter_records
  @_records.merge!(Developer.filter_by_role_levels(role_levels)) if role_levels.any?
end
```

and similar ?

With ransack you won't have them at all, instead you will declaratively change names of your form's inputs to construct desired SQL query.

Regarding the filters to construct the form, as far as I understand, your form currently is located in `components/developers/query_component.html.erb`. And this is how you render the form:


```ERB
<%= form.collection_check_boxes(:role_types, role_types, :first, :last, {include_hidden: false}) do |b| %>
  <div class="flex items-center">
    <%= b.check_box checked: role_type_selected?(b.object), class: "h-4 w-4 border-gray-300 rounded text-gray-600 focus:ring-gray-500" %>
    <%= b.label class: "ml-3 text-gray-500 text-sm" %>
  </div>
<% end %>
```


With ransack the only thing you have to change In the view component is inputs name:

```diff
- <%= form.collection_check_boxes(:role_types, ... %>
+ <%= form.collection_check_boxes(:role_types_match_any, ... %>
```

In some cases maybe some virtual methods will be required in models but usually its only needed for advanced use cases

**Comment by joemasilotti** [comment]
Thanks @viktorvsk! That seems to solve a lot of the problems this issue was initially looking to fix.

Do you have appetite to take a pass with implementing one or two filters with Ransack?

**Comment by viktorvsk** [comment]
Hey @joemasilotti please take a look at https://github.com/joemasilotti/railsdevs.com/pull/852
There is an illustration of how could it be. If you like such approach, let me know and I can polish it

**Comment by joemasilotti** [comment]
Great, thank you! I'll take a look soon.
