### ISSUE TITLE
Archive conversations

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#806]
The conversations index page can get overwhelming after you've had a lot of contact with folks. I'd like a way to make it easier to follow a few important threads without getting bogged down by the rest.

A PR addressing this issue should:

- [ ] Add an Archive button to every conversation
- [ ] When clicked, remove the conversation from `/conversations`
- [ ] If any conversations are archived, add a link to the bottom labeled "Archived conversations"
- [ ] When clicking this link, visit `/conversations/archived` and show the archived ones
- [ ] Each conversation on this screen should have a Unarchive button that moves it back to `/conversations`

**Comment by JuzerShakir** [comment]
I would like to try this out!

**Comment by vinhmai570** [comment]
Hi Joe. Can I receive this issue?

**Comment by joemasilotti** [comment]
@JuzerShakir, you commented first so this is all yours!

**Comment by JuzerShakir** [comment]
**Here's the status of this issue till now:**
[Screencast from 17-03-23 07:43:28 PM IST.webm](https://user-images.githubusercontent.com/10782481/225930374-4469917c-c62a-4795-94cb-3f21948e4ea6.webm)

I believe I have achieved all the tasks mentioned in this Issue! Hurray! 

But it actually doesn't work as expected as you can see in the video! I created `archived?` attribute as a boolean in the `conversation` table to achieve this task. But there's a flow with this logic as I released just now.

As conversations involve 2 users, so if a user sets a conversation as archived then the other side of the users' conversation is also set as `archived`. So when a message is received by a user then that conversation is in the `/archived`.

I have been about the solution but I am not understanding how should I resolve this. The only way I think is I need to undo all changes and redo them again. I spent hours on this only to know that this logic is not worth it. I need help @joemasilotti, what should I do?

**Comment by joemasilotti** [comment]
This is looking good! I'll probably tweak the design of the button but the flow looks great.

I think we will need to have two fields on `Conversation`. Look at the schema and note how we use `developer_blocked_at` and `business_blocked_at`. Let's model this the same way: `developer_archived_at` and `business_archived_at`.

You could also look at `BlocksController` to see how we update the correct field.

**Comment by JuzerShakir** [comment]
Yes! That's a nice idea! The `developer_blocket_at` & `business_blocked_at` are `datetime` type fields whose values are by default `nil` but when they're `touch`ed in the controller then their value is updated with the current timestamp!

Following this logic, I can create attributes `developer_archived?` & `business_archived?` as boolean types for which their default values will be `false`, and when they'll see the message I can use the `toggle` method to switch its values between `false` to `true` & vice-versa.

Thoughts?

**Comment by joemasilotti** [comment]
I prefer the timestamp approach. That gives a tad more flexibility when we want to sort the conversations by when they were archived.

**Comment by JuzerShakir** [comment]
[Screencast from 18-03-23 06:06:57 PM IST.webm](https://user-images.githubusercontent.com/10782481/226106575-c5873a36-1a49-497b-8cbb-34b63fd2e632.webm)

Well, with that logic everything seems to be working perfectly fine! 🥳 

I also had to add new logic in the `MessageController` in order for the receiver to see the conversation in the `/conversation` if he received a new message for it.

**Comment by joemasilotti** [comment]
Great! I'm not sure I follow your comment about `MessageController` but that's alright. Please submit your PR whenever it is ready and I can give it a review.

**Comment by JuzerShakir** [comment]
I have created the [Pull Request ](https://github.com/joemasilotti/railsdevs.com/pull/813) and all tests pass. 🥳

**Comment by joemasilotti** [comment]
Excellent! I'll take a look as soon as I can and offer feedback.

**Comment by joemasilotti** [comment]
Blocked until #843 is released. See [this comment](https://github.com/joemasilotti/railsdevs.com/pull/813#issuecomment-1484154240) for more details.
