### ISSUE TITLE
Tab order and autofocus on sign in + registration screens

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#812]
I noticed today that the the sign in and registration screens don't have some common UX affordances. I'd like to fix that.

A PR addressing this issue should:

- [ ] Set the tab order on the sign in screen to email then password _then_ forgot password
- [ ] Set the tab order on the registration screen to email then password then password confirmation (if it isn't already)
- [ ] Autofocus on the email field for both of these forms

**Comment by JuzerShakir** [comment]
I would like to try this out!

**Comment by joemasilotti** [comment]
Thanks for the offer! But I'd prefer if folks only had one outstanding issue at a time. You are welcome to start work on this once #806 is complete and if no one else has claimed it.

**Comment by aj-abhishek-jadav** [comment]
@joemasilotti Can i have a go for this?

**Comment by joemasilotti** [comment]
Sure thing! All yours @aj-abhishek-jadav.

**Comment by aj-abhishek-jadav** [comment]
Thanks @joemasilotti  for giving me opportunity 👍

**Comment by JuzerShakir** [comment]
All the best @aj-abhishek-jadav 👍

**Comment by aj-abhishek-jadav** [comment]
Hi @joemasilotti,
- shall i add autofocus on Forgot Password page's **email** field
   <img width="662" alt="image" src="https://user-images.githubusercontent.com/36496890/226114241-7c506602-0955-452a-9871-43f36e24d34d.png">
- And on Resend Confirmation Instruction Page
  <img width="507" alt="image" src="https://user-images.githubusercontent.com/36496890/226114305-b7ee6ed8-22a9-45ce-907e-d827cb4304da.png">

**Comment by joemasilotti** [comment]
Yes please to both!

**Comment by joemasilotti** [comment]
Closed via #816.
