### ISSUE TITLE
Ensure text search also searches specialties

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#814]
Developer specialties, launched today #803, gives developers an official way of letting businesses know what they are interested in. This isn't enabled in production yet, though.

I'm planning on allowing developers to add their specialties for a few weeks before opening up filtering to businesses. To help ease the transition, I'd like to make sure the text search also searches specialties.

A PR addressing this issue should:

- [ ] With a paid business plan, when searching by text on `/developers`, include developers who have specialties with the same name

For example, if I search for "hotwire" I should see profiles that mention "hotwire" in their hero and/or bio and if they have the "hotwire" specialty selected.

**Comment by nnahgodspower122** [comment]
hi @joemasilotti   I can take on this task

**Comment by joemasilotti** [comment]
Excellent! All yours @nnahgodspower122. Let me know if you run into any issues or have questions. I'm thinking we will need to modify the `pg_search` query and index on `Developer` but maybe not.

I'll reach back out in 2 weeks if I haven't heard from you.

**Comment by nnahgodspower122** [comment]
Thanks @joemasilotti would leave a comment here if I have any questions

**Comment by nnahgodspower122** [comment]
hi @joemasilotti please see attached video if this is the expectation for this issue

https://user-images.githubusercontent.com/94062261/226338421-2be39911-d608-4743-91c9-b60cc917a8fb.mp4

**Comment by joemasilotti** [comment]
That is looking good! Is the text input still searching developer hero/bio fields, too?

**Comment by nnahgodspower122** [comment]
yes it still searches for developer hero/bio

**Comment by joemasilotti** [comment]
Excellent! Please submit a PR whenever the code is ready for review.

**Comment by joemasilotti** [comment]
Closed via #823.
