### ISSUE TITLE
Client-side validation for specialties

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#815]
Developers are limited to 5 specialties. I think it would be helpful if someone knew that when selecting their 6th before submitting the form.

A PR addressing this issue should:

- [ ] Add an error field to "specialties" when a developer clicks their 6th (or more) item

Note that there is already a model-level validation. Ideally, we can use that to determine how many specialties can be selected.

**Comment by Aaryanpal** [comment]
@joemasilotti i can u assign this to me.I love to give it a shot

**Comment by joemasilotti** [comment]
You got it! Let me know if you run into any issues or have questions. I’ll reach back out in a week or so if I don’t hear from you.

**Comment by Aaryanpal** [comment]
@joemasilotti what should be the error displaying. Any Specific Quote or i matched with the same as the model validation one.

**Comment by joemasilotti** [comment]
Ideally the error message and styling is pulled directly from the existing code.

**Comment by ShanizNyawira** [comment]
@joemasilotti I would also love to help working on this

**Comment by joemasilotti** [comment]
How goes progress, @Aaryanpal?

**Comment by joemasilotti** [comment]
Closing this out as it has become quite stale. Feel free to open a PR if you already have code that is ready to merge.
