### ISSUE TITLE
Announce specialties to developers

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#817]
Before opening up filtering to businesses, I want to get a bunch of devs to add their specialties.

A PR addressing this issue should:

- [ ] Add a new mailer to `DeveloperMailer` for feature announcements
- [ ] Add a rake task that sends the email to all developers who are _not_ marked as invisible or "not currently interested"
- [ ] Add a new checkbox to the developer form asking if folks want to opt-in to product updates

The email should come from `updates@` on the updates inbox (see `config/emails.yml`) and uses the message stream broadcast. It should also include a link to ubsubscribe that links to the bottom of their developer profile edit page (see profile reminder email).

The checkbox requires a new column in the database and should default to enabled.

**Comment by sarvaiyanidhi** [comment]
I would like to take up this issue.. can you please assign it to me?

**Comment by joemasilotti** [comment]
Sure thing, all yours!

**Comment by sarvaiyanidhi** [comment]
I was just thinking through this feature and was trying to see how to make it more customized for future.

As suggested in issue, I can create rake task which will fetch developers to send product update mail but on giving second thought it will definitely happen in future where we need to send more product feature updates to developers who opted for it.

So, I was thinking if it will be good idea to add in Admin section one screen, which will define content for feature update mail and button to trigger mail to send to developers.

Though not a big thing but it will avoid to deploy changes in code base every time if product needs to send some feature updates to developers and can be done through Admin.

**Comment by sarvaiyanidhi** [comment]
Sure. Thank you for the reply. Will work as per original specs and push code soon.

**Comment by joemasilotti** [comment]
Closed via #825.
