### ISSUE TITLE
Schedule a call link

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#832]
Most, if not all, of successful placements include a live call of some sorts.

But the conversation UI is pretty terrible at trying to coordinate a time that works for both parties.

<img width="668" alt="image" src="https://user-images.githubusercontent.com/2092156/227365735-cee0d86e-693a-41fc-a29f-e692c8a1f0e5.png">

I'd love a one-click "Schedule a meeting" button for businesses to help streamline this process.

And no, I don't want to rebuilt all of SavvyCal. As an MVP this can be as simple as linking directly to the developer's SavvyCal or Calendly link.

A PR addressing this issue should:

- [ ] Add a new field to developer profiles - scheduling link
- [ ] Show a "Schedule a meeting" button to businesses when viewing a conversation
- [ ] Open the scheduling link in a new tab

**Comment by jkostolansky** [comment]
🙋‍♂️

**Comment by joemasilotti** [comment]
Sweet! All yours @jkostolansky.

**Comment by jkostolansky** [comment]
Thanks! Couple of questions to begin with:

1. Any link restrictions? For example, do you want to validate only if it's a URL, or something more?

2. Where in the dev profile form do you want the link field? Online presence, or somewhere else?

3. Where in the dev profile do you want to show the link? On the right, under "Private information"? As a "Schedule a meeting" button?

4. Where do you want the "Schedule a meeting" button in the conversation?

**Comment by joemasilotti** [comment]
1. Let's restrict to popular calendar services for now: SavvyCal, Calendly, and Cal.com
2. Let's add a new section since we will want to add a bit of copy on _why_ someone would want to add their scheduling link
3. The button will only go on the conversation screen - I want businesses to at least reach out via RailsDevs first before scheduling a call
4. Add the link on the conversation screen in-between the bottom most message and the input field - more links/buttons will be going here soon!
