### ISSUE TITLE
Convert hiring agreement to in-app DocuSign

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#835]
Businesses are required to agree to the lates hiring terms before paying for a subscription. I'd love for this to be more official than a checkbox.

<img width="649" alt="image" src="https://user-images.githubusercontent.com/2092156/227379823-b356ed0c-5b0b-42b0-b4fe-cfe6dc91166b.png">

After some light research, it seems like we can use [DocuSign's Ruby gem](https://github.com/docusign/docusign-esign-ruby-client) to redirect someone to a hosted DocuSign document for them to sign. Right in their browser!

A PR addressing this issue should:

- [ ] Rework the signed hiring agreement to use DocuSign's embedded document signing
- [ ] Listen for the callback to ensure a business has signed the doc before continuing

I'm also open to use an alternative if you have experience with a different service or there is a bootstrapped/Rails-powered tool!

**Comment by joemasilotti** [comment]
Here's some example code from the DocuSign repo: https://github.com/docusign/code-examples-ruby/blob/main/app/services/e_sign/eg001_embedded_signing_service.rb

**Comment by kaushikhande** [comment]
Hi @joemasilotti I would like to work on this.

**Comment by joemasilotti** [comment]
Sure thing! Let me know if you have any questions - otherwise I'll check in in about a week.

**Comment by joemasilotti** [comment]
Hey @kaushikhande, any progress on this one? It has been about 2 weeks. Let me know if you need help or have questions.

Otherwise, I'd like to open this up for someone else to work on. Thanks!

**Comment by kaushikhande** [comment]
@joemasilotti Please take this up for someone else.

**Comment by MikeRayUX** [comment]
I'll take this one if no one is ahead of me!

**Comment by joemasilotti** [comment]
Thanks for the heads up! @MikeRayUX, all yours.

**Comment by sonyco-4u** [comment]
I'll take this one if no one is ahead of me!
