### ISSUE TITLE
Rework "Recently Active" badge

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#841]
> Note: This is currently blocked by #777.

Currently, the "Recently Active" badge is awarded to developers who do one or more of the following in the past week:

* Add their profile
* Update their profile
* Send a message

With the new "High response rate" badge I no longer see the value of updating this badge when a developer sends a message. I'd also like to split out new vs. updated profiles.

A PR addressing this issue should:

- [ ] _Not_ apply the "Recently active" badge when a developer sends a message
- [ ] Apply a new "New profile" badge when a developer adds their profile
- [ ] Rename "Recently active" to "Recently updated"

**Comment by nnahgodspower122** [comment]
hi @joemasilotti I can work on this issue

**Comment by joemasilotti** [comment]
Unfortunately this is till blocked (see the first line of the issue). But when it opens up feel free to comment again to claim it!

**Comment by jkostolansky** [comment]
@joemasilotti What about a `blocked` issue label, wouldn't it be clearer?

**Comment by joemasilotti** [comment]
Good idea. Done!

**Comment by joemasilotti** [comment]
Closed via #856.
