### ISSUE TITLE
Fix duplicated protocol prefix in input fields

### ISSUE THREAD

**Issue by jkostolansky** [joemasilotti/railsdevs.com#842]
Currently, there are some form fields in the UI using an `https://` input pefix. Namely:

- Business
  - `website`
- Developer
  - `website`
  - `mastodon`
  - `scheduling_link`

However, these attributes don't have any validation, and the protocol prefix of the pasted link (`http(s)://`) is somewhat duplicated in the form. It should be clear from this screenshot:

![CleanShot 2023-03-25 at 21 13 22](https://user-images.githubusercontent.com/3950656/227739405-375f8e41-7e4e-4cf9-8279-385cade59c19.png)

A PR addressing this issue should:

- [ ] Take into account and refactor the existing solution for other online presence links (Github, Twitter etc.)
- [ ] Prevent showing duplicated `http(s)://` protocol prefix in the UI
- [ ] Add validation for these URL attributes

**Comment by jkostolansky** [comment]
@joemasilotti, did I forget something?

How would you like the link to be saved in the DB? Two options:

1. Save it with the `http(s)://` protocol, hide it only in the UI input field.
2. Remove the `http(s)://` protocol prefix _before_ saving it to the DB.

**Comment by joemasilotti** [comment]
I think I'm ready to "force" everyone to use https.

Let's...

1. Strip out the protocol from before saving it to the database
2. Note show the protocol in the UI
3. Always prepend a URL with `https://`
