### ISSUE TITLE
Account vs. User (take 2)

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#843]
> To keep things tidy, this is a revamp of #237.

Right now we are seeing a lot of difficulties in distinguishing a business vs. user "account" in #806. I think a lot of this headache (and complex queries) could be solved by having official business and developer _accounts_.

I want to solve for the absolute minimum experience:

1. A user can have 0 or 1 developer profiles
    * A developer is associated with exactly 1 user
3. A user can have 0 or 1 business profiles
    * A business is associated with exactly 1 user

I understand that a business might want to have multiple users associated with their account. But that can come later. Right now the goal is to understand which context a user is in.

I'm thinking we have a join table between `User` and `Business`/`Developer` called `Membership` or `Account`. In the user dropdown, if a user has both a business account _and_ a developer account they see some UI to switch between the two.

The big modeling changes that need to occur are:

1. `current_account` exposed like `current_user` (see the old issue for links on ideas)
1. Most of the relationships on `User` need to move to `Account`

From there, we can clean up a lot of the code around messages and conversations. For example,

```ruby
# app/controllers/messages_controller.rb:35

def sender
  if conversation.business?(current_user)
    current_user.business
  elsif conversation.developer?(current_user)
    current_user.developer
  end
end
```

Code like this can be simplified to `def sender = current_account.profile`!

**Comment by sarvaiyanidhi** [comment]
Hi Joe.. I would like to take up this issue.. Can you please assign it to me?

**Comment by joemasilotti** [comment]
All yours, thanks @sarvaiyanidhi!

**Comment by sarvaiyanidhi** [comment]
Hi @joemasilotti I was thinking on changes to be done for adding account for developers and business

I have thought of below migration and association changes for the same. 

Account table:
- id
- user_id
- account_type (either "business" or "developer")

Developer table:
- Replace user_id with account_id

Business table:
- Replace user_id with account_id

User Model Association:
- User has_many :accounts, dependent: :destroy
- User has_one :current_account, -> { where(account_type: ['business', 'developer']) }, class_name: 'Account', dependent: :destroy
- User has_one :business, through: :current_account, source: :business, class_name: 'Business'
- User has_one :developer, through: :current_account, source: :developer, class_name: 'Developer'

Account Model Association:
- Account belongs_to :user
- Account has_one :business, dependent: :destroy
- Account has_one :developer, dependent: :destroy

Business Model Association:
- Business belongs_to :account
- Business has_one :user, through: :account

Developer Model Association:
- Developer belongs_to :account
- Developer has_one :user, through: :account

Can you confirm above suggested changes are in align or do you have any recommend any modification in it?

**Comment by sonyco-4u** [comment]
I'll take this one if no one is ahead of me!

**Comment by joemasilotti** [comment]
I'm doing some Spring cleaning of the repo and going to put this on hold for a bit. I'll open it up again (so you will get notified) when it is ready!

**Comment by sonyco-4u** [comment]
Okay noted
