### ISSUE TITLE
Fixing Selenium::WebDriver::Error::UnknownError

### ISSUE THREAD

**Issue by JuzerShakir** [joemasilotti/railsdevs.com#884]
### What triggers `Selenium::WebDriver::Error::UnknownError` ?

When I run `rails test:system`, I get the following error log:
```
WARN Selenium [:selenium_manager] The chromedriver version (116.0.5845.187) detected in PATH at /usr/bin/chromedriver might not be compatible with the detected chrome version (117.0.5938.88); currently, chromedriver 117.0.5938.88 is recommended for chrome 117.*, so it is advised to delete the driver in PATH and retry 
```

As you can see, the error message clearly states that I am currently using `chromedriver` version `116.0.5845.187` which is not compatible with the `chrome` browser version `117.0.5938.88` I am using. 
For you, the version of chromedriver & the Chrome browser might vary but if they are a mismatch then this error is likely going to occur.

[ChromDivers' official documentation](https://chromedriver.chromium.org/downloads/version-selection) clearly states that if you're using Chrome browser version `115+` you don't need to install Chromedriver separately as it comes bundled with Chrome. 

So in order to use the latest Chromedriver, all you need to do is uninstall Chromedriver that was manually installed:
```
sudo apt-get remove chromium-chromedriver 
```

And now when you run `rails test:system` it will use the latest Chromedriver installed via Chrome browser and run the test successfully.

**Comment by JuzerShakir** [comment]
This isn't a bug from us developers but rather of the user who might face such an issue just as I did!  It took me almost an hour to figure this out and I don't want other developers to spend their valuable time on this but rather get up & running on what they want to implement or check.

So I was thinking of adding this info to `README.md` or elsewhere where if someone does face such an issue they would be able to debug right away.

Thoughts?

**Comment by joemasilotti** [comment]
Having this in the issues is good enough for me. Thanks @JuzerShakir!
