### ISSUE TITLE
Mail not being sent in conversations

### ISSUE THREAD

**Issue by aimljobs** [joemasilotti/railsdevs.com#899]
When a business messages a developer, the developer receives a notification on the dashboard, but the mail is not being sent.

Do we need to perform any additional steps in Postmark?

My message_mailer.rb:

![image](https://github.com/joemasilotti/railsdevs.com/assets/156516460/2380c4a8-ec09-46d3-8767-3a4db4e0559e)

**Comment by joemasilotti** [comment]
This issue is not present on railsdevs.com. Check the [production settings documentation](https://github.com/joemasilotti/railsdevs.com/blob/main/docs/production_settings.md) for information on what needs to be configured.

**Comment by aimljobs** [comment]
Thanks @joemasilotti! The email confirmation is working fine, but the mail delivery incase new message arrives is not working. I've followed this doc and have correctly set the `postmark_api_token`
