### ISSUE TITLE
'Share link' Stimulus error on Firefox (Desktop)

### ISSUE THREAD

**Issue by manufarez** [joemasilotti/railsdevs.com#901]
## Describe the bug

'Share link' copy to clipboard button doesn't work on Firefox (Desktop). It doesn't add the profile URL to the clipboard.

## To reproduce

1. Go to '/developers/[developer_id]
2. Click on 'Share'
3. Click on 'Copy link'

## Actual behavior

No URL is copied to the clipboard

Console error:
```
Error invoking action "click->clipboard#copy"

 ReferenceError: ClipboardItem is not defined
 ```

## Additional context
Firefox 125.0.3 (64-bit) / No adblocker JS-block

**Comment by joemasilotti** [comment]
Thanks for the report! It looks like this will be added to Firefox ["soon"](https://caniuse.com/?search=ClipboardItem) - so I'm happy to close this out until the browser catches up.
