### ISSUE TITLE
Migrate to railsdevs.com 🥳

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#94]
**Is your feature request related to a problem? Please describe.**

I recently purchased `railsdevs.com` and want to transfer of the site.

**Describe the solution you'd like**

Visiting `railsdevs.com` renders the current site. Visiting `railsdevs.io` or `www.railsdevs.io` redirects to `railsdevs.com`.

**Describe alternatives you've considered**

Keeping the `.io`.

**Comment by vamsipavanmahesh** [comment]
Let's gooo 🚀
